/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { PaygenticError } from "./paygenticerror.js";

/**
 * Price cannot be deleted because a live plan still references it
 */
export type DeletePriceConflictErrorData = {
  error?: string | undefined;
  message?: string | undefined;
  details?: operations.DeletePriceDetails | undefined;
};

/**
 * Price cannot be deleted because a live plan still references it
 */
export class DeletePriceConflictError extends PaygenticError {
  error?: string | undefined;
  details?: operations.DeletePriceDetails | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeletePriceConflictErrorData;

  constructor(
    err: DeletePriceConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.details != null) this.details = err.details;

    this.name = "DeletePriceConflictError";
  }
}

/** @internal */
export const DeletePriceConflictError$inboundSchema: z.ZodType<
  DeletePriceConflictError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  message: z.string().optional(),
  details: z.lazy(() => operations.DeletePriceDetails$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeletePriceConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
