/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { PaygenticError } from "./paygenticerror.js";

export type ValidationErrorData = {
  /**
   * Error type indicating validation failure
   */
  error?: models.ErrorEnum | undefined;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Array of field-specific validation errors
   */
  errors: Array<models.ErrorT>;
};

export class ValidationError extends PaygenticError {
  /**
   * Error type indicating validation failure
   */
  error?: models.ErrorEnum | undefined;
  /**
   * Array of field-specific validation errors
   */
  errors: Array<models.ErrorT>;

  /** The original data that was passed to this error instance. */
  data$: ValidationErrorData;

  constructor(
    err: ValidationErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    this.errors = err.errors;

    this.name = "ValidationError";
  }
}

/** @internal */
export const ValidationError$inboundSchema: z.ZodType<
  ValidationError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: models.ErrorEnum$inboundSchema.default("validation_error"),
  message: z.string(),
  errors: z.array(z.lazy(() => models.ErrorT$inboundSchema)),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ValidationError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
