/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billableMetricsCreate } from "../funcs/billableMetricsCreate.js";
import { billableMetricsGet } from "../funcs/billableMetricsGet.js";
import { billableMetricsList } from "../funcs/billableMetricsList.js";
import { billableMetricsUpdate } from "../funcs/billableMetricsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BillableMetrics extends ClientSDK {
  /**
   * Create
   *
   * @remarks
   * Create a new billable metric for a merchant organization. A `Billable Metric` represents a metric that can be used to measure the usage of a `Product`. It contains information about the metric, such as its name, description, and units.
   */
  async create(
    request: operations.CreateBillableMetricRequest,
    options?: RequestOptions,
  ): Promise<models.BillableMetric> {
    return unwrapAsync(billableMetricsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List
   */
  async list(
    request: operations.ListBillableMetricsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListBillableMetricsResponse> {
    return unwrapAsync(billableMetricsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   */
  async get(
    request: operations.GetBillableMetricRequest,
    options?: RequestOptions,
  ): Promise<models.BillableMetric> {
    return unwrapAsync(billableMetricsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update
   */
  async update(
    request: operations.UpdateBillableMetricRequest,
    options?: RequestOptions,
  ): Promise<models.BillableMetric> {
    return unwrapAsync(billableMetricsUpdate(
      this,
      request,
      options,
    ));
  }
}
