/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsCreateCost } from "../funcs/costsCreateCost.js";
import { costsDeleteCost } from "../funcs/costsDeleteCost.js";
import { costsGetCost } from "../funcs/costsGetCost.js";
import { costsGetCostSummary } from "../funcs/costsGetCostSummary.js";
import { costsListCosts } from "../funcs/costsListCosts.js";
import { costsUpdateCost } from "../funcs/costsUpdateCost.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Costs extends ClientSDK {
  /**
   * Create
   *
   * @remarks
   * Create a new metered cost for a product.
   */
  async createCost(
    request: operations.CreateCostRequest,
    options?: RequestOptions,
  ): Promise<models.Cost> {
    return unwrapAsync(costsCreateCost(
      this,
      request,
      options,
    ));
  }

  /**
   * List
   */
  async listCosts(
    request?: operations.ListCostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCostsResponse> {
    return unwrapAsync(costsListCosts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   */
  async getCost(
    request: operations.GetCostRequest,
    options?: RequestOptions,
  ): Promise<models.Cost> {
    return unwrapAsync(costsGetCost(
      this,
      request,
      options,
    ));
  }

  /**
   * Update
   */
  async updateCost(
    request: operations.UpdateCostRequest,
    options?: RequestOptions,
  ): Promise<models.Cost> {
    return unwrapAsync(costsUpdateCost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete
   */
  async deleteCost(
    request: operations.DeleteCostRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(costsDeleteCost(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Summary
   *
   * @remarks
   * Query usage data and compute cost for a specific cost configuration. To retrieve summaries for all costs belonging to a merchant, first call listCosts to obtain cost IDs, then call this endpoint in parallel for each ID.
   */
  async getCostSummary(
    request: operations.GetCostSummaryRequest,
    options?: RequestOptions,
  ): Promise<models.CostUsageResponse> {
    return unwrapAsync(costsGetCostSummary(
      this,
      request,
      options,
    ));
  }
}
