/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsCreate } from "../funcs/entitlementsCreate.js";
import { entitlementsList } from "../funcs/entitlementsList.js";
import { entitlementsListActive } from "../funcs/entitlementsListActive.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Entitlements extends ClientSDK {
  /**
   * List by Customer
   */
  async listActive(
    request: operations.GetActiveEntitlementsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetActiveEntitlementsResponse> {
    return unwrapAsync(entitlementsListActive(
      this,
      request,
      options,
    ));
  }

  /**
   * Create
   *
   * @remarks
   * Create an entitlement for a customer. This temporarily reserves funds in the customer's wallet to guarantee payment for future usage.
   */
  async create(
    request: models.CreateEntitlementRequest,
    options?: RequestOptions,
  ): Promise<models.Entitlement> {
    return unwrapAsync(entitlementsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List Entitlements
   *
   * @remarks
   * Retrieve all entitlements for a customer, optionally filtered by feature or product.
   */
  async list(
    request: operations.ListEntitlementsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListEntitlementsResponse> {
    return unwrapAsync(entitlementsList(
      this,
      request,
      options,
    ));
  }
}
