/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsV0Create } from "../funcs/entitlementsV0Create.js";
import { entitlementsV0ListActive } from "../funcs/entitlementsV0ListActive.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EntitlementsV0 extends ClientSDK {
  /**
   * List by Customer
   */
  async listActive(
    request: operations.GetActiveEntitlementsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetActiveEntitlementsResponse> {
    return unwrapAsync(entitlementsV0ListActive(
      this,
      request,
      options,
    ));
  }

  /**
   * Create
   *
   * @remarks
   * Create an entitlement for a customer. This temporarily reserves funds in the customer's wallet to guarantee payment for future usage.
   */
  async create(
    request: models.CreateEntitlementRequest,
    options?: RequestOptions,
  ): Promise<models.Entitlement> {
    return unwrapAsync(entitlementsV0Create(
      this,
      request,
      options,
    ));
  }
}
