/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesV2CreateInvoiceRefund } from "../funcs/invoicesV2CreateInvoiceRefund.js";
import { invoicesV2CreateLineItem } from "../funcs/invoicesV2CreateLineItem.js";
import { invoicesV2Get } from "../funcs/invoicesV2Get.js";
import { invoicesV2GetLineItems } from "../funcs/invoicesV2GetLineItems.js";
import { invoicesV2List } from "../funcs/invoicesV2List.js";
import { invoicesV2ListInvoiceRefunds } from "../funcs/invoicesV2ListInvoiceRefunds.js";
import { invoicesV2ListLineItems } from "../funcs/invoicesV2ListLineItems.js";
import { invoicesV2VoidInvoiceRefund } from "../funcs/invoicesV2VoidInvoiceRefund.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class InvoicesV2 extends ClientSDK {
  /**
   * List
   *
   * @remarks
   * List invoices with optional filters. Platform users can use nextActionAt=ready to get invoices ready for processing.
   */
  async list(
    request?: operations.ListInvoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListInvoicesResponse> {
    return unwrapAsync(invoicesV2List(
      this,
      request,
      options,
    ));
  }

  /**
   * List Line Items
   *
   * @remarks
   * List pending and invoiced line items for a subscription from the billing database. Returns exact fee amounts and estimated metered charges.
   */
  async listLineItems(
    request?: operations.ListLineItemsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.LineItemsResponse> {
    return unwrapAsync(invoicesV2ListLineItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Manual Line Item
   *
   * @remarks
   * Create a manual line item for a billing v1 subscription. Manual line items are ad-hoc charges or credits that flow through the same collection pipeline as auto-generated items. Exactly one of subscriptionId or invoiceId must be provided.
   */
  async createLineItem(
    request: operations.CreateLineItemRequest,
    options?: RequestOptions,
  ): Promise<models.LineItem> {
    return unwrapAsync(invoicesV2CreateLineItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   *
   * @remarks
   * Retrieve a single invoice with real-time aggregates (for ACTIVE/CLOSING/CLOSED) or cached aggregates (for finalized invoices). Optionally include line items with expand=lineItems.
   */
  async get(
    request: operations.GetInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesV2Get(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Line Items
   *
   * @remarks
   * Get paginated line items for an invoice
   */
  async getLineItems(
    request: operations.GetInvoiceLineItemsRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceLineItemsResponse> {
    return unwrapAsync(invoicesV2GetLineItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Refund Invoice
   *
   * @remarks
   * Issue a full refund against a paid invoice by creating a credit note. The invoice stays PAID; the refund is recorded as a child credit note. Accessible to the owning merchant or platform operators. Only works for invoices in PAID status that have not already been refunded. Full refund only — the entire invoice (subtotal + tax) is credited.
   */
  async createInvoiceRefund(
    request: operations.CreateInvoiceRefundRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceRefund> {
    return unwrapAsync(invoicesV2CreateInvoiceRefund(
      this,
      request,
      options,
    ));
  }

  /**
   * List Invoice Refunds
   *
   * @remarks
   * List the credit notes (refunds) recorded against an invoice. Accessible to the owning merchant or platform operators.
   */
  async listInvoiceRefunds(
    request: operations.ListInvoiceRefundsRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceRefundList> {
    return unwrapAsync(invoicesV2ListInvoiceRefunds(
      this,
      request,
      options,
    ));
  }

  /**
   * Void Invoice Refund
   *
   * @remarks
   * Void a previously-issued refund (credit note). Reverses the credit note in the tax provider and excludes it from revenue. Accessible to the owning merchant or platform operators.
   */
  async voidInvoiceRefund(
    request: operations.VoidInvoiceRefundRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceRefund> {
    return unwrapAsync(invoicesV2VoidInvoiceRefund(
      this,
      request,
      options,
    ));
  }
}
