/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesV2GetInvoice } from "../funcs/invoicesV2GetInvoice.js";
import { invoicesV2GetInvoiceLineItems } from "../funcs/invoicesV2GetInvoiceLineItems.js";
import { invoicesV2ListInvoices } from "../funcs/invoicesV2ListInvoices.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class InvoicesV2 extends ClientSDK {
  /**
   * List
   *
   * @remarks
   * List invoices with optional filters. Platform users can use nextActionAt=ready to get invoices ready for processing.
   */
  async listInvoices(
    request?: operations.ListInvoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListInvoicesResponse> {
    return unwrapAsync(invoicesV2ListInvoices(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   *
   * @remarks
   * Retrieve a single invoice with real-time aggregates (for ACTIVE/CLOSING/CLOSED) or cached aggregates (for finalized invoices). Optionally include line items with expand=lineItems.
   */
  async getInvoice(
    request: operations.GetInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesV2GetInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Line Items
   *
   * @remarks
   * Get paginated line items for an invoice from the analytics service
   */
  async getInvoiceLineItems(
    request: operations.GetInvoiceLineItemsRequest,
    options?: RequestOptions,
  ): Promise<models.InvoiceLineItemsResponse> {
    return unwrapAsync(invoicesV2GetInvoiceLineItems(
      this,
      request,
      options,
    ));
  }
}
