/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { itemsCreateItem } from "../funcs/itemsCreateItem.js";
import { itemsDeleteItem } from "../funcs/itemsDeleteItem.js";
import { itemsGetItem } from "../funcs/itemsGetItem.js";
import { itemsListItems } from "../funcs/itemsListItems.js";
import { itemsUpdateItem } from "../funcs/itemsUpdateItem.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Items extends ClientSDK {
  /**
   * Create
   */
  async createItem(
    request: operations.CreateItemRequest,
    options?: RequestOptions,
  ): Promise<models.Item> {
    return unwrapAsync(itemsCreateItem(
      this,
      request,
      options,
    ));
  }

  /**
   * List
   */
  async listItems(
    request?: operations.ListItemsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListItemsResponse> {
    return unwrapAsync(itemsListItems(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   */
  async getItem(
    request: operations.GetItemRequest,
    options?: RequestOptions,
  ): Promise<models.Item> {
    return unwrapAsync(itemsGetItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Update
   */
  async updateItem(
    request: operations.UpdateItemRequest,
    options?: RequestOptions,
  ): Promise<models.Item> {
    return unwrapAsync(itemsUpdateItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete
   */
  async deleteItem(
    request: operations.DeleteItemRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(itemsDeleteItem(
      this,
      request,
      options,
    ));
  }
}
