/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentSessionsListPaymentSessions } from "../funcs/paymentSessionsListPaymentSessions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentSessions extends ClientSDK {
  /**
   * List
   *
   * @remarks
   * List payment sessions for the authenticated merchant with optional filters. Supports filtering by subscriptionId, customerId, status, and entityType. When subscriptionId is provided the result includes both the subscription's own activation session (entityType='subscription') and any session attached to invoices for that subscription (entityType='invoice'). When customerId is provided the result covers the customer's full payment history: payment-link sessions (entityType='payment'), the activation sessions of the customer's subscriptions, and the sessions of those subscriptions' invoices.
   */
  async listPaymentSessions(
    request?: operations.ListPaymentSessionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPaymentSessionsResponse> {
    return unwrapAsync(paymentSessionsListPaymentSessions(
      this,
      request,
      options,
    ));
  }
}
