/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCreate } from "../funcs/paymentsCreate.js";
import { paymentsGet } from "../funcs/paymentsGet.js";
import { paymentsList } from "../funcs/paymentsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * List Payments
   *
   * @remarks
   * List payments for the authenticated merchant with optional filters.
   */
  async list(
    request?: operations.ListPaymentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPaymentsResponse> {
    return unwrapAsync(paymentsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Payment
   *
   * @remarks
   * Create a new payment for collecting a one-off charge. Returns a payment URL that can be shared with the customer.
   */
  async create(
    request: operations.CreatePaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Payment
   *
   * @remarks
   * Retrieve a single payment by ID.
   */
  async get(
    request: operations.GetPaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsGet(
      this,
      request,
      options,
    ));
  }
}
