/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsCreate } from "../funcs/productsCreate.js";
import { productsGet } from "../funcs/productsGet.js";
import { productsList } from "../funcs/productsList.js";
import { productsUpdate } from "../funcs/productsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Products extends ClientSDK {
  /**
   * Create
   */
  async create(
    request: operations.CreateProductRequest,
    options?: RequestOptions,
  ): Promise<models.Product> {
    return unwrapAsync(productsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List
   */
  async list(
    request?: operations.ListProductsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListProductsResponse> {
    return unwrapAsync(productsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   */
  async get(
    request: operations.GetProductRequest,
    options?: RequestOptions,
  ): Promise<models.Product> {
    return unwrapAsync(productsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update
   */
  async update(
    request: operations.UpdateProductRequest,
    options?: RequestOptions,
  ): Promise<models.Product> {
    return unwrapAsync(productsUpdate(
      this,
      request,
      options,
    ));
  }
}
