/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { profitabilityGetProfitability } from "../funcs/profitabilityGetProfitability.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Profitability extends ClientSDK {
  /**
   * Get profitability summary
   *
   * @remarks
   * Returns a per-customer profitability summary for a merchant over a date range. Each row aggregates revenue (from issued + paid invoices), cost (from metered cost discovery), profit, and margin. Customers are ranked by profit descending and capped at topN; the remainder is rolled into a single self-consistent 'Other' row whose revenue, cost, and profit reflect the same set of customers. Rows are inner-joined against the merchant's customer list, so orphaned meter subjects from deleted or unknown customers are dropped.
   */
  async getProfitability(
    request: operations.GetProfitabilityRequest,
    options?: RequestOptions,
  ): Promise<models.ProfitabilitySummaryResponse> {
    return unwrapAsync(profitabilityGetProfitability(
      this,
      request,
      options,
    ));
  }
}
