/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { revenueGet } from "../funcs/revenueGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Revenue extends ClientSDK {
  /**
   * Get revenue time series
   *
   * @remarks
   * Returns time-bucketed revenue data including usage charges, fee charges, and refunds. Data is aggregated by subscription with an optional 'other' bucket for subscriptions outside the top N.
   */
  async get(
    request: operations.GetRevenueRequest,
    options?: RequestOptions,
  ): Promise<models.RevenueTimeSeriesResponse> {
    return unwrapAsync(revenueGet(
      this,
      request,
      options,
    ));
  }
}
