/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesRulesCreate } from "../funcs/sourcesRulesCreate.js";
import { sourcesRulesDelete } from "../funcs/sourcesRulesDelete.js";
import { sourcesRulesGet } from "../funcs/sourcesRulesGet.js";
import { sourcesRulesList } from "../funcs/sourcesRulesList.js";
import { sourcesRulesUpdate } from "../funcs/sourcesRulesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rules extends ClientSDK {
  /**
   * List Rules
   *
   * @remarks
   * List all auto-acceptance rules for a source. These rules automatically approve pending source events when all conditions are met.
   */
  async list(
    request: operations.ListSourceRulesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListSourceRulesResponse> {
    return unwrapAsync(sourcesRulesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Rule
   *
   * @remarks
   * Create a rule for automatically approving source events. When a pending source event matches ALL conditions in a rule, it will be automatically approved and converted to a usage event. Rules are evaluated in order (lowest order number first), and the first matching rule triggers auto-approval. Maximum 10 rules per source.
   */
  async create(
    request: models.CreateRuleRequest,
    options?: RequestOptions,
  ): Promise<models.SourceRule> {
    return unwrapAsync(sourcesRulesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Rule
   */
  async get(
    request: operations.GetSourceRuleRequest,
    options?: RequestOptions,
  ): Promise<models.SourceRule> {
    return unwrapAsync(sourcesRulesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Rule
   */
  async update(
    request: operations.UpdateSourceRuleRequest,
    options?: RequestOptions,
  ): Promise<models.SourceRule> {
    return unwrapAsync(sourcesRulesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Rule
   */
  async delete(
    request: operations.DeleteSourceRuleRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sourcesRulesDelete(
      this,
      request,
      options,
    ));
  }
}
