/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCreateSubscription } from "../funcs/subscriptionsCreateSubscription.js";
import { subscriptionsGeneratePortalLink } from "../funcs/subscriptionsGeneratePortalLink.js";
import { subscriptionsGetSubscription } from "../funcs/subscriptionsGetSubscription.js";
import { subscriptionsListSubscriptions } from "../funcs/subscriptionsListSubscriptions.js";
import { subscriptionsTerminateSubscription } from "../funcs/subscriptionsTerminateSubscription.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Subscriptions extends ClientSDK {
  /**
   * List
   */
  async listSubscriptions(
    request?: operations.ListSubscriptionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListSubscriptionsResponse> {
    return unwrapAsync(subscriptionsListSubscriptions(
      this,
      request,
      options,
    ));
  }

  /**
   * Create
   *
   * @remarks
   * Creates a subscription for an existing customer or creates a new customer as part of the action.
   */
  async createSubscription(
    request: operations.CreateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.Subscription> {
    return unwrapAsync(subscriptionsCreateSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   */
  async getSubscription(
    request: operations.GetSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.Subscription> {
    return unwrapAsync(subscriptionsGetSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate Portal Link
   *
   * @remarks
   * Generates a secure, time-limited URL that allows customers to access their subscription data without authentication.
   */
  async generatePortalLink(
    request: operations.GeneratePortalLinkRequest,
    options?: RequestOptions,
  ): Promise<models.SubscriptionPortal> {
    return unwrapAsync(subscriptionsGeneratePortalLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Terminate
   *
   * @remarks
   * Terminates a subscription with a required reason. This endpoint is for merchant-initiated termination only.
   */
  async terminateSubscription(
    request: operations.TerminateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.Subscription> {
    return unwrapAsync(subscriptionsTerminateSubscription(
      this,
      request,
      options,
    ));
  }
}
