/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testClocksAdvance } from "../funcs/testClocksAdvance.js";
import { testClocksCreate } from "../funcs/testClocksCreate.js";
import { testClocksDelete } from "../funcs/testClocksDelete.js";
import { testClocksGet } from "../funcs/testClocksGet.js";
import { testClocksList } from "../funcs/testClocksList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TestClocks extends ClientSDK {
  /**
   * List
   *
   * @remarks
   * Retrieves a paginated list of test clocks
   */
  async list(
    request?: operations.ListTestClocksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListTestClocksResponse> {
    return unwrapAsync(testClocksList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create
   *
   * @remarks
   * Creates a new test clock with an optional initial time. If no time is provided, uses the current time.
   */
  async create(
    request: operations.CreateTestClockRequest,
    options?: RequestOptions,
  ): Promise<models.TestClock> {
    return unwrapAsync(testClocksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get
   *
   * @remarks
   * Retrieves details of a specific test clock
   */
  async get(
    request: operations.GetTestClockRequest,
    options?: RequestOptions,
  ): Promise<models.TestClock> {
    return unwrapAsync(testClocksGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Advance
   *
   * @remarks
   * Advances the test clock's current time. You can either specify a new absolute time or advance by a duration.
   */
  async advance(
    request: operations.AdvanceTestClockRequest,
    options?: RequestOptions,
  ): Promise<models.TestClock> {
    return unwrapAsync(testClocksAdvance(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete
   *
   * @remarks
   * Soft deletes a test clock. The clock will be marked as deleted but not removed from the database.
   */
  async delete(
    request: operations.DeleteTestClockRequest,
    options?: RequestOptions,
  ): Promise<models.TestClock> {
    return unwrapAsync(testClocksDelete(
      this,
      request,
      options,
    ));
  }
}
