/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @paygentic/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx customersCreate.example.ts
 */

import { Paygentic } from "@paygentic/sdk";

const paygentic = new Paygentic({
  bearerAuth: process.env["PAYGENTIC_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await paygentic.customers.create({
    consumer: {
      name: "Jane Smith",
      email: "jane@example.com",
      address: {
        city: "San Francisco",
        state: "CA",
        country: "US",
      },
    },
    merchantId: "org_YS8jkP59V71TdUvj",
  });

  console.log(result);
}

main().catch(console.error);
