/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type RequestBody2 = {
  /**
   * ISO 8601 duration format indicating clock advancement distance. Sample values: 'P1M' moves forward one month, 'P7D' moves forward seven days, 'PT2H' moves forward two hours, 'P1Y2M3DT4H5M6S' moves forward one year, two months, three days, four hours, five minutes, and six seconds
   */
  advanceBy: string;
};

export type RequestBody1 = {
  /**
   * New absolute time for the test clock (must be forward in time)
   */
  currentTime: Date;
};

export type AdvanceTestClockRequestBody = RequestBody1 | RequestBody2;

export type AdvanceTestClockRequest = {
  /**
   * Test clock ID
   */
  id: string;
  requestBody: RequestBody1 | RequestBody2;
};

/** @internal */
export type RequestBody2$Outbound = {
  advanceBy: string;
};

/** @internal */
export const RequestBody2$outboundSchema: z.ZodType<
  RequestBody2$Outbound,
  z.ZodTypeDef,
  RequestBody2
> = z.object({
  advanceBy: z.string(),
});

export function requestBody2ToJSON(requestBody2: RequestBody2): string {
  return JSON.stringify(RequestBody2$outboundSchema.parse(requestBody2));
}

/** @internal */
export type RequestBody1$Outbound = {
  currentTime: string;
};

/** @internal */
export const RequestBody1$outboundSchema: z.ZodType<
  RequestBody1$Outbound,
  z.ZodTypeDef,
  RequestBody1
> = z.object({
  currentTime: z.date().transform(v => v.toISOString()),
});

export function requestBody1ToJSON(requestBody1: RequestBody1): string {
  return JSON.stringify(RequestBody1$outboundSchema.parse(requestBody1));
}

/** @internal */
export type AdvanceTestClockRequestBody$Outbound =
  | RequestBody1$Outbound
  | RequestBody2$Outbound;

/** @internal */
export const AdvanceTestClockRequestBody$outboundSchema: z.ZodType<
  AdvanceTestClockRequestBody$Outbound,
  z.ZodTypeDef,
  AdvanceTestClockRequestBody
> = z.union([
  z.lazy(() => RequestBody1$outboundSchema),
  z.lazy(() => RequestBody2$outboundSchema),
]);

export function advanceTestClockRequestBodyToJSON(
  advanceTestClockRequestBody: AdvanceTestClockRequestBody,
): string {
  return JSON.stringify(
    AdvanceTestClockRequestBody$outboundSchema.parse(
      advanceTestClockRequestBody,
    ),
  );
}

/** @internal */
export type AdvanceTestClockRequest$Outbound = {
  id: string;
  RequestBody: RequestBody1$Outbound | RequestBody2$Outbound;
};

/** @internal */
export const AdvanceTestClockRequest$outboundSchema: z.ZodType<
  AdvanceTestClockRequest$Outbound,
  z.ZodTypeDef,
  AdvanceTestClockRequest
> = z.object({
  id: z.string(),
  requestBody: z.union([
    z.lazy(() => RequestBody1$outboundSchema),
    z.lazy(() => RequestBody2$outboundSchema),
  ]),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function advanceTestClockRequestToJSON(
  advanceTestClockRequest: AdvanceTestClockRequest,
): string {
  return JSON.stringify(
    AdvanceTestClockRequest$outboundSchema.parse(advanceTestClockRequest),
  );
}
