/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApproveSourceEventRequest = {
  id: string;
  eventId: string;
};

/** @internal */
export type ApproveSourceEventRequest$Outbound = {
  id: string;
  eventId: string;
};

/** @internal */
export const ApproveSourceEventRequest$outboundSchema: z.ZodType<
  ApproveSourceEventRequest$Outbound,
  z.ZodTypeDef,
  ApproveSourceEventRequest
> = z.object({
  id: z.string(),
  eventId: z.string(),
});

export function approveSourceEventRequestToJSON(
  approveSourceEventRequest: ApproveSourceEventRequest,
): string {
  return JSON.stringify(
    ApproveSourceEventRequest$outboundSchema.parse(approveSourceEventRequest),
  );
}
