/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type BatchCreateUsageEventsRequest = {
  events: Array<models.CreateUsageEventRequest>;
};

/** @internal */
export type BatchCreateUsageEventsRequest$Outbound = {
  events: Array<models.CreateUsageEventRequest$Outbound>;
};

/** @internal */
export const BatchCreateUsageEventsRequest$outboundSchema: z.ZodType<
  BatchCreateUsageEventsRequest$Outbound,
  z.ZodTypeDef,
  BatchCreateUsageEventsRequest
> = z.object({
  events: z.array(models.CreateUsageEventRequest$outboundSchema),
});

export function batchCreateUsageEventsRequestToJSON(
  batchCreateUsageEventsRequest: BatchCreateUsageEventsRequest,
): string {
  return JSON.stringify(
    BatchCreateUsageEventsRequest$outboundSchema.parse(
      batchCreateUsageEventsRequest,
    ),
  );
}
