/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BulkRejectSourceEventsRequestBody = {
  /**
   * IDs of events to reject
   */
  eventIds: Array<string>;
};

export type BulkRejectSourceEventsRequest = {
  id: string;
  requestBody: BulkRejectSourceEventsRequestBody;
};

/**
 * Bulk rejection results
 */
export type BulkRejectSourceEventsResponse = {
  /**
   * Number of rejected events
   */
  rejected?: number | undefined;
};

/** @internal */
export type BulkRejectSourceEventsRequestBody$Outbound = {
  eventIds: Array<string>;
};

/** @internal */
export const BulkRejectSourceEventsRequestBody$outboundSchema: z.ZodType<
  BulkRejectSourceEventsRequestBody$Outbound,
  z.ZodTypeDef,
  BulkRejectSourceEventsRequestBody
> = z.object({
  eventIds: z.array(z.string()),
});

export function bulkRejectSourceEventsRequestBodyToJSON(
  bulkRejectSourceEventsRequestBody: BulkRejectSourceEventsRequestBody,
): string {
  return JSON.stringify(
    BulkRejectSourceEventsRequestBody$outboundSchema.parse(
      bulkRejectSourceEventsRequestBody,
    ),
  );
}

/** @internal */
export type BulkRejectSourceEventsRequest$Outbound = {
  id: string;
  RequestBody: BulkRejectSourceEventsRequestBody$Outbound;
};

/** @internal */
export const BulkRejectSourceEventsRequest$outboundSchema: z.ZodType<
  BulkRejectSourceEventsRequest$Outbound,
  z.ZodTypeDef,
  BulkRejectSourceEventsRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => BulkRejectSourceEventsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function bulkRejectSourceEventsRequestToJSON(
  bulkRejectSourceEventsRequest: BulkRejectSourceEventsRequest,
): string {
  return JSON.stringify(
    BulkRejectSourceEventsRequest$outboundSchema.parse(
      bulkRejectSourceEventsRequest,
    ),
  );
}

/** @internal */
export const BulkRejectSourceEventsResponse$inboundSchema: z.ZodType<
  BulkRejectSourceEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  rejected: z.number().int().optional(),
});

export function bulkRejectSourceEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkRejectSourceEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkRejectSourceEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkRejectSourceEventsResponse' from JSON`,
  );
}
