/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BulkApproveSourceEventsRequestBody = {
  /**
   * IDs of events to approve
   */
  eventIds: Array<string>;
};

export type BulkApproveSourceEventsRequest = {
  id: string;
  requestBody: BulkApproveSourceEventsRequestBody;
};

export type Failed = {
  id?: string | undefined;
  error?: string | undefined;
};

export type BulkApproveSourceEventsDetails = {
  /**
   * IDs of successfully processed events
   */
  processed?: Array<string> | undefined;
  /**
   * Failed events with error messages
   */
  failed?: Array<Failed> | undefined;
};

/**
 * Bulk approval results
 */
export type BulkApproveSourceEventsResponse = {
  /**
   * Number of successfully approved events
   */
  processed?: number | undefined;
  /**
   * Number of events that failed to process
   */
  failed?: number | undefined;
  details?: BulkApproveSourceEventsDetails | undefined;
};

/** @internal */
export type BulkApproveSourceEventsRequestBody$Outbound = {
  eventIds: Array<string>;
};

/** @internal */
export const BulkApproveSourceEventsRequestBody$outboundSchema: z.ZodType<
  BulkApproveSourceEventsRequestBody$Outbound,
  z.ZodTypeDef,
  BulkApproveSourceEventsRequestBody
> = z.object({
  eventIds: z.array(z.string()),
});

export function bulkApproveSourceEventsRequestBodyToJSON(
  bulkApproveSourceEventsRequestBody: BulkApproveSourceEventsRequestBody,
): string {
  return JSON.stringify(
    BulkApproveSourceEventsRequestBody$outboundSchema.parse(
      bulkApproveSourceEventsRequestBody,
    ),
  );
}

/** @internal */
export type BulkApproveSourceEventsRequest$Outbound = {
  id: string;
  RequestBody: BulkApproveSourceEventsRequestBody$Outbound;
};

/** @internal */
export const BulkApproveSourceEventsRequest$outboundSchema: z.ZodType<
  BulkApproveSourceEventsRequest$Outbound,
  z.ZodTypeDef,
  BulkApproveSourceEventsRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => BulkApproveSourceEventsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function bulkApproveSourceEventsRequestToJSON(
  bulkApproveSourceEventsRequest: BulkApproveSourceEventsRequest,
): string {
  return JSON.stringify(
    BulkApproveSourceEventsRequest$outboundSchema.parse(
      bulkApproveSourceEventsRequest,
    ),
  );
}

/** @internal */
export const Failed$inboundSchema: z.ZodType<Failed, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    error: z.string().optional(),
  });

export function failedFromJSON(
  jsonString: string,
): SafeParseResult<Failed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Failed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Failed' from JSON`,
  );
}

/** @internal */
export const BulkApproveSourceEventsDetails$inboundSchema: z.ZodType<
  BulkApproveSourceEventsDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  processed: z.array(z.string()).optional(),
  failed: z.array(z.lazy(() => Failed$inboundSchema)).optional(),
});

export function bulkApproveSourceEventsDetailsFromJSON(
  jsonString: string,
): SafeParseResult<BulkApproveSourceEventsDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkApproveSourceEventsDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkApproveSourceEventsDetails' from JSON`,
  );
}

/** @internal */
export const BulkApproveSourceEventsResponse$inboundSchema: z.ZodType<
  BulkApproveSourceEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  processed: z.number().int().optional(),
  failed: z.number().int().optional(),
  details: z.lazy(() => BulkApproveSourceEventsDetails$inboundSchema)
    .optional(),
});

export function bulkApproveSourceEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkApproveSourceEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkApproveSourceEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkApproveSourceEventsResponse' from JSON`,
  );
}
