/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type CreateExternalReferenceRequest = {
  merchantId: string;
  /**
   * The type of Paygentic entity this external reference points at
   */
  entityType: models.EntityType;
  /**
   * Paygentic id of the entity, e.g. `itm_xxx`
   */
  entityId: string;
  /**
   * Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)
   */
  provider: string;
  /**
   * Identifier of the record in the external system
   */
  externalId: string;
  /**
   * Human-friendly name shown in UIs (e.g. a NetSuite financial-treatment name)
   */
  externalLabel?: string | undefined;
  /**
   * Provider-specific fields (e.g. `{ "sfObject": "Product2" }`)
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * Whether this reference claims `(provider, externalId)` — the code resolves back to this one entity. Unique per merchant; unclaimed references are aliases. **Omitting it claims the code.** Send `false` for a code that is only ever sent outward, such as a ledger account several items post to — claiming that refuses the second item to use it. The default is not derived from the provider: what a code is for is a property of the operation recording it, and one provider can both resolve an arriving code and be sent a selected one. Declaring a schema default here would defeat the distinction, because a generated client materialises the default into the request body and the caller can no longer express "I did not say".
   */
  isPrimary?: boolean | undefined;
  /**
   * Whether this is the code sent *to* the provider for this entity. At most one per `(entityType, entityId, provider)`. **Omit** to have the entity's first code for the provider designated automatically — see the note on `isPrimary` for why this carries no schema default.
   */
  isDefault?: boolean | undefined;
  /**
   * Take this code's claim from whichever entity currently holds it, in the same transaction.
   *
   * @remarks
   *
   * Without it, claiming a code another entity claims is a `409` identifying the holder — the right answer to an accident, and the common case. With it, the reassignment is the point.
   *
   * It exists because the alternative route — remove the old claim, then create the new one — leaves a window in which the code resolves to nothing. An arrival in that window is still recorded, untagged rather than rejected, so nothing is lost; but it is silent while it lasts and leaves work to repair.
   *
   * Deliberately opt-in, unlike moving a designation. A designation moves within one entity; a claim moves *between* entities and changes what future arrivals resolve to, which should never be a side effect of recording a code. Ignored when the write is not claiming the code.
   */
  moveClaim?: boolean | undefined;
};

/** @internal */
export type CreateExternalReferenceRequest$Outbound = {
  merchantId: string;
  entityType: string;
  entityId: string;
  provider: string;
  externalId: string;
  externalLabel?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  isPrimary?: boolean | undefined;
  isDefault?: boolean | undefined;
  moveClaim?: boolean | undefined;
};

/** @internal */
export const CreateExternalReferenceRequest$outboundSchema: z.ZodType<
  CreateExternalReferenceRequest$Outbound,
  z.ZodTypeDef,
  CreateExternalReferenceRequest
> = z.object({
  merchantId: z.string(),
  entityType: models.EntityType$outboundSchema,
  entityId: z.string(),
  provider: z.string(),
  externalId: z.string(),
  externalLabel: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  isPrimary: z.boolean().optional(),
  isDefault: z.boolean().optional(),
  moveClaim: z.boolean().optional(),
});

export function createExternalReferenceRequestToJSON(
  createExternalReferenceRequest: CreateExternalReferenceRequest,
): string {
  return JSON.stringify(
    CreateExternalReferenceRequest$outboundSchema.parse(
      createExternalReferenceRequest,
    ),
  );
}
