/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Billing timing preference: 'in_advance' (prepaid — charged upfront or drawn from a prepaid commitment) or 'in_arrears' (charged at period end).
 */
export const CreatePricePaymentTerm = {
  InArrears: "in_arrears",
  InAdvance: "in_advance",
} as const;
/**
 * Billing timing preference: 'in_advance' (prepaid — charged upfront or drawn from a prepaid commitment) or 'in_arrears' (charged at period end).
 */
export type CreatePricePaymentTerm = ClosedEnum<typeof CreatePricePaymentTerm>;

export type CreatePriceRequest = {
  /**
   * Unique identifier for a billable metric
   */
  billableMetricId?: string | undefined;
  /**
   * The unique identifier for the fee referred to by this price. Either billableMetricId or feeId must be provided.
   */
  feeId?: string | undefined;
  /**
   * Unique identifier for a pricing unit
   */
  pricingUnitId?: string | undefined;
  /**
   * Pricing calculation model. Required for billable metrics, optional for fees (defaults to 'standard'). Only 'standard' is accepted; for percentage/revenue-share use 'standard' with a unit-price multiplier. Legacy prices using 'dynamic'/'volume'/'percentage' stay readable and billable but cannot be created.
   */
  model?: models.PriceModelInput | undefined;
  /**
   * Line item label shown on customer invoices. Sample values: 'Claude Token Consumption', 'Storage Usage (GB)', 'Inference API Calls', 'Image Generation Count', 'Training Compute Hours', 'Data Transfer (TB)'
   */
  invoiceDisplayName: string;
  /**
   * Billing timing preference: 'in_advance' (prepaid — charged upfront or drawn from a prepaid commitment) or 'in_arrears' (charged at period end).
   */
  paymentTerm: CreatePricePaymentTerm;
  /**
   * ISO 8601 duration for recurring charges (e.g., 'P1M' for monthly, 'P1Y' for yearly) or 'P0D' for one-time charges. Required for fees, optional for billable metrics. Sample values: 'P0D' for one-time, 'P1M' for monthly recurring, 'P1Y' for yearly recurring
   */
  billingCadence?: string | null | undefined;
  properties: models.PriceProperties;
  feature?: models.PriceFeatureInput | undefined;
  /**
   * When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
   */
  grantDiscountEnabled?: boolean | undefined;
  /**
   * Quantity for invoice line items. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1.
   */
  quantity?: number | undefined;
};

/** @internal */
export const CreatePricePaymentTerm$outboundSchema: z.ZodNativeEnum<
  typeof CreatePricePaymentTerm
> = z.nativeEnum(CreatePricePaymentTerm);

/** @internal */
export type CreatePriceRequest$Outbound = {
  billableMetricId?: string | undefined;
  feeId?: string | undefined;
  pricingUnitId?: string | undefined;
  model?: string | undefined;
  invoiceDisplayName: string;
  paymentTerm: string;
  billingCadence?: string | null | undefined;
  properties: models.PriceProperties$Outbound;
  feature?: models.PriceFeatureInput$Outbound | undefined;
  grantDiscountEnabled: boolean;
  quantity?: number | undefined;
};

/** @internal */
export const CreatePriceRequest$outboundSchema: z.ZodType<
  CreatePriceRequest$Outbound,
  z.ZodTypeDef,
  CreatePriceRequest
> = z.object({
  billableMetricId: z.string().optional(),
  feeId: z.string().optional(),
  pricingUnitId: z.string().optional(),
  model: models.PriceModelInput$outboundSchema.optional(),
  invoiceDisplayName: z.string(),
  paymentTerm: CreatePricePaymentTerm$outboundSchema,
  billingCadence: z.nullable(z.string()).optional(),
  properties: models.PriceProperties$outboundSchema,
  feature: models.PriceFeatureInput$outboundSchema.optional(),
  grantDiscountEnabled: z.boolean().default(false),
  quantity: z.number().int().optional(),
});

export function createPriceRequestToJSON(
  createPriceRequest: CreatePriceRequest,
): string {
  return JSON.stringify(
    CreatePriceRequest$outboundSchema.parse(createPriceRequest),
  );
}
