/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Fields to create a new consumer. Will use an existing consumer if one exists with the same email address. Required if `consumerId` is not provided. Address with complete tax information (country, state, zipCode) is required for tax calculation when using Paygentic Tax.
 */
export type Consumer = {
  name: string;
  /**
   * Consumer email address. Sample values: 'customer@example.com', 'billing@company.com', 'admin@startup.io'
   */
  email: string;
  /**
   * Consumer phone number. Sample values: '+1-555-123-4567', '+44-20-7946-0958', '+49-30-12345678'
   */
  phone?: string | undefined;
  /**
   * Consumer address. For accurate tax calculation when using Paygentic Tax, provide complete address with country (ISO 3166-1 alpha-2), state, and zipCode. Incomplete addresses will skip tax calculation and use the plan's default tax rate instead.
   */
  address: models.Address;
};

export type CreateCustomerRequest = {
  /**
   * Fields to create a new consumer. Will use an existing consumer if one exists with the same email address. Required if `consumerId` is not provided. Address with complete tax information (country, state, zipCode) is required for tax calculation when using Paygentic Tax.
   */
  consumer?: Consumer | undefined;
  /**
   * Unique identifier for an organization
   */
  consumerId?: string | undefined;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  /**
   * Optional business tax registration identifier. Sample values: 'GB123456789' for UK VAT, 'DE123456789' for German VAT, 'FR12345678901' for French VAT. Supplying this value enables inter-company tax handling and exemption from standard tax collection.
   */
  taxId?: string | undefined;
  /**
   * An object mapping plan IDs, metric IDs, or 'default' to a tax rate percentage (e.g., 13 for 13%)
   */
  taxRates?: { [k: string]: number } | undefined;
};

/**
 * Customer created successfully
 */
export type CreateCustomerResponseBody2 = {
  customerId: string;
  /**
   * Indicates whether the consumer address is valid for tax calculation when using Paygentic Tax. If valid=false, tax calculation will be skipped and internal invoice flow with default tax rate will be used.
   */
  validTaxAddress: models.ValidTaxAddress;
};

/**
 * Customer already exists
 */
export type CreateCustomerResponseBody1 = {
  customerId: string;
  /**
   * Indicates whether the consumer address is valid for tax calculation when using Paygentic Tax. If valid=false, tax calculation will be skipped and internal invoice flow with default tax rate will be used.
   */
  validTaxAddress: models.ValidTaxAddress;
};

export type CreateCustomerResponse =
  | CreateCustomerResponseBody1
  | CreateCustomerResponseBody2;

/** @internal */
export type Consumer$Outbound = {
  name: string;
  email: string;
  phone?: string | undefined;
  address: models.Address$Outbound;
};

/** @internal */
export const Consumer$outboundSchema: z.ZodType<
  Consumer$Outbound,
  z.ZodTypeDef,
  Consumer
> = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  address: models.Address$outboundSchema,
});

export function consumerToJSON(consumer: Consumer): string {
  return JSON.stringify(Consumer$outboundSchema.parse(consumer));
}

/** @internal */
export type CreateCustomerRequest$Outbound = {
  consumer?: Consumer$Outbound | undefined;
  consumerId?: string | undefined;
  merchantId: string;
  taxId?: string | undefined;
  taxRates?: { [k: string]: number } | undefined;
};

/** @internal */
export const CreateCustomerRequest$outboundSchema: z.ZodType<
  CreateCustomerRequest$Outbound,
  z.ZodTypeDef,
  CreateCustomerRequest
> = z.object({
  consumer: z.lazy(() => Consumer$outboundSchema).optional(),
  consumerId: z.string().optional(),
  merchantId: z.string(),
  taxId: z.string().optional(),
  taxRates: z.record(z.number()).optional(),
});

export function createCustomerRequestToJSON(
  createCustomerRequest: CreateCustomerRequest,
): string {
  return JSON.stringify(
    CreateCustomerRequest$outboundSchema.parse(createCustomerRequest),
  );
}

/** @internal */
export const CreateCustomerResponseBody2$inboundSchema: z.ZodType<
  CreateCustomerResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string(),
  validTaxAddress: models.ValidTaxAddress$inboundSchema,
});

export function createCustomerResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<CreateCustomerResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCustomerResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCustomerResponseBody2' from JSON`,
  );
}

/** @internal */
export const CreateCustomerResponseBody1$inboundSchema: z.ZodType<
  CreateCustomerResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string(),
  validTaxAddress: models.ValidTaxAddress$inboundSchema,
});

export function createCustomerResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<CreateCustomerResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCustomerResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCustomerResponseBody1' from JSON`,
  );
}

/** @internal */
export const CreateCustomerResponse$inboundSchema: z.ZodType<
  CreateCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CreateCustomerResponseBody1$inboundSchema),
  z.lazy(() => CreateCustomerResponseBody2$inboundSchema),
]);

export function createCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCustomerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCustomerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCustomerResponse' from JSON`,
  );
}
