/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateCustomerPaymentMethodRequestBody = {
  /**
   * URL the customer is redirected to on success. When the page is iframed, success is reported via `postMessage` instead.
   */
  successRedirectUrl?: string | undefined;
  /**
   * URL the customer is redirected to on failure. When the page is iframed, failure is reported via `postMessage` instead.
   */
  failureRedirectUrl?: string | undefined;
  /**
   * Arbitrary key/value pairs to attach to the session.
   */
  metadata?: { [k: string]: any } | undefined;
};

export type CreateCustomerPaymentMethodRequest = {
  /**
   * The unique identifier of the customer.
   */
  id: string;
  requestBody?: CreateCustomerPaymentMethodRequestBody | undefined;
};

/** @internal */
export type CreateCustomerPaymentMethodRequestBody$Outbound = {
  successRedirectUrl?: string | undefined;
  failureRedirectUrl?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateCustomerPaymentMethodRequestBody$outboundSchema: z.ZodType<
  CreateCustomerPaymentMethodRequestBody$Outbound,
  z.ZodTypeDef,
  CreateCustomerPaymentMethodRequestBody
> = z.object({
  successRedirectUrl: z.string().optional(),
  failureRedirectUrl: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

export function createCustomerPaymentMethodRequestBodyToJSON(
  createCustomerPaymentMethodRequestBody:
    CreateCustomerPaymentMethodRequestBody,
): string {
  return JSON.stringify(
    CreateCustomerPaymentMethodRequestBody$outboundSchema.parse(
      createCustomerPaymentMethodRequestBody,
    ),
  );
}

/** @internal */
export type CreateCustomerPaymentMethodRequest$Outbound = {
  id: string;
  RequestBody?: CreateCustomerPaymentMethodRequestBody$Outbound | undefined;
};

/** @internal */
export const CreateCustomerPaymentMethodRequest$outboundSchema: z.ZodType<
  CreateCustomerPaymentMethodRequest$Outbound,
  z.ZodTypeDef,
  CreateCustomerPaymentMethodRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() =>
    CreateCustomerPaymentMethodRequestBody$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createCustomerPaymentMethodRequestToJSON(
  createCustomerPaymentMethodRequest: CreateCustomerPaymentMethodRequest,
): string {
  return JSON.stringify(
    CreateCustomerPaymentMethodRequest$outboundSchema.parse(
      createCustomerPaymentMethodRequest,
    ),
  );
}
