/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CreateTestClockRequest = {
  /**
   * Initial time for the test clock (defaults to current time). Cannot be more than 1 hour in the past to prevent accidental backdating. The 1-hour buffer accounts for clock drift and network delays.
   */
  currentTime?: Date | undefined;
  /**
   * Description of the test clock's purpose
   */
  description?: string | undefined;
  /**
   * The merchant organization that will own this test clock. If not provided, will be extracted from authenticated user's context.
   */
  merchantId?: string | undefined;
  /**
   * Name of the test clock
   */
  name?: string | undefined;
};

/** @internal */
export type CreateTestClockRequest$Outbound = {
  currentTime?: string | undefined;
  description?: string | undefined;
  merchantId?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const CreateTestClockRequest$outboundSchema: z.ZodType<
  CreateTestClockRequest$Outbound,
  z.ZodTypeDef,
  CreateTestClockRequest
> = z.object({
  currentTime: z.date().transform(v => v.toISOString()).optional(),
  description: z.string().optional(),
  merchantId: z.string().optional(),
  name: z.string().optional(),
});

export function createTestClockRequestToJSON(
  createTestClockRequest: CreateTestClockRequest,
): string {
  return JSON.stringify(
    CreateTestClockRequest$outboundSchema.parse(createTestClockRequest),
  );
}
