/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateLineItemRequest = {
  /**
   * Optional idempotency key. If provided, duplicate requests with the same key return the previously created item.
   */
  idempotencyKey?: string | undefined;
  createManualLineItemRequest: models.CreateManualLineItemRequest;
};

/** @internal */
export type CreateLineItemRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  CreateManualLineItemRequest: models.CreateManualLineItemRequest$Outbound;
};

/** @internal */
export const CreateLineItemRequest$outboundSchema: z.ZodType<
  CreateLineItemRequest$Outbound,
  z.ZodTypeDef,
  CreateLineItemRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  createManualLineItemRequest:
    models.CreateManualLineItemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "Idempotency-Key",
    createManualLineItemRequest: "CreateManualLineItemRequest",
  });
});

export function createLineItemRequestToJSON(
  createLineItemRequest: CreateLineItemRequest,
): string {
  return JSON.stringify(
    CreateLineItemRequest$outboundSchema.parse(createLineItemRequest),
  );
}
