/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The cost type. Only `metered` costs are supported; they track usage via events.
 */
export const CreateCostType = {
  Metered: "metered",
} as const;
/**
 * The cost type. Only `metered` costs are supported; they track usage via events.
 */
export type CreateCostType = ClosedEnum<typeof CreateCostType>;

/**
 * Aggregation method for the metered event.
 */
export const CreateCostAggregation = {
  Sum: "SUM",
  Count: "COUNT",
  Avg: "AVG",
  Min: "MIN",
  Max: "MAX",
  UniqueCount: "UNIQUE_COUNT",
  Latest: "LATEST",
} as const;
/**
 * Aggregation method for the metered event.
 */
export type CreateCostAggregation = ClosedEnum<typeof CreateCostAggregation>;

export type CreateCostRequest = {
  /**
   * The cost type. Only `metered` costs are supported; they track usage via events.
   */
  type: CreateCostType;
  /**
   * Human-readable name for the cost.
   */
  name: string;
  /**
   * Cost per unit, multiplied by measured quantity to compute total cost. Must be non-negative.
   */
  unitCost: number;
  /**
   * ISO 4217 currency code (e.g. USD, EUR).
   */
  currency: string;
  /**
   * Unique identifier for a product
   */
  productId: string;
  /**
   * Unit label for metered costs (e.g. 'token', 'request'). Only valid for metered costs.
   */
  unit?: string | undefined;
  /**
   * Aggregation method for the metered event.
   */
  aggregation: CreateCostAggregation;
  /**
   * CloudEvents type that identifies the metered event.
   */
  eventType: string;
  /**
   * JSONPath to extract numeric value from event data. Required for SUM/AVG/MIN/MAX/LATEST aggregations.
   */
  valueProperty?: string | undefined;
  /**
   * Map of dimension name to JSONPath for group-by queries. Only valid for metered costs.
   */
  groupBy?: { [k: string]: string } | undefined;
  /**
   * Unique identifier for an organization
   */
  merchantId?: string | undefined;
};

/** @internal */
export const CreateCostType$outboundSchema: z.ZodNativeEnum<
  typeof CreateCostType
> = z.nativeEnum(CreateCostType);

/** @internal */
export const CreateCostAggregation$outboundSchema: z.ZodNativeEnum<
  typeof CreateCostAggregation
> = z.nativeEnum(CreateCostAggregation);

/** @internal */
export type CreateCostRequest$Outbound = {
  type: string;
  name: string;
  unitCost: number;
  currency: string;
  productId: string;
  unit?: string | undefined;
  aggregation: string;
  eventType: string;
  valueProperty?: string | undefined;
  groupBy?: { [k: string]: string } | undefined;
  merchantId?: string | undefined;
};

/** @internal */
export const CreateCostRequest$outboundSchema: z.ZodType<
  CreateCostRequest$Outbound,
  z.ZodTypeDef,
  CreateCostRequest
> = z.object({
  type: CreateCostType$outboundSchema,
  name: z.string(),
  unitCost: z.number(),
  currency: z.string(),
  productId: z.string(),
  unit: z.string().optional(),
  aggregation: CreateCostAggregation$outboundSchema,
  eventType: z.string(),
  valueProperty: z.string().optional(),
  groupBy: z.record(z.string()).optional(),
  merchantId: z.string().optional(),
});

export function createCostRequestToJSON(
  createCostRequest: CreateCostRequest,
): string {
  return JSON.stringify(
    CreateCostRequest$outboundSchema.parse(createCostRequest),
  );
}
