/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Whether tax is added on top of the price (exclusive) or included in the price (inclusive)
 */
export const CreatePlanTaxBehavior = {
  Exclusive: "exclusive",
  Inclusive: "inclusive",
} as const;
/**
 * Whether tax is added on top of the price (exclusive) or included in the price (inclusive)
 */
export type CreatePlanTaxBehavior = ClosedEnum<typeof CreatePlanTaxBehavior>;

export type CreatePlanRequest = {
  /**
   * Recurring billing period frequency. Sample values: 'monthly' for monthly billing, 'yearly' for annual billing, 'weekly' for weekly billing
   */
  billingInterval?: string | undefined;
  /**
   * Three-letter ISO 4217 currency code for plan pricing. Must be one of the merchant's supported currencies. Sample values: 'USD' for US dollars, 'EUR' for euros, 'GBP' for British pounds
   */
  currency: string;
  /**
   * Default tax code for plan line items. Common values: 'eservice' (electronically supplied services), 'saas' (software as a service), 'consulting', 'ebook', 'standard', 'reduced', 'exempt'. Full list available via GET /tax/codes endpoint.
   */
  defaultTaxCode?: string | undefined;
  /**
   * Fallback tax rate percentage when automatic tax calculation fails. Sample values: 8.5 represents 8.5% tax, 10.0 represents 10% tax, 0 represents no tax
   */
  defaultTaxRate?: number | undefined;
  /**
   * Plan details explaining included features and limits. Sample values: 'Claude API access with 500K tokens monthly allowance', 'Unlimited cloud storage plus real-time analytics tools', 'Complete machine learning infrastructure with GPU access', 'Flexible usage-based pricing with no monthly commitment'
   */
  description?: string | undefined;
  /**
   * Plan name shown on billing statements. Sample values: 'LLM API Basic Plan', 'Data Warehouse Business', 'ML Platform Enterprise', 'Pay-Per-Use Model'
   */
  invoiceDisplayName?: string | undefined;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  /**
   * Plan identifier visible to customers. Sample values: 'Basic Tier', 'Business Package', 'Enterprise Solution', 'Metered Billing', 'Free Tier', 'Premium Access'
   */
  name: string;
  /**
   * Array of price IDs to associate with this plan
   */
  prices?: Array<string> | undefined;
  /**
   * Unique identifier for a product
   */
  productId?: string | undefined;
  /**
   * Whether tax is added on top of the price (exclusive) or included in the price (inclusive)
   */
  taxBehavior?: CreatePlanTaxBehavior | undefined;
  /**
   * Whether to send renewal reminder emails to customers before their subscription renews
   */
  renewalReminderEnabled?: boolean | undefined;
  /**
   * Number of days before renewal to send the reminder email
   */
  renewalReminderDays?: number | undefined;
};

/** @internal */
export const CreatePlanTaxBehavior$outboundSchema: z.ZodNativeEnum<
  typeof CreatePlanTaxBehavior
> = z.nativeEnum(CreatePlanTaxBehavior);

/** @internal */
export type CreatePlanRequest$Outbound = {
  billingInterval?: string | undefined;
  currency: string;
  defaultTaxCode: string;
  defaultTaxRate: number;
  description?: string | undefined;
  invoiceDisplayName?: string | undefined;
  merchantId: string;
  name: string;
  prices?: Array<string> | undefined;
  productId?: string | undefined;
  taxBehavior: string;
  renewalReminderEnabled: boolean;
  renewalReminderDays: number;
};

/** @internal */
export const CreatePlanRequest$outboundSchema: z.ZodType<
  CreatePlanRequest$Outbound,
  z.ZodTypeDef,
  CreatePlanRequest
> = z.object({
  billingInterval: z.string().optional(),
  currency: z.string(),
  defaultTaxCode: z.string().default("eservice"),
  defaultTaxRate: z.number().default(0),
  description: z.string().optional(),
  invoiceDisplayName: z.string().optional(),
  merchantId: z.string(),
  name: z.string(),
  prices: z.array(z.string()).optional(),
  productId: z.string().optional(),
  taxBehavior: CreatePlanTaxBehavior$outboundSchema.default("exclusive"),
  renewalReminderEnabled: z.boolean().default(true),
  renewalReminderDays: z.number().int().default(3),
});

export function createPlanRequestToJSON(
  createPlanRequest: CreatePlanRequest,
): string {
  return JSON.stringify(
    CreatePlanRequest$outboundSchema.parse(createPlanRequest),
  );
}
