/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type CreateExternalReferenceRequest = {
  merchantId: string;
  /**
   * The type of Paygentic entity this external reference points at
   */
  entityType: models.EntityType;
  /**
   * Paygentic id of the entity, e.g. `itm_xxx`
   */
  entityId: string;
  /**
   * Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)
   */
  provider: string;
  /**
   * Identifier of the record in the external system
   */
  externalId: string;
  /**
   * Human-friendly name shown in UIs (e.g. a NetSuite financial-treatment name)
   */
  externalLabel?: string | undefined;
  /**
   * Provider-specific fields (e.g. `{ "sfObject": "Product2" }`)
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * Whether this is the canonical reference for `(provider, externalId)`. The primary is unique per merchant; non-primary references are aliases.
   */
  isPrimary?: boolean | undefined;
  /**
   * Whether this is the default target for the entity + provider. At most one default per `(entityType, entityId, provider)`.
   */
  isDefault?: boolean | undefined;
};

/** @internal */
export type CreateExternalReferenceRequest$Outbound = {
  merchantId: string;
  entityType: string;
  entityId: string;
  provider: string;
  externalId: string;
  externalLabel?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  isPrimary: boolean;
  isDefault: boolean;
};

/** @internal */
export const CreateExternalReferenceRequest$outboundSchema: z.ZodType<
  CreateExternalReferenceRequest$Outbound,
  z.ZodTypeDef,
  CreateExternalReferenceRequest
> = z.object({
  merchantId: z.string(),
  entityType: models.EntityType$outboundSchema,
  entityId: z.string(),
  provider: z.string(),
  externalId: z.string(),
  externalLabel: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  isPrimary: z.boolean().default(true),
  isDefault: z.boolean().default(false),
});

export function createExternalReferenceRequestToJSON(
  createExternalReferenceRequest: CreateExternalReferenceRequest,
): string {
  return JSON.stringify(
    CreateExternalReferenceRequest$outboundSchema.parse(
      createExternalReferenceRequest,
    ),
  );
}
