/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CreateFeeRequest = {
  /**
   * Human-readable label identifying the fee. Sample values: 'Setup Fee', 'Monthly Subscription', 'Compliance Update', 'Annual License'
   */
  name: string;
  /**
   * Explanatory text describing what the fee represents. Sample values: 'One-time setup fee for new customers', 'Monthly base subscription charge', 'Yearly compliance and security update fee'
   */
  description: string;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  /**
   * Unique identifier for a product
   */
  productId: string;
};

/** @internal */
export type CreateFeeRequest$Outbound = {
  name: string;
  description: string;
  merchantId: string;
  productId: string;
};

/** @internal */
export const CreateFeeRequest$outboundSchema: z.ZodType<
  CreateFeeRequest$Outbound,
  z.ZodTypeDef,
  CreateFeeRequest
> = z.object({
  name: z.string(),
  description: z.string(),
  merchantId: z.string(),
  productId: z.string(),
});

export function createFeeRequestToJSON(
  createFeeRequest: CreateFeeRequest,
): string {
  return JSON.stringify(
    CreateFeeRequest$outboundSchema.parse(createFeeRequest),
  );
}
