/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Address is required for tax calculation. Must include: country (ISO 3166-1 alpha-2) and zipCode. The state/region field is required and validated for US/CA addresses only (custom validation in API logic). Postal code format is not validated but will be normalized.
 */
export type Address = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  /**
   * 2 character ISO 3166 country code
   */
  country: string;
  zipCode: string;
};

/**
 * Fields to create a new customer and consumer. Will use an existing consumer if one exists with the same email address. Required if `customerId` is not provided. Address with complete tax information (country, state, zipCode) is required for tax calculation when using Paygentic Tax.
 */
export type Customer = {
  name: string;
  email: string;
  phone?: string | undefined;
  address: Address;
  /**
   * An object mapping plan IDs, metric IDs, or 'default' to a tax rate percentage (e.g., 13 for 13%)
   */
  taxRates?: { [k: string]: number } | undefined;
};

/**
 * Optional redirect URLs after payment completion or failure. If not provided, uses default platform behavior.
 */
export type RedirectUrls = {
  /**
   * Redirect destination after successful payment. Sample values: 'https://app.example.com/success', 'https://dashboard.company.com/welcome', 'https://portal.startup.io/complete'
   */
  onSuccess?: string | undefined;
  /**
   * Redirect destination after failed payment. Sample values: 'https://app.example.com/payment-failed', 'https://dashboard.company.com/retry', 'https://portal.startup.io/error'
   */
  onFailure?: string | undefined;
};

export type CreateSubscriptionRequest = {
  /**
   * Enable automatic charging of invoices using stored payment methods. When true, invoices will be automatically paid using off-session payment. Defaults to false.
   */
  autoCharge?: boolean | undefined;
  /**
   * When true, forces tax rate to 0%. Use for customers with verified tax-exempt status.
   */
  taxExempt?: boolean | undefined;
  /**
   * Fields to create a new customer and consumer. Will use an existing consumer if one exists with the same email address. Required if `customerId` is not provided. Address with complete tax information (country, state, zipCode) is required for tax calculation when using Paygentic Tax.
   */
  customer?: Customer | undefined;
  /**
   * Unique identifier for a customer
   */
  customerId?: string | undefined;
  /**
   * Subscription expiration timestamp in ISO 8601 format. Sample values: '2024-12-31T23:59:59Z', '2025-01-15T10:30:00Z'. Omit for indefinite subscriptions.
   */
  endingAt?: Date | undefined;
  /**
   * Subscription identifier combining customer and service details. Sample values: 'TechCorp - LLM API Access', 'Analytics Co - Data Platform Enterprise', 'StartupXYZ - Image Generation Service', 'Enterprise Inc - ML Training Platform'
   */
  name: string;
  /**
   * Unique identifier for a plan
   */
  planId: string;
  /**
   * @deprecated Use minimumAccountBalance instead. Required initial wallet deposit amount. Sample values: '200.00' requires $200 prepaid balance for metered LLM usage, '1000.00' requires $1000 prepaid credits for data processing services, '50.00' requires $50 minimum for API call consumption
   */
  prefundAmount?: string | undefined;
  /**
   * Minimum wallet balance requirement in decimal dollars (e.g., '100.00'). Can be set to '0' to disable. The system will calculate the difference between this minimum and the customer's current balance, charging only what's needed to reach the minimum. If the customer already has sufficient balance, no charge is made. Note: If the calculated charge amount is below payment processor minimums (typically $1.00), it will be automatically adjusted upward to meet the minimum requirement. Sample values: '200.00' requires minimum $200 balance for metered LLM usage, '1000.00' requires minimum $1000 balance for data processing services
   */
  minimumAccountBalance?: string | undefined;
  /**
   * Optional redirect URLs after payment completion or failure. If not provided, uses default platform behavior.
   */
  redirectUrls?: RedirectUrls | undefined;
  /**
   * Subscription activation timestamp in ISO 8601 format. Sample values: '2024-01-15T10:30:00Z', '2024-02-01T00:00:00Z'
   */
  startedAt: Date;
  /**
   * Test clock identifier for simulating time-based billing scenarios. Sample values: 'tc_abc123xyz', 'tc_789def456'. Restricted to non-production environments (local, dev, sandbox). Must belong to the same merchant organization.
   */
  testClockId?: string | undefined;
  /**
   * Override plan setting for renewal reminder emails. When set, this subscription's setting takes precedence over the plan default. Set to true to enable reminders, false to disable, or null/omit to use plan default.
   */
  renewalReminderEnabled?: boolean | null | undefined;
  /**
   * Override plan setting for number of days before renewal to send the reminder. Only used if renewalReminderEnabled is true (or inherited from plan). Set to null to use plan default.
   */
  renewalReminderDays?: number | null | undefined;
  /**
   * Number of minutes until the payment session expires. Defaults to 240 minutes (4 hours) if not provided.
   */
  sessionExpiryMinutes?: number | undefined;
};

/** @internal */
export type Address$Outbound = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  country: string;
  zipCode: string;
};

/** @internal */
export const Address$outboundSchema: z.ZodType<
  Address$Outbound,
  z.ZodTypeDef,
  Address
> = z.object({
  line1: z.string().optional(),
  line2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string(),
  zipCode: z.string(),
});

export function addressToJSON(address: Address): string {
  return JSON.stringify(Address$outboundSchema.parse(address));
}

/** @internal */
export type Customer$Outbound = {
  name: string;
  email: string;
  phone?: string | undefined;
  address: Address$Outbound;
  taxRates?: { [k: string]: number } | undefined;
};

/** @internal */
export const Customer$outboundSchema: z.ZodType<
  Customer$Outbound,
  z.ZodTypeDef,
  Customer
> = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  address: z.lazy(() => Address$outboundSchema),
  taxRates: z.record(z.number()).optional(),
});

export function customerToJSON(customer: Customer): string {
  return JSON.stringify(Customer$outboundSchema.parse(customer));
}

/** @internal */
export type RedirectUrls$Outbound = {
  onSuccess?: string | undefined;
  onFailure?: string | undefined;
};

/** @internal */
export const RedirectUrls$outboundSchema: z.ZodType<
  RedirectUrls$Outbound,
  z.ZodTypeDef,
  RedirectUrls
> = z.object({
  onSuccess: z.string().optional(),
  onFailure: z.string().optional(),
});

export function redirectUrlsToJSON(redirectUrls: RedirectUrls): string {
  return JSON.stringify(RedirectUrls$outboundSchema.parse(redirectUrls));
}

/** @internal */
export type CreateSubscriptionRequest$Outbound = {
  autoCharge: boolean;
  taxExempt: boolean;
  customer?: Customer$Outbound | undefined;
  customerId?: string | undefined;
  endingAt?: string | undefined;
  name: string;
  planId: string;
  prefundAmount?: string | undefined;
  minimumAccountBalance?: string | undefined;
  redirectUrls?: RedirectUrls$Outbound | undefined;
  startedAt: string;
  testClockId?: string | undefined;
  renewalReminderEnabled?: boolean | null | undefined;
  renewalReminderDays?: number | null | undefined;
  sessionExpiryMinutes?: number | undefined;
};

/** @internal */
export const CreateSubscriptionRequest$outboundSchema: z.ZodType<
  CreateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  CreateSubscriptionRequest
> = z.object({
  autoCharge: z.boolean().default(false),
  taxExempt: z.boolean().default(false),
  customer: z.lazy(() => Customer$outboundSchema).optional(),
  customerId: z.string().optional(),
  endingAt: z.date().transform(v => v.toISOString()).optional(),
  name: z.string(),
  planId: z.string(),
  prefundAmount: z.string().optional(),
  minimumAccountBalance: z.string().optional(),
  redirectUrls: z.lazy(() => RedirectUrls$outboundSchema).optional(),
  startedAt: z.date().transform(v => v.toISOString()),
  testClockId: z.string().optional(),
  renewalReminderEnabled: z.nullable(z.boolean()).optional(),
  renewalReminderDays: z.nullable(z.number().int()).optional(),
  sessionExpiryMinutes: z.number().optional(),
});

export function createSubscriptionRequestToJSON(
  createSubscriptionRequest: CreateSubscriptionRequest,
): string {
  return JSON.stringify(
    CreateSubscriptionRequest$outboundSchema.parse(createSubscriptionRequest),
  );
}
