/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeletePriceRequest = {
  /**
   * The unique identifier of the price
   */
  id: string;
};

/** @internal */
export type DeletePriceRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeletePriceRequest$outboundSchema: z.ZodType<
  DeletePriceRequest$Outbound,
  z.ZodTypeDef,
  DeletePriceRequest
> = z.object({
  id: z.string(),
});

export function deletePriceRequestToJSON(
  deletePriceRequest: DeletePriceRequest,
): string {
  return JSON.stringify(
    DeletePriceRequest$outboundSchema.parse(deletePriceRequest),
  );
}
