/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteBillingScheduleRequest = {
  id: string;
};

/** @internal */
export type DeleteBillingScheduleRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteBillingScheduleRequest$outboundSchema: z.ZodType<
  DeleteBillingScheduleRequest$Outbound,
  z.ZodTypeDef,
  DeleteBillingScheduleRequest
> = z.object({
  id: z.string(),
});

export function deleteBillingScheduleRequestToJSON(
  deleteBillingScheduleRequest: DeleteBillingScheduleRequest,
): string {
  return JSON.stringify(
    DeleteBillingScheduleRequest$outboundSchema.parse(
      deleteBillingScheduleRequest,
    ),
  );
}
