/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteFeeRequest = {
  /**
   * The unique identifier of the fee
   */
  id: string;
};

export type DeleteFeeBlocker = {
  type?: string | undefined;
  count?: number | undefined;
};

export type DeleteFeeDetails = {
  blockers?: Array<DeleteFeeBlocker> | undefined;
};

/** @internal */
export type DeleteFeeRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteFeeRequest$outboundSchema: z.ZodType<
  DeleteFeeRequest$Outbound,
  z.ZodTypeDef,
  DeleteFeeRequest
> = z.object({
  id: z.string(),
});

export function deleteFeeRequestToJSON(
  deleteFeeRequest: DeleteFeeRequest,
): string {
  return JSON.stringify(
    DeleteFeeRequest$outboundSchema.parse(deleteFeeRequest),
  );
}

/** @internal */
export const DeleteFeeBlocker$inboundSchema: z.ZodType<
  DeleteFeeBlocker,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string().optional(),
  count: z.number().int().optional(),
});

export function deleteFeeBlockerFromJSON(
  jsonString: string,
): SafeParseResult<DeleteFeeBlocker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteFeeBlocker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteFeeBlocker' from JSON`,
  );
}

/** @internal */
export const DeleteFeeDetails$inboundSchema: z.ZodType<
  DeleteFeeDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  blockers: z.array(z.lazy(() => DeleteFeeBlocker$inboundSchema)).optional(),
});

export function deleteFeeDetailsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteFeeDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteFeeDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteFeeDetails' from JSON`,
  );
}
