/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DisconnectMerchantIntegrationRequest = {
  /**
   * The unique identifier of the merchant integration
   */
  id: string;
};

/** @internal */
export type DisconnectMerchantIntegrationRequest$Outbound = {
  id: string;
};

/** @internal */
export const DisconnectMerchantIntegrationRequest$outboundSchema: z.ZodType<
  DisconnectMerchantIntegrationRequest$Outbound,
  z.ZodTypeDef,
  DisconnectMerchantIntegrationRequest
> = z.object({
  id: z.string(),
});

export function disconnectMerchantIntegrationRequestToJSON(
  disconnectMerchantIntegrationRequest: DisconnectMerchantIntegrationRequest,
): string {
  return JSON.stringify(
    DisconnectMerchantIntegrationRequest$outboundSchema.parse(
      disconnectMerchantIntegrationRequest,
    ),
  );
}
