/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DownloadInvoicePdfRequest = {
  /**
   * The invoice ID
   */
  id: string;
};

/** @internal */
export type DownloadInvoicePdfRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadInvoicePdfRequest$outboundSchema: z.ZodType<
  DownloadInvoicePdfRequest$Outbound,
  z.ZodTypeDef,
  DownloadInvoicePdfRequest
> = z.object({
  id: z.string(),
});

export function downloadInvoicePdfRequestToJSON(
  downloadInvoicePdfRequest: DownloadInvoicePdfRequest,
): string {
  return JSON.stringify(
    DownloadInvoicePdfRequest$outboundSchema.parse(downloadInvoicePdfRequest),
  );
}
