/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApprovalRequest = {
  id: string;
};

/** @internal */
export type GetApprovalRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApprovalRequest$outboundSchema: z.ZodType<
  GetApprovalRequest$Outbound,
  z.ZodTypeDef,
  GetApprovalRequest
> = z.object({
  id: z.string(),
});

export function getApprovalRequestToJSON(
  getApprovalRequest: GetApprovalRequest,
): string {
  return JSON.stringify(
    GetApprovalRequest$outboundSchema.parse(getApprovalRequest),
  );
}
