/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetActiveEntitlementsRequest = {
  /**
   * The customer ID to get active entitlements for.
   */
  customerId: string;
  /**
   * The product ID to get active entitlements for.
   */
  productId?: string | undefined;
  /**
   * The subscription ID to get active entitlements for.
   */
  subscriptionId?: string | undefined;
};

export const GetActiveEntitlementsObject = {
  List: "list",
} as const;
export type GetActiveEntitlementsObject = ClosedEnum<
  typeof GetActiveEntitlementsObject
>;

export type GetActiveEntitlementsPagination = {
  offset?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
};

/**
 * List of active entitlements
 */
export type GetActiveEntitlementsResponse = {
  object: GetActiveEntitlementsObject;
  data?: Array<models.ActiveEntitlement> | undefined;
  pagination?: GetActiveEntitlementsPagination | undefined;
};

/** @internal */
export type GetActiveEntitlementsRequest$Outbound = {
  customerId: string;
  productId?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const GetActiveEntitlementsRequest$outboundSchema: z.ZodType<
  GetActiveEntitlementsRequest$Outbound,
  z.ZodTypeDef,
  GetActiveEntitlementsRequest
> = z.object({
  customerId: z.string(),
  productId: z.string().optional(),
  subscriptionId: z.string().optional(),
});

export function getActiveEntitlementsRequestToJSON(
  getActiveEntitlementsRequest: GetActiveEntitlementsRequest,
): string {
  return JSON.stringify(
    GetActiveEntitlementsRequest$outboundSchema.parse(
      getActiveEntitlementsRequest,
    ),
  );
}

/** @internal */
export const GetActiveEntitlementsObject$inboundSchema: z.ZodNativeEnum<
  typeof GetActiveEntitlementsObject
> = z.nativeEnum(GetActiveEntitlementsObject);

/** @internal */
export const GetActiveEntitlementsPagination$inboundSchema: z.ZodType<
  GetActiveEntitlementsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  offset: z.number().optional(),
  limit: z.number().optional(),
  total: z.number().optional(),
});

export function getActiveEntitlementsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetActiveEntitlementsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActiveEntitlementsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActiveEntitlementsPagination' from JSON`,
  );
}

/** @internal */
export const GetActiveEntitlementsResponse$inboundSchema: z.ZodType<
  GetActiveEntitlementsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: GetActiveEntitlementsObject$inboundSchema.default("list"),
  data: z.array(models.ActiveEntitlement$inboundSchema).optional(),
  pagination: z.lazy(() => GetActiveEntitlementsPagination$inboundSchema)
    .optional(),
});

export function getActiveEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetActiveEntitlementsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActiveEntitlementsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActiveEntitlementsResponse' from JSON`,
  );
}
