/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetEntitlementRequest = {
  /**
   * The unique identifier of the entitlement.
   */
  entitlementId: string;
};

/** @internal */
export type GetEntitlementRequest$Outbound = {
  entitlementId: string;
};

/** @internal */
export const GetEntitlementRequest$outboundSchema: z.ZodType<
  GetEntitlementRequest$Outbound,
  z.ZodTypeDef,
  GetEntitlementRequest
> = z.object({
  entitlementId: z.string(),
});

export function getEntitlementRequestToJSON(
  getEntitlementRequest: GetEntitlementRequest,
): string {
  return JSON.stringify(
    GetEntitlementRequest$outboundSchema.parse(getEntitlementRequest),
  );
}
