/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetFeePriceRequest = {
  /**
   * The unique identifier of the fee.
   */
  id: string;
  /**
   * The unique identifier of the subscription.
   */
  subscriptionId: string;
};

/** @internal */
export type GetFeePriceRequest$Outbound = {
  id: string;
  subscriptionId: string;
};

/** @internal */
export const GetFeePriceRequest$outboundSchema: z.ZodType<
  GetFeePriceRequest$Outbound,
  z.ZodTypeDef,
  GetFeePriceRequest
> = z.object({
  id: z.string(),
  subscriptionId: z.string(),
});

export function getFeePriceRequestToJSON(
  getFeePriceRequest: GetFeePriceRequest,
): string {
  return JSON.stringify(
    GetFeePriceRequest$outboundSchema.parse(getFeePriceRequest),
  );
}
