/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetInvoiceRequest = {
  /**
   * The invoice ID
   */
  id: string;
  /**
   * Comma-separated list of fields to expand. Currently supports: lineItems
   */
  expand?: string | undefined;
  /**
   * Page size for line items when expand=lineItems
   */
  lineItemsLimit?: number | undefined;
  /**
   * Pagination token for line items when expand=lineItems
   */
  lineItemsPageToken?: string | undefined;
};

/** @internal */
export type GetInvoiceRequest$Outbound = {
  id: string;
  expand?: string | undefined;
  lineItemsLimit: number;
  lineItemsPageToken?: string | undefined;
};

/** @internal */
export const GetInvoiceRequest$outboundSchema: z.ZodType<
  GetInvoiceRequest$Outbound,
  z.ZodTypeDef,
  GetInvoiceRequest
> = z.object({
  id: z.string(),
  expand: z.string().optional(),
  lineItemsLimit: z.number().int().default(100),
  lineItemsPageToken: z.string().optional(),
});

export function getInvoiceRequestToJSON(
  getInvoiceRequest: GetInvoiceRequest,
): string {
  return JSON.stringify(
    GetInvoiceRequest$outboundSchema.parse(getInvoiceRequest),
  );
}
