/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetMerchantIntegrationRequest = {
  /**
   * The unique identifier of the merchant integration
   */
  id: string;
};

/** @internal */
export type GetMerchantIntegrationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetMerchantIntegrationRequest$outboundSchema: z.ZodType<
  GetMerchantIntegrationRequest$Outbound,
  z.ZodTypeDef,
  GetMerchantIntegrationRequest
> = z.object({
  id: z.string(),
});

export function getMerchantIntegrationRequestToJSON(
  getMerchantIntegrationRequest: GetMerchantIntegrationRequest,
): string {
  return JSON.stringify(
    GetMerchantIntegrationRequest$outboundSchema.parse(
      getMerchantIntegrationRequest,
    ),
  );
}
