/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetProductRequest = {
  /**
   * The unique identifier of the product
   */
  id: string;
};

/** @internal */
export type GetProductRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetProductRequest$outboundSchema: z.ZodType<
  GetProductRequest$Outbound,
  z.ZodTypeDef,
  GetProductRequest
> = z.object({
  id: z.string(),
});

export function getProductRequestToJSON(
  getProductRequest: GetProductRequest,
): string {
  return JSON.stringify(
    GetProductRequest$outboundSchema.parse(getProductRequest),
  );
}
