/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetProfitabilityRequest = {
  /**
   * Merchant whose customers to summarize
   */
  merchantId: string;
  /**
   * Start of the time range (ISO 8601 format)
   */
  from: Date;
  /**
   * End of the time range (ISO 8601 format)
   */
  to: Date;
  /**
   * Number of top customers (by profit) to return individually. The rest are rolled into a single 'Other' row.
   */
  topN?: number | undefined;
  /**
   * ISO 4217 currency code to scope the summary. Defaults to the merchant's primary currency.
   */
  currency?: string | undefined;
  /**
   * When true, leave customers with neither revenue nor cost in the period out of `rows`. They are dropped before ranking, so they take no top-N slot and are not folded into the 'Other' row. `emptyCustomerCount` says how many there are either way.
   */
  excludeEmpty?: boolean | undefined;
  /**
   * When true, also return in `emptyCustomers` the customers counted in `emptyCustomerCount` that `rows` does not carry, so a caller can show the complete customer list.
   */
  includeEmpty?: boolean | undefined;
};

/** @internal */
export type GetProfitabilityRequest$Outbound = {
  merchantId: string;
  from: string;
  to: string;
  topN: number;
  currency?: string | undefined;
  excludeEmpty: boolean;
  includeEmpty: boolean;
};

/** @internal */
export const GetProfitabilityRequest$outboundSchema: z.ZodType<
  GetProfitabilityRequest$Outbound,
  z.ZodTypeDef,
  GetProfitabilityRequest
> = z.object({
  merchantId: z.string(),
  from: z.date().transform(v => v.toISOString()),
  to: z.date().transform(v => v.toISOString()),
  topN: z.number().int().default(10),
  currency: z.string().optional(),
  excludeEmpty: z.boolean().default(false),
  includeEmpty: z.boolean().default(false),
});

export function getProfitabilityRequestToJSON(
  getProfitabilityRequest: GetProfitabilityRequest,
): string {
  return JSON.stringify(
    GetProfitabilityRequest$outboundSchema.parse(getProfitabilityRequest),
  );
}
