/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Time bucket granularity
 */
export const BucketWidth = {
  Minute: "minute",
  Hour: "hour",
  Day: "day",
} as const;
/**
 * Time bucket granularity
 */
export type BucketWidth = ClosedEnum<typeof BucketWidth>;

export type GetRevenueRequest = {
  /**
   * Start of the time range (ISO 8601 format)
   */
  startTime: Date;
  /**
   * End of the time range (ISO 8601 format)
   */
  endTime: Date;
  /**
   * Time bucket granularity
   */
  bucketWidth?: BucketWidth | undefined;
  /**
   * Filter by merchant ID. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  merchantId?: string | undefined;
  /**
   * Filter by customer ID. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  customerId?: string | undefined;
  /**
   * Filter by subscription IDs. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  subscriptionIds?: Array<string> | undefined;
  /**
   * Limit to top N subscriptions by net revenue. Remaining subscriptions are aggregated into 'other'.
   */
  topN?: number | undefined;
};

/** @internal */
export const BucketWidth$outboundSchema: z.ZodNativeEnum<typeof BucketWidth> = z
  .nativeEnum(BucketWidth);

/** @internal */
export type GetRevenueRequest$Outbound = {
  startTime: string;
  endTime: string;
  bucketWidth: string;
  merchantId?: string | undefined;
  customerId?: string | undefined;
  subscriptionIds?: Array<string> | undefined;
  topN: number;
};

/** @internal */
export const GetRevenueRequest$outboundSchema: z.ZodType<
  GetRevenueRequest$Outbound,
  z.ZodTypeDef,
  GetRevenueRequest
> = z.object({
  startTime: z.date().transform(v => v.toISOString()),
  endTime: z.date().transform(v => v.toISOString()),
  bucketWidth: BucketWidth$outboundSchema.default("hour"),
  merchantId: z.string().optional(),
  customerId: z.string().optional(),
  subscriptionIds: z.array(z.string()).optional(),
  topN: z.number().int().default(10),
});

export function getRevenueRequestToJSON(
  getRevenueRequest: GetRevenueRequest,
): string {
  return JSON.stringify(
    GetRevenueRequest$outboundSchema.parse(getRevenueRequest),
  );
}
