/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Time bucket granularity for trend data
 */
export const BucketWidth = {
  Hour: "hour",
  Day: "day",
  Week: "week",
} as const;
/**
 * Time bucket granularity for trend data
 */
export type BucketWidth = ClosedEnum<typeof BucketWidth>;

/**
 * Group invoice data by dimension. Allowed values: 'plan' (max 5 groups, top 4 + 'other' when exceeding), 'customer' (max 25 groups, top 24 + 'other' when exceeding, sorted by revenue descending), 'currency' (one entry per currency, primary currency first then alphabetical). Note: groupBy values are mutually exclusive — combining them returns a 400 error. When groupBy=currency is active, top-level netRevenue, invoices, and payments fields are omitted; currencyBreakdown is the sole data source.
 */
export const GroupBy = {
  Plan: "plan",
  Customer: "customer",
  Currency: "currency",
} as const;
/**
 * Group invoice data by dimension. Allowed values: 'plan' (max 5 groups, top 4 + 'other' when exceeding), 'customer' (max 25 groups, top 24 + 'other' when exceeding, sorted by revenue descending), 'currency' (one entry per currency, primary currency first then alphabetical). Note: groupBy values are mutually exclusive — combining them returns a 400 error. When groupBy=currency is active, top-level netRevenue, invoices, and payments fields are omitted; currencyBreakdown is the sole data source.
 */
export type GroupBy = ClosedEnum<typeof GroupBy>;

export type GetRevenueRequest = {
  /**
   * Start of the time range (ISO 8601 format)
   */
  startTime: Date;
  /**
   * End of the time range (ISO 8601 format)
   */
  endTime: Date;
  /**
   * Time bucket granularity for trend data
   */
  bucketWidth?: BucketWidth | undefined;
  /**
   * Filter by merchant ID. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  merchantId?: string | undefined;
  /**
   * Filter by customer ID. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  customerId?: string | undefined;
  /**
   * Filter by subscription IDs. At least one of merchantId, subscriptionIds, or customerId must be provided.
   */
  subscriptionIds?: Array<string> | undefined;
  /**
   * Filter all results to a single ISO 4217 currency code (e.g. 'USD'). When omitted, results include all currencies.
   */
  currency?: string | undefined;
  /**
   * Group invoice data by dimension. Allowed values: 'plan' (max 5 groups, top 4 + 'other' when exceeding), 'customer' (max 25 groups, top 24 + 'other' when exceeding, sorted by revenue descending), 'currency' (one entry per currency, primary currency first then alphabetical). Note: groupBy values are mutually exclusive — combining them returns a 400 error. When groupBy=currency is active, top-level netRevenue, invoices, and payments fields are omitted; currencyBreakdown is the sole data source.
   */
  groupBy?: GroupBy | undefined;
};

/** @internal */
export const BucketWidth$outboundSchema: z.ZodNativeEnum<typeof BucketWidth> = z
  .nativeEnum(BucketWidth);

/** @internal */
export const GroupBy$outboundSchema: z.ZodNativeEnum<typeof GroupBy> = z
  .nativeEnum(GroupBy);

/** @internal */
export type GetRevenueRequest$Outbound = {
  startTime: string;
  endTime: string;
  bucketWidth: string;
  merchantId?: string | undefined;
  customerId?: string | undefined;
  subscriptionIds?: Array<string> | undefined;
  currency?: string | undefined;
  groupBy?: string | undefined;
};

/** @internal */
export const GetRevenueRequest$outboundSchema: z.ZodType<
  GetRevenueRequest$Outbound,
  z.ZodTypeDef,
  GetRevenueRequest
> = z.object({
  startTime: z.date().transform(v => v.toISOString()),
  endTime: z.date().transform(v => v.toISOString()),
  bucketWidth: BucketWidth$outboundSchema.default("day"),
  merchantId: z.string().optional(),
  customerId: z.string().optional(),
  subscriptionIds: z.array(z.string()).optional(),
  currency: z.string().optional(),
  groupBy: GroupBy$outboundSchema.optional(),
});

export function getRevenueRequestToJSON(
  getRevenueRequest: GetRevenueRequest,
): string {
  return JSON.stringify(
    GetRevenueRequest$outboundSchema.parse(getRevenueRequest),
  );
}
