/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetUserRequest = {
  id: string;
};

/** @internal */
export type GetUserRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetUserRequest$outboundSchema: z.ZodType<
  GetUserRequest$Outbound,
  z.ZodTypeDef,
  GetUserRequest
> = z.object({
  id: z.string(),
});

export function getUserRequestToJSON(getUserRequest: GetUserRequest): string {
  return JSON.stringify(GetUserRequest$outboundSchema.parse(getUserRequest));
}
