/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListEntitlementGrantsRequest = {
  /**
   * The unique identifier of the entitlement.
   */
  entitlementId: string;
  /**
   * Maximum number of grants to return per page.
   */
  limit?: number | undefined;
  /**
   * Number of grants to skip.
   */
  offset?: number | undefined;
  /**
   * When true, voided grants are included in the response.
   */
  includeVoided?: boolean | undefined;
};

export const ListEntitlementGrantsObject = {
  List: "list",
} as const;
export type ListEntitlementGrantsObject = ClosedEnum<
  typeof ListEntitlementGrantsObject
>;

/**
 * Successfully retrieved the list of grants.
 */
export type ListEntitlementGrantsResponse = {
  object: ListEntitlementGrantsObject;
  data: Array<models.Grant>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListEntitlementGrantsRequest$Outbound = {
  entitlementId: string;
  limit: number;
  offset: number;
  includeVoided: boolean;
};

/** @internal */
export const ListEntitlementGrantsRequest$outboundSchema: z.ZodType<
  ListEntitlementGrantsRequest$Outbound,
  z.ZodTypeDef,
  ListEntitlementGrantsRequest
> = z.object({
  entitlementId: z.string(),
  limit: z.number().int().default(20),
  offset: z.number().int().default(0),
  includeVoided: z.boolean().default(false),
});

export function listEntitlementGrantsRequestToJSON(
  listEntitlementGrantsRequest: ListEntitlementGrantsRequest,
): string {
  return JSON.stringify(
    ListEntitlementGrantsRequest$outboundSchema.parse(
      listEntitlementGrantsRequest,
    ),
  );
}

/** @internal */
export const ListEntitlementGrantsObject$inboundSchema: z.ZodNativeEnum<
  typeof ListEntitlementGrantsObject
> = z.nativeEnum(ListEntitlementGrantsObject);

/** @internal */
export const ListEntitlementGrantsResponse$inboundSchema: z.ZodType<
  ListEntitlementGrantsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListEntitlementGrantsObject$inboundSchema.default("list"),
  data: z.array(models.Grant$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listEntitlementGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitlementGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitlementGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitlementGrantsResponse' from JSON`,
  );
}
