/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type ListIntervalChangesRequest = {
  /**
   * Number of interval changes to return
   */
  limit?: string | undefined;
  /**
   * Number of interval changes to skip
   */
  offset?: string | undefined;
  /**
   * Only return changes recorded at or after this time
   */
  from?: Date | undefined;
  /**
   * Only return changes recorded before this time
   */
  to?: Date | undefined;
  /**
   * Only return changes with this reason.
   */
  changeReason?: models.ChangeReason | undefined;
};

/** @internal */
export type ListIntervalChangesRequest$Outbound = {
  limit: string;
  offset: string;
  from?: string | undefined;
  to?: string | undefined;
  changeReason?: string | undefined;
};

/** @internal */
export const ListIntervalChangesRequest$outboundSchema: z.ZodType<
  ListIntervalChangesRequest$Outbound,
  z.ZodTypeDef,
  ListIntervalChangesRequest
> = z.object({
  limit: z.string().default("10"),
  offset: z.string().default("0"),
  from: z.date().transform(v => v.toISOString()).optional(),
  to: z.date().transform(v => v.toISOString()).optional(),
  changeReason: models.ChangeReason$outboundSchema.optional(),
});

export function listIntervalChangesRequestToJSON(
  listIntervalChangesRequest: ListIntervalChangesRequest,
): string {
  return JSON.stringify(
    ListIntervalChangesRequest$outboundSchema.parse(listIntervalChangesRequest),
  );
}
