/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListCustomersRequest = {
  /**
   * Number of customers to return
   */
  limit?: number | undefined;
  /**
   * Number of customers to skip
   */
  offset?: number | undefined;
  /**
   * ID of the merchant organization to filter customers by
   */
  organizationId: string;
};

export const ListCustomersObject = {
  List: "list",
} as const;
export type ListCustomersObject = ClosedEnum<typeof ListCustomersObject>;

/**
 * List of customers retrieved successfully
 */
export type ListCustomersResponse = {
  object: ListCustomersObject;
  data: Array<models.Customer>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListCustomersRequest$Outbound = {
  limit: number;
  offset: number;
  organizationId: string;
};

/** @internal */
export const ListCustomersRequest$outboundSchema: z.ZodType<
  ListCustomersRequest$Outbound,
  z.ZodTypeDef,
  ListCustomersRequest
> = z.object({
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
  organizationId: z.string(),
});

export function listCustomersRequestToJSON(
  listCustomersRequest: ListCustomersRequest,
): string {
  return JSON.stringify(
    ListCustomersRequest$outboundSchema.parse(listCustomersRequest),
  );
}

/** @internal */
export const ListCustomersObject$inboundSchema: z.ZodNativeEnum<
  typeof ListCustomersObject
> = z.nativeEnum(ListCustomersObject);

/** @internal */
export const ListCustomersResponse$inboundSchema: z.ZodType<
  ListCustomersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListCustomersObject$inboundSchema,
  data: z.array(models.Customer$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomersResponse' from JSON`,
  );
}
