/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListAvailablePlansRequest = {
  /**
   * The customer to check subscriptions for. The merchant is derived from the customer record.
   */
  customerId: string;
  /**
   * Optional filter by product ID
   */
  productId?: string | undefined;
  /**
   * Optional search text to filter plan names (case-insensitive)
   */
  search?: string | undefined;
  /**
   * Number of plans to return
   */
  limit?: number | undefined;
  /**
   * Number of plans to skip
   */
  offset?: number | undefined;
};

export type ListAvailablePlansPagination = {
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

/**
 * List of available plans
 */
export type ListAvailablePlansResponse = {
  data?: Array<models.Plan> | undefined;
  pagination?: ListAvailablePlansPagination | undefined;
};

/** @internal */
export type ListAvailablePlansRequest$Outbound = {
  customerId: string;
  productId?: string | undefined;
  search?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListAvailablePlansRequest$outboundSchema: z.ZodType<
  ListAvailablePlansRequest$Outbound,
  z.ZodTypeDef,
  ListAvailablePlansRequest
> = z.object({
  customerId: z.string(),
  productId: z.string().optional(),
  search: z.string().optional(),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
});

export function listAvailablePlansRequestToJSON(
  listAvailablePlansRequest: ListAvailablePlansRequest,
): string {
  return JSON.stringify(
    ListAvailablePlansRequest$outboundSchema.parse(listAvailablePlansRequest),
  );
}

/** @internal */
export const ListAvailablePlansPagination$inboundSchema: z.ZodType<
  ListAvailablePlansPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  total: z.number().int().optional(),
});

export function listAvailablePlansPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListAvailablePlansPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAvailablePlansPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAvailablePlansPagination' from JSON`,
  );
}

/** @internal */
export const ListAvailablePlansResponse$inboundSchema: z.ZodType<
  ListAvailablePlansResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.Plan$inboundSchema).optional(),
  pagination: z.lazy(() => ListAvailablePlansPagination$inboundSchema)
    .optional(),
});

export function listAvailablePlansResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAvailablePlansResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAvailablePlansResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAvailablePlansResponse' from JSON`,
  );
}
