/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListMerchantIntegrationsRequest = {
  /**
   * Restrict results to a specific merchant. All active filters AND together.
   */
  merchantId?: string | undefined;
  /**
   * Filter by provider (e.g. `salesforce`).
   */
  provider?: models.MerchantIntegrationProvider | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * List of merchant integrations
 */
export type ListMerchantIntegrationsResponse = {
  data: Array<models.MerchantIntegration>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListMerchantIntegrationsRequest$Outbound = {
  merchantId?: string | undefined;
  provider?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListMerchantIntegrationsRequest$outboundSchema: z.ZodType<
  ListMerchantIntegrationsRequest$Outbound,
  z.ZodTypeDef,
  ListMerchantIntegrationsRequest
> = z.object({
  merchantId: z.string().optional(),
  provider: models.MerchantIntegrationProvider$outboundSchema.optional(),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

export function listMerchantIntegrationsRequestToJSON(
  listMerchantIntegrationsRequest: ListMerchantIntegrationsRequest,
): string {
  return JSON.stringify(
    ListMerchantIntegrationsRequest$outboundSchema.parse(
      listMerchantIntegrationsRequest,
    ),
  );
}

/** @internal */
export const ListMerchantIntegrationsResponse$inboundSchema: z.ZodType<
  ListMerchantIntegrationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.MerchantIntegration$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listMerchantIntegrationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMerchantIntegrationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMerchantIntegrationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMerchantIntegrationsResponse' from JSON`,
  );
}
