/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Filter by status
 */
export const ListOrdersStatus = {
  Draft: "draft",
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Cancelled: "cancelled",
} as const;
/**
 * Filter by status
 */
export type ListOrdersStatus = ClosedEnum<typeof ListOrdersStatus>;

/**
 * Filter by type
 */
export const ListOrdersType = {
  NewBusiness: "new_business",
  Renewal: "renewal",
  Expansion: "expansion",
} as const;
/**
 * Filter by type
 */
export type ListOrdersType = ClosedEnum<typeof ListOrdersType>;

export type ListOrdersRequest = {
  /**
   * Filter by merchant
   */
  merchantId?: string | undefined;
  /**
   * Filter by customer
   */
  customerId?: string | undefined;
  /**
   * Filter by status
   */
  status?: ListOrdersStatus | undefined;
  /**
   * Filter by type
   */
  type?: ListOrdersType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const ListOrdersStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListOrdersStatus
> = z.nativeEnum(ListOrdersStatus);

/** @internal */
export const ListOrdersType$outboundSchema: z.ZodNativeEnum<
  typeof ListOrdersType
> = z.nativeEnum(ListOrdersType);

/** @internal */
export type ListOrdersRequest$Outbound = {
  merchantId?: string | undefined;
  customerId?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListOrdersRequest$outboundSchema: z.ZodType<
  ListOrdersRequest$Outbound,
  z.ZodTypeDef,
  ListOrdersRequest
> = z.object({
  merchantId: z.string().optional(),
  customerId: z.string().optional(),
  status: ListOrdersStatus$outboundSchema.optional(),
  type: ListOrdersType$outboundSchema.optional(),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

export function listOrdersRequestToJSON(
  listOrdersRequest: ListOrdersRequest,
): string {
  return JSON.stringify(
    ListOrdersRequest$outboundSchema.parse(listOrdersRequest),
  );
}
