/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPlanVersionsRequest = {
  id: string;
  /**
   * Maximum number of versions to return
   */
  limit?: number | undefined;
  /**
   * Number of versions to skip
   */
  offset?: number | undefined;
};

export const ListPlanVersionsObject = {
  List: "list",
} as const;
export type ListPlanVersionsObject = ClosedEnum<typeof ListPlanVersionsObject>;

/**
 * List of plan versions
 */
export type ListPlanVersionsResponse = {
  object: ListPlanVersionsObject;
  data: Array<models.PlanVersionSummary>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListPlanVersionsRequest$Outbound = {
  id: string;
  limit: number;
  offset: number;
};

/** @internal */
export const ListPlanVersionsRequest$outboundSchema: z.ZodType<
  ListPlanVersionsRequest$Outbound,
  z.ZodTypeDef,
  ListPlanVersionsRequest
> = z.object({
  id: z.string(),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
});

export function listPlanVersionsRequestToJSON(
  listPlanVersionsRequest: ListPlanVersionsRequest,
): string {
  return JSON.stringify(
    ListPlanVersionsRequest$outboundSchema.parse(listPlanVersionsRequest),
  );
}

/** @internal */
export const ListPlanVersionsObject$inboundSchema: z.ZodNativeEnum<
  typeof ListPlanVersionsObject
> = z.nativeEnum(ListPlanVersionsObject);

/** @internal */
export const ListPlanVersionsResponse$inboundSchema: z.ZodType<
  ListPlanVersionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListPlanVersionsObject$inboundSchema,
  data: z.array(models.PlanVersionSummary$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listPlanVersionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPlanVersionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlanVersionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlanVersionsResponse' from JSON`,
  );
}
