/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListSalesforceAccountsRequest = {
  /**
   * Merchant whose Salesforce connection to use.
   */
  merchantId: string;
  /**
   * Optional name filter (LIKE match).
   */
  q?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * List of Salesforce accounts
 */
export type ListSalesforceAccountsResponse = {
  data: Array<{ [k: string]: any }>;
  totalSize: number;
  done: boolean;
};

/** @internal */
export type ListSalesforceAccountsRequest$Outbound = {
  merchantId: string;
  q?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListSalesforceAccountsRequest$outboundSchema: z.ZodType<
  ListSalesforceAccountsRequest$Outbound,
  z.ZodTypeDef,
  ListSalesforceAccountsRequest
> = z.object({
  merchantId: z.string(),
  q: z.string().optional(),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

export function listSalesforceAccountsRequestToJSON(
  listSalesforceAccountsRequest: ListSalesforceAccountsRequest,
): string {
  return JSON.stringify(
    ListSalesforceAccountsRequest$outboundSchema.parse(
      listSalesforceAccountsRequest,
    ),
  );
}

/** @internal */
export const ListSalesforceAccountsResponse$inboundSchema: z.ZodType<
  ListSalesforceAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.record(z.any())),
  totalSize: z.number().int(),
  done: z.boolean(),
});

export function listSalesforceAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSalesforceAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSalesforceAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSalesforceAccountsResponse' from JSON`,
  );
}
