/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter by dispute status
 */
export const ListDisputesStatus = {
  Pending: "pending",
  Accepted: "accepted",
  Declined: "declined",
} as const;
/**
 * Filter by dispute status
 */
export type ListDisputesStatus = ClosedEnum<typeof ListDisputesStatus>;

export type ListDisputesRequest = {
  /**
   * Filter disputes for a specific consumer. At least one of merchantId, customerId, or consumerId must be provided.
   */
  consumerId?: string | undefined;
  /**
   * Filter disputes for a specific customer. At least one of merchantId, customerId, or consumerId must be provided.
   */
  customerId?: string | undefined;
  /**
   * Number of disputes to return
   */
  limit?: number | undefined;
  /**
   * Filter disputes for a specific merchant. At least one of merchantId, customerId, or consumerId must be provided.
   */
  merchantId?: string | undefined;
  /**
   * Number of disputes to skip
   */
  offset?: number | undefined;
  /**
   * Filter by dispute status
   */
  status?: ListDisputesStatus | undefined;
};

export const ListDisputesObject = {
  List: "list",
} as const;
export type ListDisputesObject = ClosedEnum<typeof ListDisputesObject>;

export type ListDisputesPagination = {
  limit: number;
  offset: number;
  total: number;
  hasMore: boolean;
};

/**
 * Disputes retrieved successfully
 */
export type ListDisputesResponse = {
  object: ListDisputesObject;
  data: Array<models.DisputeWithCustomer>;
  pagination: ListDisputesPagination;
};

/** @internal */
export const ListDisputesStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListDisputesStatus
> = z.nativeEnum(ListDisputesStatus);

/** @internal */
export type ListDisputesRequest$Outbound = {
  consumerId?: string | undefined;
  customerId?: string | undefined;
  limit: number;
  merchantId?: string | undefined;
  offset: number;
  status?: string | undefined;
};

/** @internal */
export const ListDisputesRequest$outboundSchema: z.ZodType<
  ListDisputesRequest$Outbound,
  z.ZodTypeDef,
  ListDisputesRequest
> = z.object({
  consumerId: z.string().optional(),
  customerId: z.string().optional(),
  limit: z.number().int().default(10),
  merchantId: z.string().optional(),
  offset: z.number().int().default(0),
  status: ListDisputesStatus$outboundSchema.optional(),
});

export function listDisputesRequestToJSON(
  listDisputesRequest: ListDisputesRequest,
): string {
  return JSON.stringify(
    ListDisputesRequest$outboundSchema.parse(listDisputesRequest),
  );
}

/** @internal */
export const ListDisputesObject$inboundSchema: z.ZodNativeEnum<
  typeof ListDisputesObject
> = z.nativeEnum(ListDisputesObject);

/** @internal */
export const ListDisputesPagination$inboundSchema: z.ZodType<
  ListDisputesPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  total: z.number().int(),
  hasMore: z.boolean(),
});

export function listDisputesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListDisputesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDisputesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDisputesPagination' from JSON`,
  );
}

/** @internal */
export const ListDisputesResponse$inboundSchema: z.ZodType<
  ListDisputesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListDisputesObject$inboundSchema,
  data: z.array(models.DisputeWithCustomer$inboundSchema),
  pagination: z.lazy(() => ListDisputesPagination$inboundSchema),
});

export function listDisputesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDisputesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDisputesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDisputesResponse' from JSON`,
  );
}
