/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter events by status
 */
export const ListSourceEventsStatus = {
  Pending: "pending",
  Processed: "processed",
  Failed: "failed",
  Rejected: "rejected",
} as const;
/**
 * Filter events by status
 */
export type ListSourceEventsStatus = ClosedEnum<typeof ListSourceEventsStatus>;

export type ListSourceEventsRequest = {
  id: string;
  /**
   * Filter events by customer ID
   */
  customerId?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  /**
   * Filter events by status
   */
  status?: ListSourceEventsStatus | undefined;
  /**
   * Filter events by subscription ID
   */
  subscriptionId?: string | undefined;
};

/**
 * List of source events
 */
export type ListSourceEventsResponse = {
  data?: Array<models.SourceEvent> | undefined;
  /**
   * Offset-based pagination response.
   */
  pagination?: models.OffsetPagination | undefined;
};

/** @internal */
export const ListSourceEventsStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListSourceEventsStatus
> = z.nativeEnum(ListSourceEventsStatus);

/** @internal */
export type ListSourceEventsRequest$Outbound = {
  id: string;
  customerId?: string | undefined;
  limit: number;
  offset: number;
  status?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const ListSourceEventsRequest$outboundSchema: z.ZodType<
  ListSourceEventsRequest$Outbound,
  z.ZodTypeDef,
  ListSourceEventsRequest
> = z.object({
  id: z.string(),
  customerId: z.string().optional(),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
  status: ListSourceEventsStatus$outboundSchema.optional(),
  subscriptionId: z.string().optional(),
});

export function listSourceEventsRequestToJSON(
  listSourceEventsRequest: ListSourceEventsRequest,
): string {
  return JSON.stringify(
    ListSourceEventsRequest$outboundSchema.parse(listSourceEventsRequest),
  );
}

/** @internal */
export const ListSourceEventsResponse$inboundSchema: z.ZodType<
  ListSourceEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.SourceEvent$inboundSchema).optional(),
  pagination: models.OffsetPagination$inboundSchema.optional(),
});

export function listSourceEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSourceEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSourceEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSourceEventsResponse' from JSON`,
  );
}
