/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPlansRequest = {
  /**
   * Number of plans to return
   */
  limit?: number | undefined;
  /**
   * Filter plans by merchant organization ID
   */
  merchantId?: string | undefined;
  /**
   * Number of plans to skip
   */
  offset?: number | undefined;
  /**
   * Filter plans by product ID
   */
  productId?: string | undefined;
};

export type ListPlansPagination = {
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

/**
 * List of plans
 */
export type ListPlansResponse = {
  data?: Array<models.Plan> | undefined;
  pagination?: ListPlansPagination | undefined;
};

/** @internal */
export type ListPlansRequest$Outbound = {
  limit: number;
  merchantId?: string | undefined;
  offset: number;
  productId?: string | undefined;
};

/** @internal */
export const ListPlansRequest$outboundSchema: z.ZodType<
  ListPlansRequest$Outbound,
  z.ZodTypeDef,
  ListPlansRequest
> = z.object({
  limit: z.number().int().default(10),
  merchantId: z.string().optional(),
  offset: z.number().int().default(0),
  productId: z.string().optional(),
});

export function listPlansRequestToJSON(
  listPlansRequest: ListPlansRequest,
): string {
  return JSON.stringify(
    ListPlansRequest$outboundSchema.parse(listPlansRequest),
  );
}

/** @internal */
export const ListPlansPagination$inboundSchema: z.ZodType<
  ListPlansPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  total: z.number().int().optional(),
});

export function listPlansPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListPlansPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlansPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlansPagination' from JSON`,
  );
}

/** @internal */
export const ListPlansResponse$inboundSchema: z.ZodType<
  ListPlansResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.Plan$inboundSchema).optional(),
  pagination: z.lazy(() => ListPlansPagination$inboundSchema).optional(),
});

export function listPlansResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPlansResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlansResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlansResponse' from JSON`,
  );
}
