/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListProductsRequest = {
  /**
   * Number of products to return
   */
  limit?: number | undefined;
  /**
   * Filter products by merchant organization ID
   */
  merchantId?: string | undefined;
  /**
   * Number of products to skip
   */
  offset?: number | undefined;
};

/**
 * List of products
 */
export type ListProductsResponse = {
  data?: Array<models.Product> | undefined;
  /**
   * Offset-based pagination response.
   */
  pagination?: models.OffsetPagination | undefined;
};

/** @internal */
export type ListProductsRequest$Outbound = {
  limit: number;
  merchantId?: string | undefined;
  offset: number;
};

/** @internal */
export const ListProductsRequest$outboundSchema: z.ZodType<
  ListProductsRequest$Outbound,
  z.ZodTypeDef,
  ListProductsRequest
> = z.object({
  limit: z.number().int().default(10),
  merchantId: z.string().optional(),
  offset: z.number().int().default(0),
});

export function listProductsRequestToJSON(
  listProductsRequest: ListProductsRequest,
): string {
  return JSON.stringify(
    ListProductsRequest$outboundSchema.parse(listProductsRequest),
  );
}

/** @internal */
export const ListProductsResponse$inboundSchema: z.ZodType<
  ListProductsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.Product$inboundSchema).optional(),
  pagination: models.OffsetPagination$inboundSchema.optional(),
});

export function listProductsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProductsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProductsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProductsResponse' from JSON`,
  );
}
