/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListExternalReferencesRequest = {
  /**
   * Restrict results to a specific merchant. All active filters AND together.
   */
  merchantId?: string | undefined;
  /**
   * Filter by the Paygentic entity type the reference points at (e.g. `item`). All active filters AND together.
   */
  entityType?: models.EntityType | undefined;
  /**
   * Filter by the Paygentic entity id (e.g. `itm_xxx`). This is the inverse of the `GET /v0/items?provider=&externalId=` resolution endpoint — look up references from the Paygentic side. All active filters AND together.
   */
  entityId?: string | undefined;
  /**
   * Filter by provider (e.g. `salesforce`, `netsuite`). All active filters AND together.
   */
  provider?: string | undefined;
  /**
   * Filter by the external system's record id. Pair with `provider` to look up all Paygentic entities that carry a given external reference. All active filters AND together.
   */
  externalId?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * List of external references
 */
export type ListExternalReferencesResponse = {
  data: Array<models.ExternalReference>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListExternalReferencesRequest$Outbound = {
  merchantId?: string | undefined;
  entityType?: string | undefined;
  entityId?: string | undefined;
  provider?: string | undefined;
  externalId?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListExternalReferencesRequest$outboundSchema: z.ZodType<
  ListExternalReferencesRequest$Outbound,
  z.ZodTypeDef,
  ListExternalReferencesRequest
> = z.object({
  merchantId: z.string().optional(),
  entityType: models.EntityType$outboundSchema.optional(),
  entityId: z.string().optional(),
  provider: z.string().optional(),
  externalId: z.string().optional(),
  limit: z.number().int().default(50),
  offset: z.number().int().default(0),
});

export function listExternalReferencesRequestToJSON(
  listExternalReferencesRequest: ListExternalReferencesRequest,
): string {
  return JSON.stringify(
    ListExternalReferencesRequest$outboundSchema.parse(
      listExternalReferencesRequest,
    ),
  );
}

/** @internal */
export const ListExternalReferencesResponse$inboundSchema: z.ZodType<
  ListExternalReferencesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.ExternalReference$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listExternalReferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListExternalReferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListExternalReferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListExternalReferencesResponse' from JSON`,
  );
}
