/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter by payment status.
 */
export const ListPaymentSessionsStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
/**
 * Filter by payment status.
 */
export type ListPaymentSessionsStatus = ClosedEnum<
  typeof ListPaymentSessionsStatus
>;

export type ListPaymentSessionsRequest = {
  /**
   * Merchant organization ID. Required when using an API key that is not scoped to a single merchant.
   */
  merchantId?: string | undefined;
  /**
   * Filter by payment status.
   */
  status?: ListPaymentSessionsStatus | undefined;
  /**
   * Filter by customer ID.
   */
  customerId?: string | undefined;
  /**
   * Number of payments to return.
   */
  limit?: number | undefined;
  /**
   * Number of payments to skip.
   */
  offset?: number | undefined;
};

export const ListPaymentSessionsObject = {
  List: "list",
} as const;
export type ListPaymentSessionsObject = ClosedEnum<
  typeof ListPaymentSessionsObject
>;

/**
 * List of payments
 */
export type ListPaymentSessionsResponse = {
  object: ListPaymentSessionsObject;
  data: Array<models.Payment>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export const ListPaymentSessionsStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListPaymentSessionsStatus
> = z.nativeEnum(ListPaymentSessionsStatus);

/** @internal */
export type ListPaymentSessionsRequest$Outbound = {
  merchantId?: string | undefined;
  status?: string | undefined;
  customerId?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const ListPaymentSessionsRequest$outboundSchema: z.ZodType<
  ListPaymentSessionsRequest$Outbound,
  z.ZodTypeDef,
  ListPaymentSessionsRequest
> = z.object({
  merchantId: z.string().optional(),
  status: ListPaymentSessionsStatus$outboundSchema.optional(),
  customerId: z.string().optional(),
  limit: z.number().int().default(10),
  offset: z.number().int().default(0),
});

export function listPaymentSessionsRequestToJSON(
  listPaymentSessionsRequest: ListPaymentSessionsRequest,
): string {
  return JSON.stringify(
    ListPaymentSessionsRequest$outboundSchema.parse(listPaymentSessionsRequest),
  );
}

/** @internal */
export const ListPaymentSessionsObject$inboundSchema: z.ZodNativeEnum<
  typeof ListPaymentSessionsObject
> = z.nativeEnum(ListPaymentSessionsObject);

/** @internal */
export const ListPaymentSessionsResponse$inboundSchema: z.ZodType<
  ListPaymentSessionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListPaymentSessionsObject$inboundSchema,
  data: z.array(models.Payment$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listPaymentSessionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPaymentSessionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPaymentSessionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPaymentSessionsResponse' from JSON`,
  );
}
