/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListBillingSchedulesRequest = {
  /**
   * Filter by owning order (XOR with subscriptionId)
   */
  orderId?: string | undefined;
  /**
   * Filter by owning subscription (XOR with orderId)
   */
  subscriptionId?: string | undefined;
};

export const ListBillingSchedulesObject = {
  List: "list",
} as const;
export type ListBillingSchedulesObject = ClosedEnum<
  typeof ListBillingSchedulesObject
>;

/**
 * List of billing schedules
 */
export type ListBillingSchedulesResponse = {
  object: ListBillingSchedulesObject;
  data: Array<models.SchemasBillingSchedule>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ListBillingSchedulesRequest$Outbound = {
  orderId?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const ListBillingSchedulesRequest$outboundSchema: z.ZodType<
  ListBillingSchedulesRequest$Outbound,
  z.ZodTypeDef,
  ListBillingSchedulesRequest
> = z.object({
  orderId: z.string().optional(),
  subscriptionId: z.string().optional(),
});

export function listBillingSchedulesRequestToJSON(
  listBillingSchedulesRequest: ListBillingSchedulesRequest,
): string {
  return JSON.stringify(
    ListBillingSchedulesRequest$outboundSchema.parse(
      listBillingSchedulesRequest,
    ),
  );
}

/** @internal */
export const ListBillingSchedulesObject$inboundSchema: z.ZodNativeEnum<
  typeof ListBillingSchedulesObject
> = z.nativeEnum(ListBillingSchedulesObject);

/** @internal */
export const ListBillingSchedulesResponse$inboundSchema: z.ZodType<
  ListBillingSchedulesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListBillingSchedulesObject$inboundSchema,
  data: z.array(models.SchemasBillingSchedule$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function listBillingSchedulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBillingSchedulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBillingSchedulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBillingSchedulesResponse' from JSON`,
  );
}
