/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const ListSubscriptionsStatus = {
  Active: "active",
  Terminated: "terminated",
  PendingPayment: "pending_payment",
} as const;
export type ListSubscriptionsStatus = ClosedEnum<
  typeof ListSubscriptionsStatus
>;

/**
 * Include related resources. When 'customer' is specified, each subscription includes merchant and consumer details.
 */
export const Include = {
  Customer: "customer",
} as const;
/**
 * Include related resources. When 'customer' is specified, each subscription includes merchant and consumer details.
 */
export type Include = ClosedEnum<typeof Include>;

export type ListSubscriptionsRequest = {
  consumerId?: string | undefined;
  customerId?: string | undefined;
  /**
   * Number of subscriptions to return
   */
  limit?: string | undefined;
  merchantId?: string | undefined;
  /**
   * Number of subscriptions to skip
   */
  offset?: string | undefined;
  status?: ListSubscriptionsStatus | undefined;
  /**
   * Filter subscriptions started at or before this ISO 8601 date-time
   */
  startedBefore?: Date | undefined;
  /**
   * Include related resources. When 'customer' is specified, each subscription includes merchant and consumer details.
   */
  include?: Include | undefined;
};

/**
 * List of subscriptions
 */
export type ListSubscriptionsResponse = {
  data?: Array<models.Subscription> | undefined;
  /**
   * Offset-based pagination response.
   */
  pagination?: models.OffsetPagination | undefined;
};

/** @internal */
export const ListSubscriptionsStatus$outboundSchema: z.ZodNativeEnum<
  typeof ListSubscriptionsStatus
> = z.nativeEnum(ListSubscriptionsStatus);

/** @internal */
export const Include$outboundSchema: z.ZodNativeEnum<typeof Include> = z
  .nativeEnum(Include);

/** @internal */
export type ListSubscriptionsRequest$Outbound = {
  consumerId?: string | undefined;
  customerId?: string | undefined;
  limit: string;
  merchantId?: string | undefined;
  offset: string;
  status?: string | undefined;
  startedBefore?: string | undefined;
  include?: string | undefined;
};

/** @internal */
export const ListSubscriptionsRequest$outboundSchema: z.ZodType<
  ListSubscriptionsRequest$Outbound,
  z.ZodTypeDef,
  ListSubscriptionsRequest
> = z.object({
  consumerId: z.string().optional(),
  customerId: z.string().optional(),
  limit: z.string().default("10"),
  merchantId: z.string().optional(),
  offset: z.string().default("0"),
  status: ListSubscriptionsStatus$outboundSchema.optional(),
  startedBefore: z.date().transform(v => v.toISOString()).optional(),
  include: Include$outboundSchema.optional(),
});

export function listSubscriptionsRequestToJSON(
  listSubscriptionsRequest: ListSubscriptionsRequest,
): string {
  return JSON.stringify(
    ListSubscriptionsRequest$outboundSchema.parse(listSubscriptionsRequest),
  );
}

/** @internal */
export const ListSubscriptionsResponse$inboundSchema: z.ZodType<
  ListSubscriptionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.Subscription$inboundSchema).optional(),
  pagination: models.OffsetPagination$inboundSchema.optional(),
});

export function listSubscriptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSubscriptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSubscriptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSubscriptionsResponse' from JSON`,
  );
}
