/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListBillableMetricsRequest = {
  /**
   * Number of billable metrics to return.
   */
  limit?: number | undefined;
  /**
   * Filter billable metrics by merchant organization ID.
   */
  merchantId: string;
  /**
   * Number of billable metrics to skip.
   */
  offset?: number | undefined;
  /**
   * Filter billable metrics by product ID.
   */
  productId?: string | undefined;
};

export const ListBillableMetricsObject = {
  List: "list",
} as const;
export type ListBillableMetricsObject = ClosedEnum<
  typeof ListBillableMetricsObject
>;

export type ListBillableMetricsPagination = {
  limit: number;
  offset: number;
  total: number;
};

/**
 * List of billable metrics
 */
export type ListBillableMetricsResponse = {
  object: ListBillableMetricsObject;
  data: Array<models.BillableMetric>;
  pagination: ListBillableMetricsPagination;
};

/** @internal */
export type ListBillableMetricsRequest$Outbound = {
  limit: number;
  merchantId: string;
  offset: number;
  productId?: string | undefined;
};

/** @internal */
export const ListBillableMetricsRequest$outboundSchema: z.ZodType<
  ListBillableMetricsRequest$Outbound,
  z.ZodTypeDef,
  ListBillableMetricsRequest
> = z.object({
  limit: z.number().int().default(10),
  merchantId: z.string(),
  offset: z.number().int().default(0),
  productId: z.string().optional(),
});

export function listBillableMetricsRequestToJSON(
  listBillableMetricsRequest: ListBillableMetricsRequest,
): string {
  return JSON.stringify(
    ListBillableMetricsRequest$outboundSchema.parse(listBillableMetricsRequest),
  );
}

/** @internal */
export const ListBillableMetricsObject$inboundSchema: z.ZodNativeEnum<
  typeof ListBillableMetricsObject
> = z.nativeEnum(ListBillableMetricsObject);

/** @internal */
export const ListBillableMetricsPagination$inboundSchema: z.ZodType<
  ListBillableMetricsPagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  total: z.number().int(),
});

export function listBillableMetricsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ListBillableMetricsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBillableMetricsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBillableMetricsPagination' from JSON`,
  );
}

/** @internal */
export const ListBillableMetricsResponse$inboundSchema: z.ZodType<
  ListBillableMetricsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListBillableMetricsObject$inboundSchema,
  data: z.array(models.BillableMetric$inboundSchema),
  pagination: z.lazy(() => ListBillableMetricsPagination$inboundSchema),
});

export function listBillableMetricsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBillableMetricsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBillableMetricsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBillableMetricsResponse' from JSON`,
  );
}
