/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type MintPlanVersionRequest = {
  id: string;
  mintPlanVersionRequest: models.MintPlanVersionRequest;
};

/** @internal */
export type MintPlanVersionRequest$Outbound = {
  id: string;
  MintPlanVersionRequest: models.MintPlanVersionRequest$Outbound;
};

/** @internal */
export const MintPlanVersionRequest$outboundSchema: z.ZodType<
  MintPlanVersionRequest$Outbound,
  z.ZodTypeDef,
  MintPlanVersionRequest
> = z.object({
  id: z.string(),
  mintPlanVersionRequest: models.MintPlanVersionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    mintPlanVersionRequest: "MintPlanVersionRequest",
  });
});

export function mintPlanVersionRequestToJSON(
  mintPlanVersionRequest: MintPlanVersionRequest,
): string {
  return JSON.stringify(
    MintPlanVersionRequest$outboundSchema.parse(mintPlanVersionRequest),
  );
}
