/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type RejectSourceEventRequest = {
  id: string;
  eventId: string;
};

/** @internal */
export type RejectSourceEventRequest$Outbound = {
  id: string;
  eventId: string;
};

/** @internal */
export const RejectSourceEventRequest$outboundSchema: z.ZodType<
  RejectSourceEventRequest$Outbound,
  z.ZodTypeDef,
  RejectSourceEventRequest
> = z.object({
  id: z.string(),
  eventId: z.string(),
});

export function rejectSourceEventRequestToJSON(
  rejectSourceEventRequest: RejectSourceEventRequest,
): string {
  return JSON.stringify(
    RejectSourceEventRequest$outboundSchema.parse(rejectSourceEventRequest),
  );
}
