/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ReplaceScheduleIntervalsRequest = {
  id: string;
  replaceScheduleIntervalsRequest: models.ReplaceScheduleIntervalsRequest;
};

export const ReplaceScheduleIntervalsObject = {
  List: "list",
} as const;
export type ReplaceScheduleIntervalsObject = ClosedEnum<
  typeof ReplaceScheduleIntervalsObject
>;

/**
 * Intervals replaced
 */
export type ReplaceScheduleIntervalsResponse = {
  object: ReplaceScheduleIntervalsObject;
  data: Array<models.ScheduleInterval>;
  /**
   * Offset-based pagination response.
   */
  pagination: models.OffsetPagination;
};

/** @internal */
export type ReplaceScheduleIntervalsRequest$Outbound = {
  id: string;
  ReplaceScheduleIntervalsRequest:
    models.ReplaceScheduleIntervalsRequest$Outbound;
};

/** @internal */
export const ReplaceScheduleIntervalsRequest$outboundSchema: z.ZodType<
  ReplaceScheduleIntervalsRequest$Outbound,
  z.ZodTypeDef,
  ReplaceScheduleIntervalsRequest
> = z.object({
  id: z.string(),
  replaceScheduleIntervalsRequest:
    models.ReplaceScheduleIntervalsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    replaceScheduleIntervalsRequest: "ReplaceScheduleIntervalsRequest",
  });
});

export function replaceScheduleIntervalsRequestToJSON(
  replaceScheduleIntervalsRequest: ReplaceScheduleIntervalsRequest,
): string {
  return JSON.stringify(
    ReplaceScheduleIntervalsRequest$outboundSchema.parse(
      replaceScheduleIntervalsRequest,
    ),
  );
}

/** @internal */
export const ReplaceScheduleIntervalsObject$inboundSchema: z.ZodNativeEnum<
  typeof ReplaceScheduleIntervalsObject
> = z.nativeEnum(ReplaceScheduleIntervalsObject);

/** @internal */
export const ReplaceScheduleIntervalsResponse$inboundSchema: z.ZodType<
  ReplaceScheduleIntervalsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ReplaceScheduleIntervalsObject$inboundSchema,
  data: z.array(models.ScheduleInterval$inboundSchema),
  pagination: models.OffsetPagination$inboundSchema,
});

export function replaceScheduleIntervalsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReplaceScheduleIntervalsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplaceScheduleIntervalsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplaceScheduleIntervalsResponse' from JSON`,
  );
}
