/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type TerminateSubscriptionRequestBody = {
  /**
   * Cancellation explanation text. Sample values: 'Customer requested cancellation', 'Payment failure', 'Service migration', 'Contract expiration'
   */
  reason: string;
  /**
   * Why a change was made. `correction` fixes data to match what was agreed; `migration` moves a contract from another system; `commercial` is a real change to the deal. Defaults to `unspecified`.
   */
  changeReason?: models.ChangeReason | undefined;
};

export type TerminateSubscriptionRequest = {
  /**
   * The subscription ID
   */
  id: string;
  requestBody: TerminateSubscriptionRequestBody;
};

/** @internal */
export type TerminateSubscriptionRequestBody$Outbound = {
  reason: string;
  changeReason?: string | undefined;
};

/** @internal */
export const TerminateSubscriptionRequestBody$outboundSchema: z.ZodType<
  TerminateSubscriptionRequestBody$Outbound,
  z.ZodTypeDef,
  TerminateSubscriptionRequestBody
> = z.object({
  reason: z.string(),
  changeReason: models.ChangeReason$outboundSchema.optional(),
});

export function terminateSubscriptionRequestBodyToJSON(
  terminateSubscriptionRequestBody: TerminateSubscriptionRequestBody,
): string {
  return JSON.stringify(
    TerminateSubscriptionRequestBody$outboundSchema.parse(
      terminateSubscriptionRequestBody,
    ),
  );
}

/** @internal */
export type TerminateSubscriptionRequest$Outbound = {
  id: string;
  RequestBody: TerminateSubscriptionRequestBody$Outbound;
};

/** @internal */
export const TerminateSubscriptionRequest$outboundSchema: z.ZodType<
  TerminateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  TerminateSubscriptionRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => TerminateSubscriptionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function terminateSubscriptionRequestToJSON(
  terminateSubscriptionRequest: TerminateSubscriptionRequest,
): string {
  return JSON.stringify(
    TerminateSubscriptionRequest$outboundSchema.parse(
      terminateSubscriptionRequest,
    ),
  );
}
