/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateBillingScheduleRequest = {
  id: string;
  updateBillingScheduleRequest: models.UpdateBillingScheduleRequest;
};

/** @internal */
export type UpdateBillingScheduleRequest$Outbound = {
  id: string;
  UpdateBillingScheduleRequest: models.UpdateBillingScheduleRequest$Outbound;
};

/** @internal */
export const UpdateBillingScheduleRequest$outboundSchema: z.ZodType<
  UpdateBillingScheduleRequest$Outbound,
  z.ZodTypeDef,
  UpdateBillingScheduleRequest
> = z.object({
  id: z.string(),
  updateBillingScheduleRequest:
    models.UpdateBillingScheduleRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateBillingScheduleRequest: "UpdateBillingScheduleRequest",
  });
});

export function updateBillingScheduleRequestToJSON(
  updateBillingScheduleRequest: UpdateBillingScheduleRequest,
): string {
  return JSON.stringify(
    UpdateBillingScheduleRequest$outboundSchema.parse(
      updateBillingScheduleRequest,
    ),
  );
}
