/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateApprovalRequest = {
  id: string;
  updateApprovalRequest: models.UpdateApprovalRequest;
};

/** @internal */
export type UpdateApprovalRequest$Outbound = {
  id: string;
  UpdateApprovalRequest: models.UpdateApprovalRequest$Outbound;
};

/** @internal */
export const UpdateApprovalRequest$outboundSchema: z.ZodType<
  UpdateApprovalRequest$Outbound,
  z.ZodTypeDef,
  UpdateApprovalRequest
> = z.object({
  id: z.string(),
  updateApprovalRequest: models.UpdateApprovalRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateApprovalRequest: "UpdateApprovalRequest",
  });
});

export function updateApprovalRequestToJSON(
  updateApprovalRequest: UpdateApprovalRequest,
): string {
  return JSON.stringify(
    UpdateApprovalRequest$outboundSchema.parse(updateApprovalRequest),
  );
}
