/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateBillableMetricRequestBody = {
  /**
   * Revised explanation of what the metric represents. Sample values: 'Language model token consumption', 'Database storage capacity used', 'Machine learning prediction API calls', 'AI-generated content items'
   */
  description?: string | undefined;
  /**
   * Updated label for the metric. Sample values: 'LLM Tokens', 'Database Storage', 'Prediction Requests', 'Content Generations'
   */
  name?: string | undefined;
  /**
   * Updated measurement unit. Common examples: 'tokens', 'GB', 'requests', 'items', 'hours'
   */
  unit?: string | undefined;
  /**
   * CloudEvents type for meter routing.
   */
  eventType?: string | null | undefined;
  /**
   * JSONPath to extract numeric value from event data.
   */
  valueProperty?: string | null | undefined;
  /**
   * Map of dimension name to JSONPath for group-by queries.
   */
  groupBy?: { [k: string]: string } | null | undefined;
  /**
   * Only count events after this timestamp.
   */
  eventFrom?: Date | null | undefined;
};

export type UpdateBillableMetricRequest = {
  id: string;
  requestBody: UpdateBillableMetricRequestBody;
};

/** @internal */
export type UpdateBillableMetricRequestBody$Outbound = {
  description?: string | undefined;
  name?: string | undefined;
  unit?: string | undefined;
  eventType?: string | null | undefined;
  valueProperty?: string | null | undefined;
  groupBy?: { [k: string]: string } | null | undefined;
  eventFrom?: string | null | undefined;
};

/** @internal */
export const UpdateBillableMetricRequestBody$outboundSchema: z.ZodType<
  UpdateBillableMetricRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateBillableMetricRequestBody
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  unit: z.string().optional(),
  eventType: z.nullable(z.string()).optional(),
  valueProperty: z.nullable(z.string()).optional(),
  groupBy: z.nullable(z.record(z.string())).optional(),
  eventFrom: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});

export function updateBillableMetricRequestBodyToJSON(
  updateBillableMetricRequestBody: UpdateBillableMetricRequestBody,
): string {
  return JSON.stringify(
    UpdateBillableMetricRequestBody$outboundSchema.parse(
      updateBillableMetricRequestBody,
    ),
  );
}

/** @internal */
export type UpdateBillableMetricRequest$Outbound = {
  id: string;
  RequestBody: UpdateBillableMetricRequestBody$Outbound;
};

/** @internal */
export const UpdateBillableMetricRequest$outboundSchema: z.ZodType<
  UpdateBillableMetricRequest$Outbound,
  z.ZodTypeDef,
  UpdateBillableMetricRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateBillableMetricRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateBillableMetricRequestToJSON(
  updateBillableMetricRequest: UpdateBillableMetricRequest,
): string {
  return JSON.stringify(
    UpdateBillableMetricRequest$outboundSchema.parse(
      updateBillableMetricRequest,
    ),
  );
}
