/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateItemRequestBody = {
  name?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export type UpdateItemRequest = {
  /**
   * The unique identifier of the item
   */
  id: string;
  requestBody: UpdateItemRequestBody;
};

/** @internal */
export type UpdateItemRequestBody$Outbound = {
  name?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const UpdateItemRequestBody$outboundSchema: z.ZodType<
  UpdateItemRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateItemRequestBody
> = z.object({
  name: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

export function updateItemRequestBodyToJSON(
  updateItemRequestBody: UpdateItemRequestBody,
): string {
  return JSON.stringify(
    UpdateItemRequestBody$outboundSchema.parse(updateItemRequestBody),
  );
}

/** @internal */
export type UpdateItemRequest$Outbound = {
  id: string;
  RequestBody: UpdateItemRequestBody$Outbound;
};

/** @internal */
export const UpdateItemRequest$outboundSchema: z.ZodType<
  UpdateItemRequest$Outbound,
  z.ZodTypeDef,
  UpdateItemRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateItemRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateItemRequestToJSON(
  updateItemRequest: UpdateItemRequest,
): string {
  return JSON.stringify(
    UpdateItemRequest$outboundSchema.parse(updateItemRequest),
  );
}
