/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Updated feature type
 */
export const UpdateFeatureType = {
  Metered: "metered",
  Static: "static",
  Boolean: "boolean",
} as const;
/**
 * Updated feature type
 */
export type UpdateFeatureType = ClosedEnum<typeof UpdateFeatureType>;

export type UpdateFeatureRequestBody = {
  /**
   * Updated feature key slug. Sample values: 'increased-api-limit', 'new-storage-tier'
   */
  key?: string | undefined;
  /**
   * Updated feature name.
   */
  name?: string | undefined;
  /**
   * Updated feature type
   */
  type?: UpdateFeatureType | undefined;
  /**
   * Updated metadata for the feature
   */
  metadata?: { [k: string]: string } | undefined;
};

export type UpdateFeatureRequest = {
  /**
   * The unique identifier of the feature
   */
  id: string;
  requestBody: UpdateFeatureRequestBody;
};

/** @internal */
export const UpdateFeatureType$outboundSchema: z.ZodNativeEnum<
  typeof UpdateFeatureType
> = z.nativeEnum(UpdateFeatureType);

/** @internal */
export type UpdateFeatureRequestBody$Outbound = {
  key?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const UpdateFeatureRequestBody$outboundSchema: z.ZodType<
  UpdateFeatureRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateFeatureRequestBody
> = z.object({
  key: z.string().optional(),
  name: z.string().optional(),
  type: UpdateFeatureType$outboundSchema.optional(),
  metadata: z.record(z.string()).optional(),
});

export function updateFeatureRequestBodyToJSON(
  updateFeatureRequestBody: UpdateFeatureRequestBody,
): string {
  return JSON.stringify(
    UpdateFeatureRequestBody$outboundSchema.parse(updateFeatureRequestBody),
  );
}

/** @internal */
export type UpdateFeatureRequest$Outbound = {
  id: string;
  RequestBody: UpdateFeatureRequestBody$Outbound;
};

/** @internal */
export const UpdateFeatureRequest$outboundSchema: z.ZodType<
  UpdateFeatureRequest$Outbound,
  z.ZodTypeDef,
  UpdateFeatureRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateFeatureRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateFeatureRequestToJSON(
  updateFeatureRequest: UpdateFeatureRequest,
): string {
  return JSON.stringify(
    UpdateFeatureRequest$outboundSchema.parse(updateFeatureRequest),
  );
}
