/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type TaxRates = number | { [k: string]: number };

export type UpdateCustomerRequestBody = {
  /**
   * Business tax registration identifier. Sample values: 'GB123456789' for UK VAT, 'DE123456789' for German VAT, 'FR12345678901' for French VAT. Enables inter-company tax handling and exemption from standard tax collection. Assign null to delete the identifier.
   */
  taxId?: string | null | undefined;
  taxRates?: number | { [k: string]: number } | undefined;
};

export type UpdateCustomerRequest = {
  /**
   * The unique identifier of the customer.
   */
  id: string;
  requestBody: UpdateCustomerRequestBody;
};

/** @internal */
export type TaxRates$Outbound = number | { [k: string]: number };

/** @internal */
export const TaxRates$outboundSchema: z.ZodType<
  TaxRates$Outbound,
  z.ZodTypeDef,
  TaxRates
> = z.union([z.number(), z.record(z.number())]);

export function taxRatesToJSON(taxRates: TaxRates): string {
  return JSON.stringify(TaxRates$outboundSchema.parse(taxRates));
}

/** @internal */
export type UpdateCustomerRequestBody$Outbound = {
  taxId?: string | null | undefined;
  taxRates?: number | { [k: string]: number } | undefined;
};

/** @internal */
export const UpdateCustomerRequestBody$outboundSchema: z.ZodType<
  UpdateCustomerRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateCustomerRequestBody
> = z.object({
  taxId: z.nullable(z.string()).optional(),
  taxRates: z.union([z.number(), z.record(z.number())]).optional(),
});

export function updateCustomerRequestBodyToJSON(
  updateCustomerRequestBody: UpdateCustomerRequestBody,
): string {
  return JSON.stringify(
    UpdateCustomerRequestBody$outboundSchema.parse(updateCustomerRequestBody),
  );
}

/** @internal */
export type UpdateCustomerRequest$Outbound = {
  id: string;
  RequestBody: UpdateCustomerRequestBody$Outbound;
};

/** @internal */
export const UpdateCustomerRequest$outboundSchema: z.ZodType<
  UpdateCustomerRequest$Outbound,
  z.ZodTypeDef,
  UpdateCustomerRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateCustomerRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateCustomerRequestToJSON(
  updateCustomerRequest: UpdateCustomerRequest,
): string {
  return JSON.stringify(
    UpdateCustomerRequest$outboundSchema.parse(updateCustomerRequest),
  );
}
