/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { RFCDate } from "../../types/rfcdate.js";
import * as models from "../index.js";

/**
 * Type of entity the user represents.
 */
export const UpdateUserType = {
  Company: "COMPANY",
  Individual: "INDIVIDUAL",
} as const;
/**
 * Type of entity the user represents.
 */
export type UpdateUserType = ClosedEnum<typeof UpdateUserType>;

export type UpdateUserRequestBody = {
  address?: models.Address | undefined;
  /**
   * The date of birth of the user.
   */
  dateOfBirth?: RFCDate | undefined;
  /**
   * The first name of the user.
   */
  firstName?: string | undefined;
  /**
   * The last name of the user.
   */
  lastName?: string | undefined;
  /**
   * The phone number of the user.
   */
  phone?: string | undefined;
  /**
   * Type of entity the user represents.
   */
  type?: UpdateUserType | undefined;
};

export type UpdateUserRequest = {
  id: string;
  requestBody: UpdateUserRequestBody;
};

/** @internal */
export const UpdateUserType$outboundSchema: z.ZodNativeEnum<
  typeof UpdateUserType
> = z.nativeEnum(UpdateUserType);

/** @internal */
export type UpdateUserRequestBody$Outbound = {
  address?: models.Address$Outbound | undefined;
  dateOfBirth?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phone?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const UpdateUserRequestBody$outboundSchema: z.ZodType<
  UpdateUserRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateUserRequestBody
> = z.object({
  address: models.Address$outboundSchema.optional(),
  dateOfBirth: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  phone: z.string().optional(),
  type: UpdateUserType$outboundSchema.optional(),
});

export function updateUserRequestBodyToJSON(
  updateUserRequestBody: UpdateUserRequestBody,
): string {
  return JSON.stringify(
    UpdateUserRequestBody$outboundSchema.parse(updateUserRequestBody),
  );
}

/** @internal */
export type UpdateUserRequest$Outbound = {
  id: string;
  RequestBody: UpdateUserRequestBody$Outbound;
};

/** @internal */
export const UpdateUserRequest$outboundSchema: z.ZodType<
  UpdateUserRequest$Outbound,
  z.ZodTypeDef,
  UpdateUserRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateUserRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateUserRequestToJSON(
  updateUserRequest: UpdateUserRequest,
): string {
  return JSON.stringify(
    UpdateUserRequest$outboundSchema.parse(updateUserRequest),
  );
}
