/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type VoidInvoiceRefundRequestBody = {
  /**
   * Optional reason for voiding the refund (recorded on the credit note)
   */
  reason?: string | undefined;
};

export type VoidInvoiceRefundRequest = {
  /**
   * The invoice ID
   */
  id: string;
  /**
   * The refund (credit note) ID
   */
  refundId: string;
  requestBody?: VoidInvoiceRefundRequestBody | undefined;
};

/** @internal */
export type VoidInvoiceRefundRequestBody$Outbound = {
  reason?: string | undefined;
};

/** @internal */
export const VoidInvoiceRefundRequestBody$outboundSchema: z.ZodType<
  VoidInvoiceRefundRequestBody$Outbound,
  z.ZodTypeDef,
  VoidInvoiceRefundRequestBody
> = z.object({
  reason: z.string().optional(),
});

export function voidInvoiceRefundRequestBodyToJSON(
  voidInvoiceRefundRequestBody: VoidInvoiceRefundRequestBody,
): string {
  return JSON.stringify(
    VoidInvoiceRefundRequestBody$outboundSchema.parse(
      voidInvoiceRefundRequestBody,
    ),
  );
}

/** @internal */
export type VoidInvoiceRefundRequest$Outbound = {
  id: string;
  refundId: string;
  RequestBody?: VoidInvoiceRefundRequestBody$Outbound | undefined;
};

/** @internal */
export const VoidInvoiceRefundRequest$outboundSchema: z.ZodType<
  VoidInvoiceRefundRequest$Outbound,
  z.ZodTypeDef,
  VoidInvoiceRefundRequest
> = z.object({
  id: z.string(),
  refundId: z.string(),
  requestBody: z.lazy(() => VoidInvoiceRefundRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function voidInvoiceRefundRequestToJSON(
  voidInvoiceRefundRequest: VoidInvoiceRefundRequest,
): string {
  return JSON.stringify(
    VoidInvoiceRefundRequest$outboundSchema.parse(voidInvoiceRefundRequest),
  );
}
