/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ActiveEntitlementObject = {
  Entitlement: "entitlement",
} as const;
export type ActiveEntitlementObject = ClosedEnum<
  typeof ActiveEntitlementObject
>;

export type ActiveEntitlement = {
  /**
   * Unique identifier for an entitlement
   */
  id?: string | undefined;
  object: ActiveEntitlementObject;
  /**
   * List of billable metrics that this entitlement covers.
   */
  billableMetrics?: Array<string> | undefined;
  /**
   * Unique identifier for a customer
   */
  customerId?: string | undefined;
  /**
   * Unique identifier for a plan
   */
  planId?: string | undefined;
  /**
   * Unique identifier for a product
   */
  productId?: string | undefined;
  /**
   * Unique identifier for a subscription
   */
  subscriptionId?: string | undefined;
  /**
   * Timestamp when the entitlement was checked.
   */
  verifiedAt?: Date | undefined;
};

/** @internal */
export const ActiveEntitlementObject$inboundSchema: z.ZodNativeEnum<
  typeof ActiveEntitlementObject
> = z.nativeEnum(ActiveEntitlementObject);

/** @internal */
export const ActiveEntitlement$inboundSchema: z.ZodType<
  ActiveEntitlement,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  object: ActiveEntitlementObject$inboundSchema.default("entitlement"),
  billableMetrics: z.array(z.string()).optional(),
  customerId: z.string().optional(),
  planId: z.string().optional(),
  productId: z.string().optional(),
  subscriptionId: z.string().optional(),
  verifiedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

export function activeEntitlementFromJSON(
  jsonString: string,
): SafeParseResult<ActiveEntitlement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveEntitlement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveEntitlement' from JSON`,
  );
}
