/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ApprovalObject = {
  Approval: "approval",
} as const;
export type ApprovalObject = ClosedEnum<typeof ApprovalObject>;

export const ApprovalResourceType = {
  Order: "order",
  Invoice: "invoice",
} as const;
export type ApprovalResourceType = ClosedEnum<typeof ApprovalResourceType>;

export const ApprovalKind = {
  DataReview: "data_review",
  FinancialReview: "financial_review",
  Push: "push",
} as const;
export type ApprovalKind = ClosedEnum<typeof ApprovalKind>;

export const ApprovalDecision = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
  Cancelled: "cancelled",
} as const;
export type ApprovalDecision = ClosedEnum<typeof ApprovalDecision>;

export type Approval = {
  id: string;
  object: ApprovalObject;
  merchantId: string;
  resourceType: ApprovalResourceType;
  resourceId: string;
  kind: ApprovalKind;
  decision: ApprovalDecision;
  requester: string;
  reviewer?: string | null | undefined;
  note?: string | null | undefined;
  dataSnapshotHash: string;
  decidedAt?: Date | null | undefined;
  createdAt: Date;
};

/** @internal */
export const ApprovalObject$inboundSchema: z.ZodNativeEnum<
  typeof ApprovalObject
> = z.nativeEnum(ApprovalObject);

/** @internal */
export const ApprovalResourceType$inboundSchema: z.ZodNativeEnum<
  typeof ApprovalResourceType
> = z.nativeEnum(ApprovalResourceType);

/** @internal */
export const ApprovalKind$inboundSchema: z.ZodNativeEnum<typeof ApprovalKind> =
  z.nativeEnum(ApprovalKind);

/** @internal */
export const ApprovalDecision$inboundSchema: z.ZodNativeEnum<
  typeof ApprovalDecision
> = z.nativeEnum(ApprovalDecision);

/** @internal */
export const Approval$inboundSchema: z.ZodType<
  Approval,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: ApprovalObject$inboundSchema,
  merchantId: z.string(),
  resourceType: ApprovalResourceType$inboundSchema,
  resourceId: z.string(),
  kind: ApprovalKind$inboundSchema,
  decision: ApprovalDecision$inboundSchema,
  requester: z.string(),
  reviewer: z.nullable(z.string()).optional(),
  note: z.nullable(z.string()).optional(),
  dataSnapshotHash: z.string(),
  decidedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function approvalFromJSON(
  jsonString: string,
): SafeParseResult<Approval, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Approval$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Approval' from JSON`,
  );
}
