/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { UsageEvent, UsageEvent$inboundSchema } from "./usageevent.js";

export const BatchUsageEventResponseObject = {
  BatchUsageEvents: "batchUsageEvents",
} as const;
export type BatchUsageEventResponseObject = ClosedEnum<
  typeof BatchUsageEventResponseObject
>;

export type Failed = {
  /**
   * Error message describing why the event failed
   */
  error: string;
  /**
   * Idempotency key of the failed event for identification
   */
  idempotencyKey: string;
  /**
   * Index of the failed event in the original request array
   */
  index: number;
};

/**
 * Summary of batch processing results
 */
export type Summary = {
  /**
   * Number of events that failed to be created
   */
  failed: number;
  /**
   * Number of successfully created events
   */
  successful: number;
  /**
   * Total number of events in the batch
   */
  total: number;
};

export type BatchUsageEventResponse = {
  object: BatchUsageEventResponseObject;
  /**
   * Array of events that failed to be created with error details
   */
  failed: Array<Failed>;
  /**
   * Array of successfully created usage events
   */
  successful: Array<UsageEvent>;
  /**
   * Summary of batch processing results
   */
  summary: Summary;
};

/** @internal */
export const BatchUsageEventResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof BatchUsageEventResponseObject
> = z.nativeEnum(BatchUsageEventResponseObject);

/** @internal */
export const Failed$inboundSchema: z.ZodType<Failed, z.ZodTypeDef, unknown> = z
  .object({
    error: z.string(),
    idempotencyKey: z.string(),
    index: z.number().int(),
  });

export function failedFromJSON(
  jsonString: string,
): SafeParseResult<Failed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Failed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Failed' from JSON`,
  );
}

/** @internal */
export const Summary$inboundSchema: z.ZodType<Summary, z.ZodTypeDef, unknown> =
  z.object({
    failed: z.number().int(),
    successful: z.number().int(),
    total: z.number().int(),
  });

export function summaryFromJSON(
  jsonString: string,
): SafeParseResult<Summary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Summary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Summary' from JSON`,
  );
}

/** @internal */
export const BatchUsageEventResponse$inboundSchema: z.ZodType<
  BatchUsageEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: BatchUsageEventResponseObject$inboundSchema,
  failed: z.array(z.lazy(() => Failed$inboundSchema)),
  successful: z.array(UsageEvent$inboundSchema),
  summary: z.lazy(() => Summary$inboundSchema),
});

export function batchUsageEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<BatchUsageEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BatchUsageEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BatchUsageEventResponse' from JSON`,
  );
}
