/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const BillingScheduleObject = {
  BillingSchedule: "billing_schedule",
} as const;
export type BillingScheduleObject = ClosedEnum<typeof BillingScheduleObject>;

export const BillingScheduleStatus = {
  Draft: "draft",
  Active: "active",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type BillingScheduleStatus = ClosedEnum<typeof BillingScheduleStatus>;

export const BillingScheduleAlignmentPolicy = {
  Anchor: "anchor",
  Calendar: "calendar",
  Coterm: "coterm",
} as const;
export type BillingScheduleAlignmentPolicy = ClosedEnum<
  typeof BillingScheduleAlignmentPolicy
>;

export const BillingScheduleProrationPolicy = {
  None: "none",
  Daily: "daily",
} as const;
export type BillingScheduleProrationPolicy = ClosedEnum<
  typeof BillingScheduleProrationPolicy
>;

export const BillingSchedulePeriodPreset = {
  Single: "single",
  P1M: "P1M",
  P3M: "P3M",
  P6M: "P6M",
  P1Y: "P1Y",
  Custom: "custom",
} as const;
export type BillingSchedulePeriodPreset = ClosedEnum<
  typeof BillingSchedulePeriodPreset
>;

export type BillingSchedule = {
  id: string;
  object: BillingScheduleObject;
  orderId?: string | null | undefined;
  subscriptionId?: string | null | undefined;
  merchantId: string;
  status: BillingScheduleStatus;
  startDate: Date;
  /**
   * The schedule's end date. Always present.
   */
  endDate: Date | null;
  billingAnchor: Date;
  alignmentPolicy: BillingScheduleAlignmentPolicy;
  prorationPolicy: BillingScheduleProrationPolicy;
  paymentTermDays?: number | null | undefined;
  periodPreset: BillingSchedulePeriodPreset;
  customPeriodWindows: Array<any>;
  metadata: { [k: string]: any };
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null | undefined;
};

/** @internal */
export const BillingScheduleObject$inboundSchema: z.ZodNativeEnum<
  typeof BillingScheduleObject
> = z.nativeEnum(BillingScheduleObject);

/** @internal */
export const BillingScheduleStatus$inboundSchema: z.ZodNativeEnum<
  typeof BillingScheduleStatus
> = z.nativeEnum(BillingScheduleStatus);

/** @internal */
export const BillingScheduleAlignmentPolicy$inboundSchema: z.ZodNativeEnum<
  typeof BillingScheduleAlignmentPolicy
> = z.nativeEnum(BillingScheduleAlignmentPolicy);

/** @internal */
export const BillingScheduleProrationPolicy$inboundSchema: z.ZodNativeEnum<
  typeof BillingScheduleProrationPolicy
> = z.nativeEnum(BillingScheduleProrationPolicy);

/** @internal */
export const BillingSchedulePeriodPreset$inboundSchema: z.ZodNativeEnum<
  typeof BillingSchedulePeriodPreset
> = z.nativeEnum(BillingSchedulePeriodPreset);

/** @internal */
export const BillingSchedule$inboundSchema: z.ZodType<
  BillingSchedule,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: BillingScheduleObject$inboundSchema,
  orderId: z.nullable(z.string()).optional(),
  subscriptionId: z.nullable(z.string()).optional(),
  merchantId: z.string(),
  status: BillingScheduleStatus$inboundSchema,
  startDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  endDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  billingAnchor: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  alignmentPolicy: BillingScheduleAlignmentPolicy$inboundSchema,
  prorationPolicy: BillingScheduleProrationPolicy$inboundSchema,
  paymentTermDays: z.nullable(z.number().int()).optional(),
  periodPreset: BillingSchedulePeriodPreset$inboundSchema,
  customPeriodWindows: z.array(z.any()),
  metadata: z.record(z.any()),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function billingScheduleFromJSON(
  jsonString: string,
): SafeParseResult<BillingSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingSchedule' from JSON`,
  );
}
