/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CostObject = {
  Cost: "cost",
} as const;
export type CostObject = ClosedEnum<typeof CostObject>;

export const CostType = {
  Metered: "metered",
} as const;
export type CostType = ClosedEnum<typeof CostType>;

export const CostAggregation = {
  Sum: "SUM",
  Count: "COUNT",
  Avg: "AVG",
  Min: "MIN",
  Max: "MAX",
  UniqueCount: "UNIQUE_COUNT",
  Latest: "LATEST",
} as const;
export type CostAggregation = ClosedEnum<typeof CostAggregation>;

export type Cost = {
  /**
   * Unique identifier for a cost
   */
  id: string;
  object: CostObject;
  type: CostType;
  name: string;
  currency: string;
  /**
   * Decimal as string to avoid floating point precision loss.
   */
  unitCost: string;
  unit?: string | null | undefined;
  aggregation?: CostAggregation | null | undefined;
  eventType?: string | null | undefined;
  valueProperty?: string | null | undefined;
  groupBy?: { [k: string]: string } | null | undefined;
  /**
   * Unique identifier for a product
   */
  productId: string;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  createdAt: Date;
  updatedAt: Date;
  /**
   * Soft-delete timestamp. Always null for active costs returned by the API.
   */
  deletedAt?: Date | null | undefined;
};

/** @internal */
export const CostObject$inboundSchema: z.ZodNativeEnum<typeof CostObject> = z
  .nativeEnum(CostObject);

/** @internal */
export const CostType$inboundSchema: z.ZodNativeEnum<typeof CostType> = z
  .nativeEnum(CostType);

/** @internal */
export const CostAggregation$inboundSchema: z.ZodNativeEnum<
  typeof CostAggregation
> = z.nativeEnum(CostAggregation);

/** @internal */
export const Cost$inboundSchema: z.ZodType<Cost, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    object: CostObject$inboundSchema.default("cost"),
    type: CostType$inboundSchema,
    name: z.string(),
    currency: z.string(),
    unitCost: z.string(),
    unit: z.nullable(z.string()).optional(),
    aggregation: z.nullable(CostAggregation$inboundSchema).optional(),
    eventType: z.nullable(z.string()).optional(),
    valueProperty: z.nullable(z.string()).optional(),
    groupBy: z.nullable(z.record(z.string())).optional(),
    productId: z.string(),
    merchantId: z.string(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    updatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    deletedAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
  });

export function costFromJSON(
  jsonString: string,
): SafeParseResult<Cost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cost' from JSON`,
  );
}
