/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CostUsageResponseObject = {
  Cost: "cost",
} as const;
export type CostUsageResponseObject = ClosedEnum<
  typeof CostUsageResponseObject
>;

export const CostUsageResponseType = {
  Metered: "metered",
} as const;
export type CostUsageResponseType = ClosedEnum<typeof CostUsageResponseType>;

export type Group = {
  dimensions: { [k: string]: string };
  quantity: number;
  cost: number;
};

export type TimeSery = {
  windowStart: Date;
  windowEnd: Date;
  quantity: number;
  cost: number;
};

export type CostUsageResponse = {
  object: CostUsageResponseObject;
  /**
   * Unique identifier for a cost
   */
  id: string;
  name: string;
  type: CostUsageResponseType;
  currency: string;
  /**
   * CloudEvents type for metered costs.
   */
  eventType?: string | undefined;
  /**
   * Total cost for the query window. Null if usage data could not be computed.
   */
  totalCost: number | null;
  /**
   * Total usage quantity (metered costs only). Null when usage was not computed.
   */
  totalQuantity?: number | null | undefined;
  /**
   * Per-group breakdown (present when groupBy is specified).
   */
  groups?: Array<Group> | undefined;
  /**
   * Time-series breakdown (present when window is specified).
   */
  timeSeries?: Array<TimeSery> | undefined;
};

/** @internal */
export const CostUsageResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof CostUsageResponseObject
> = z.nativeEnum(CostUsageResponseObject);

/** @internal */
export const CostUsageResponseType$inboundSchema: z.ZodNativeEnum<
  typeof CostUsageResponseType
> = z.nativeEnum(CostUsageResponseType);

/** @internal */
export const Group$inboundSchema: z.ZodType<Group, z.ZodTypeDef, unknown> = z
  .object({
    dimensions: z.record(z.string()),
    quantity: z.number(),
    cost: z.number(),
  });

export function groupFromJSON(
  jsonString: string,
): SafeParseResult<Group, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Group$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Group' from JSON`,
  );
}

/** @internal */
export const TimeSery$inboundSchema: z.ZodType<
  TimeSery,
  z.ZodTypeDef,
  unknown
> = z.object({
  windowStart: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  windowEnd: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  quantity: z.number(),
  cost: z.number(),
});

export function timeSeryFromJSON(
  jsonString: string,
): SafeParseResult<TimeSery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimeSery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimeSery' from JSON`,
  );
}

/** @internal */
export const CostUsageResponse$inboundSchema: z.ZodType<
  CostUsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: CostUsageResponseObject$inboundSchema.default("cost"),
  id: z.string(),
  name: z.string(),
  type: CostUsageResponseType$inboundSchema,
  currency: z.string(),
  eventType: z.string().optional(),
  totalCost: z.nullable(z.number()),
  totalQuantity: z.nullable(z.number()).optional(),
  groups: z.array(z.lazy(() => Group$inboundSchema)).optional(),
  timeSeries: z.array(z.lazy(() => TimeSery$inboundSchema)).optional(),
});

export function costUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<CostUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CostUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CostUsageResponse' from JSON`,
  );
}
