/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  RuleCondition,
  RuleCondition$Outbound,
  RuleCondition$outboundSchema,
} from "./rulecondition.js";

export type CreateRuleRequest = {
  /**
   * Conditions that must ALL be met (AND logic) for auto-acceptance. Sample values: customerEmail domain='@trusted.com' AND amount lessThan=1000, customerId equals='org_abc123' AND billableMetricId equals='bm_tokens', subscriptionId equals='sub_xyz789' AND quantity greaterThan=100
   */
  conditions: Array<RuleCondition>;
  /**
   * Detailed description of what this source rule does
   */
  description?: string | undefined;
  /**
   * Whether this rule should be active immediately
   */
  enabled?: boolean | undefined;
  /**
   * Human-readable name for the source rule
   */
  name: string;
  /**
   * Evaluation priority (0-999). Lower numbers are evaluated first. First matching rule triggers auto-acceptance.
   */
  order?: number | undefined;
  /**
   * Unique identifier for a source
   */
  sourceId: string;
};

/** @internal */
export type CreateRuleRequest$Outbound = {
  conditions: Array<RuleCondition$Outbound>;
  description?: string | undefined;
  enabled: boolean;
  name: string;
  order: number;
  sourceId: string;
};

/** @internal */
export const CreateRuleRequest$outboundSchema: z.ZodType<
  CreateRuleRequest$Outbound,
  z.ZodTypeDef,
  CreateRuleRequest
> = z.object({
  conditions: z.array(RuleCondition$outboundSchema),
  description: z.string().optional(),
  enabled: z.boolean().default(true),
  name: z.string(),
  order: z.number().int().default(0),
  sourceId: z.string(),
});

export function createRuleRequestToJSON(
  createRuleRequest: CreateRuleRequest,
): string {
  return JSON.stringify(
    CreateRuleRequest$outboundSchema.parse(createRuleRequest),
  );
}
