/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CreateMaximumQuantityAdjustment = {
  /**
   * Bills at most the contracted quantity on one price, whatever the customer actually used.
   */
  type: "maximumQuantity";
  /**
   * The contracted maximum quantity for one billing period of the target price, sent as a plain decimal string. Not negative, at most 6 decimal places, fewer than 35 digits before the point. Plain notation only — no sign, exponent, hex or digit separators, so "1_000" and "1e3" are rejected rather than read as 1000. "4" bills 4 seats in a period the customer used 9 in; a value of 0 bills nothing at all. Measured over the whole billing period, not per line: where a period is split into several lines, each line's quantity counts for its share of the period, and every line is scaled by the same factor to bring the period to the maximum. Several bounds of the same direction on one price do not add up — the greatest minimum and the least maximum are the ones that apply.
   */
  maximumQuantity: string;
  /**
   * Exactly one price of this subscription. A metered price is accepted, and so is a price whose supply is outside the scope of VAT: a bound constrains a measurement rather than an amount of consideration. A price that bills once rather than per period is refused, because there is no repeating period for the bound to be measured over.
   */
  targetPriceIds: Array<string>;
  /**
   * Opens the window. Exclusive for this type: a line is bounded when its period END falls after this instant, so a window opening exactly when a period ends belongs to the next period, not that one. The bound is never prorated — a window opening mid-period applies to that whole period.
   */
  effectiveFrom: Date;
  /**
   * Closes the window. INCLUSIVE for this type, like usageDiscount and unlike percentageDiscount: set this to the exact period end you are bounding and that period is covered. Null means the bound never stops. Must be after effectiveFrom.
   */
  effectiveTo?: Date | null | undefined;
  /**
   * Your own name for this term. A quantity bound emits no invoice line, so this is printed nowhere on the invoice — it is returned on the adjustment for your own records.
   */
  description?: string | null | undefined;
  /**
   * A key of your choosing that makes a retry safe. Sending the same key against the same subscription returns the adjustment already created and creates no second one. Without a key a retried request creates a second bound; two identical bounds change nothing, because bounds of one direction do not add up.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type CreateMaximumQuantityAdjustment$Outbound = {
  type: "maximumQuantity";
  maximumQuantity: string;
  targetPriceIds: Array<string>;
  effectiveFrom: string;
  effectiveTo?: string | null | undefined;
  description?: string | null | undefined;
  idempotencyKey?: string | undefined;
};

/** @internal */
export const CreateMaximumQuantityAdjustment$outboundSchema: z.ZodType<
  CreateMaximumQuantityAdjustment$Outbound,
  z.ZodTypeDef,
  CreateMaximumQuantityAdjustment
> = z.object({
  type: z.literal("maximumQuantity"),
  maximumQuantity: z.string(),
  targetPriceIds: z.array(z.string()),
  effectiveFrom: z.date().transform(v => v.toISOString()),
  effectiveTo: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  description: z.nullable(z.string()).optional(),
  idempotencyKey: z.string().optional(),
});

export function createMaximumQuantityAdjustmentToJSON(
  createMaximumQuantityAdjustment: CreateMaximumQuantityAdjustment,
): string {
  return JSON.stringify(
    CreateMaximumQuantityAdjustment$outboundSchema.parse(
      createMaximumQuantityAdjustment,
    ),
  );
}
