/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const CreateApprovalRequestResourceType = {
  Order: "order",
  Invoice: "invoice",
} as const;
export type CreateApprovalRequestResourceType = ClosedEnum<
  typeof CreateApprovalRequestResourceType
>;

/**
 * Defaults to data_review.
 */
export const CreateApprovalRequestKind = {
  DataReview: "data_review",
  FinancialReview: "financial_review",
  Push: "push",
} as const;
/**
 * Defaults to data_review.
 */
export type CreateApprovalRequestKind = ClosedEnum<
  typeof CreateApprovalRequestKind
>;

export type CreateApprovalRequest = {
  /**
   * The merchant that owns the resource being approved.
   */
  merchantId: string;
  resourceType: CreateApprovalRequestResourceType;
  resourceId: string;
  /**
   * A precomputed hash of the resource state being approved. The resource-owning domain builds this snapshot; approvals stays decoupled from any specific resource shape.
   */
  dataSnapshotHash: string;
  /**
   * Defaults to data_review.
   */
  kind?: CreateApprovalRequestKind | undefined;
  note?: string | null | undefined;
  /**
   * Optional. The real user id to record as the requester. Used when the request is made via a platform-level key on behalf of a human user (e.g. from the platform Next.js frontend). When supplied and the authenticated principal is 'platform', this value overrides the derived principal as the requester. Ignored when the caller is a non-platform API key.
   */
  actorId?: string | undefined;
};

/** @internal */
export const CreateApprovalRequestResourceType$outboundSchema: z.ZodNativeEnum<
  typeof CreateApprovalRequestResourceType
> = z.nativeEnum(CreateApprovalRequestResourceType);

/** @internal */
export const CreateApprovalRequestKind$outboundSchema: z.ZodNativeEnum<
  typeof CreateApprovalRequestKind
> = z.nativeEnum(CreateApprovalRequestKind);

/** @internal */
export type CreateApprovalRequest$Outbound = {
  merchantId: string;
  resourceType: string;
  resourceId: string;
  dataSnapshotHash: string;
  kind?: string | undefined;
  note?: string | null | undefined;
  actorId?: string | undefined;
};

/** @internal */
export const CreateApprovalRequest$outboundSchema: z.ZodType<
  CreateApprovalRequest$Outbound,
  z.ZodTypeDef,
  CreateApprovalRequest
> = z.object({
  merchantId: z.string(),
  resourceType: CreateApprovalRequestResourceType$outboundSchema,
  resourceId: z.string(),
  dataSnapshotHash: z.string(),
  kind: CreateApprovalRequestKind$outboundSchema.optional(),
  note: z.nullable(z.string()).optional(),
  actorId: z.string().optional(),
});

export function createApprovalRequestToJSON(
  createApprovalRequest: CreateApprovalRequest,
): string {
  return JSON.stringify(
    CreateApprovalRequest$outboundSchema.parse(createApprovalRequest),
  );
}
