/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CreateMaximumQuantityAdjustment,
  CreateMaximumQuantityAdjustment$Outbound,
  CreateMaximumQuantityAdjustment$outboundSchema,
} from "./createmaximumquantityadjustment.js";
import {
  CreateMinimumQuantityAdjustment,
  CreateMinimumQuantityAdjustment$Outbound,
  CreateMinimumQuantityAdjustment$outboundSchema,
} from "./createminimumquantityadjustment.js";
import {
  CreatePercentageDiscountAdjustment,
  CreatePercentageDiscountAdjustment$Outbound,
  CreatePercentageDiscountAdjustment$outboundSchema,
} from "./createpercentagediscountadjustment.js";
import {
  CreateUsageDiscountAdjustment,
  CreateUsageDiscountAdjustment$Outbound,
  CreateUsageDiscountAdjustment$outboundSchema,
} from "./createusagediscountadjustment.js";

/**
 * One adjustment to attach to the subscription. The type decides which number the body carries: a rate for percentageDiscount, a unit count and one target price for usageDiscount, and a contracted quantity and one target price for minimumQuantity and maximumQuantity.
 */
export type CreateSubscriptionAdjustmentRequest =
  | CreatePercentageDiscountAdjustment
  | CreateUsageDiscountAdjustment
  | CreateMinimumQuantityAdjustment
  | CreateMaximumQuantityAdjustment;

/** @internal */
export type CreateSubscriptionAdjustmentRequest$Outbound =
  | CreatePercentageDiscountAdjustment$Outbound
  | CreateUsageDiscountAdjustment$Outbound
  | CreateMinimumQuantityAdjustment$Outbound
  | CreateMaximumQuantityAdjustment$Outbound;

/** @internal */
export const CreateSubscriptionAdjustmentRequest$outboundSchema: z.ZodType<
  CreateSubscriptionAdjustmentRequest$Outbound,
  z.ZodTypeDef,
  CreateSubscriptionAdjustmentRequest
> = z.union([
  CreatePercentageDiscountAdjustment$outboundSchema,
  CreateUsageDiscountAdjustment$outboundSchema,
  CreateMinimumQuantityAdjustment$outboundSchema,
  CreateMaximumQuantityAdjustment$outboundSchema,
]);

export function createSubscriptionAdjustmentRequestToJSON(
  createSubscriptionAdjustmentRequest: CreateSubscriptionAdjustmentRequest,
): string {
  return JSON.stringify(
    CreateSubscriptionAdjustmentRequest$outboundSchema.parse(
      createSubscriptionAdjustmentRequest,
    ),
  );
}
