/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CreateOrderApprovalRequest = {
  /**
   * Optional. The maker submitting the order. Derived from the authenticated principal; only a platform key may set it explicitly.
   */
  requester?: string | undefined;
  note?: string | null | undefined;
};

/** @internal */
export type CreateOrderApprovalRequest$Outbound = {
  requester?: string | undefined;
  note?: string | null | undefined;
};

/** @internal */
export const CreateOrderApprovalRequest$outboundSchema: z.ZodType<
  CreateOrderApprovalRequest$Outbound,
  z.ZodTypeDef,
  CreateOrderApprovalRequest
> = z.object({
  requester: z.string().optional(),
  note: z.nullable(z.string()).optional(),
});

export function createOrderApprovalRequestToJSON(
  createOrderApprovalRequest: CreateOrderApprovalRequest,
): string {
  return JSON.stringify(
    CreateOrderApprovalRequest$outboundSchema.parse(createOrderApprovalRequest),
  );
}
