/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CreateUsageDiscountAdjustment = {
  /**
   * Reduces one metered price's billable quantity by a number of usage units, before the line is priced.
   */
  type: "usageDiscount";
  /**
   * The number of usage units to take off the billable quantity, sent as a plain decimal string. "300" waives 300 units. Greater than 0, at most 6 decimal places, fewer than 35 digits before the point. Plain notation only — no sign, exponent, hex or digit separators, so "1_000" and "1e3" are rejected rather than read as 1000. Applied in full or not at all — a unit count is never prorated across a partial window — and once per matching line, so an invoice bundling several periods is corrected on each of them. The line is floored at 0, so a discount larger than the billable quantity zeroes it rather than crediting. On a volume ladder the corrected quantity also re-selects the band, so a waiver that crosses a boundary can bill more than the uncorrected line did: waiving 300 of 1000 units on a ladder of 2.00 up to 999 and 1.00 beyond bills 700 at 2.00 for 1400.00, where the 1000 units billed 1000.00. That is the ladder's price for the corrected usage — what a customer who genuinely used 700 units pays — so check the ladder before waiving units near a band boundary.
   */
  usageDiscount: string;
  /**
   * Exactly one metered price of this subscription, priced as standard or volume. Usage units are not comparable across metrics, so a usage discount names the one price it reduces. A dynamic or percentage price is refused: its quantity is a monetary amount rather than a unit count. A price billing at a negative rate (a usage-scaled rebate) is refused too, because removing its units would raise the invoice.
   */
  targetPriceIds: Array<string>;
  /**
   * Opens the window. Exclusive for this type: a metered line is corrected when its period END falls after this instant, so a window opening exactly when a period ends belongs to the next period, not that one. Set it to the start of the period you are correcting.
   */
  effectiveFrom: Date;
  /**
   * Closes the window. INCLUSIVE for this type, unlike percentageDiscount: a metered line bills in arrears, so set this to the exact period end you are correcting and that period is covered. Null means the discount never stops — it then takes its full unit count off this price on EVERY later invoice, so set both bounds whenever you are correcting one period. Must be after effectiveFrom.
   */
  effectiveTo?: Date | null | undefined;
  /**
   * Your own name for this correction. A usageDiscount emits no invoice line, so this is printed nowhere on the invoice — it is returned on the adjustment for your own records.
   */
  description?: string | null | undefined;
  /**
   * A key of your choosing that makes a retry safe. Sending the same key against the same subscription returns the adjustment already created and creates no second one. Without a key a retried request creates a second adjustment, and usage discounts against one price SUM — two of "300" waive 600 units, not 300. Nothing else detects a duplicate.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type CreateUsageDiscountAdjustment$Outbound = {
  type: "usageDiscount";
  usageDiscount: string;
  targetPriceIds: Array<string>;
  effectiveFrom: string;
  effectiveTo?: string | null | undefined;
  description?: string | null | undefined;
  idempotencyKey?: string | undefined;
};

/** @internal */
export const CreateUsageDiscountAdjustment$outboundSchema: z.ZodType<
  CreateUsageDiscountAdjustment$Outbound,
  z.ZodTypeDef,
  CreateUsageDiscountAdjustment
> = z.object({
  type: z.literal("usageDiscount"),
  usageDiscount: z.string(),
  targetPriceIds: z.array(z.string()),
  effectiveFrom: z.date().transform(v => v.toISOString()),
  effectiveTo: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  description: z.nullable(z.string()).optional(),
  idempotencyKey: z.string().optional(),
});

export function createUsageDiscountAdjustmentToJSON(
  createUsageDiscountAdjustment: CreateUsageDiscountAdjustment,
): string {
  return JSON.stringify(
    CreateUsageDiscountAdjustment$outboundSchema.parse(
      createUsageDiscountAdjustment,
    ),
  );
}
