/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CustomerPaymentSessionObject = {
  PaymentSession: "paymentSession",
} as const;
export type CustomerPaymentSessionObject = ClosedEnum<
  typeof CustomerPaymentSessionObject
>;

export const Mode = {
  Payment: "payment",
  Setup: "setup",
} as const;
export type Mode = ClosedEnum<typeof Mode>;

export const CustomerPaymentSessionStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Failed: "failed",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
export type CustomerPaymentSessionStatus = ClosedEnum<
  typeof CustomerPaymentSessionStatus
>;

export type CustomerPaymentSession = {
  object: CustomerPaymentSessionObject;
  /**
   * Payment session identifier (e.g. `ps_...`).
   */
  id: string;
  mode: Mode;
  status: CustomerPaymentSessionStatus;
  /**
   * Hosted page URL. Redirect the customer here, or load it inside an iframe — when iframed, the page reports outcomes via `postMessage` (`payment_success` / `payment_error`) to the parent window.
   */
  url: string;
  successRedirectUrl?: string | null | undefined;
  failureRedirectUrl?: string | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  expiresAt: Date;
  completedAt?: Date | null | undefined;
  createdAt: Date;
};

/** @internal */
export const CustomerPaymentSessionObject$inboundSchema: z.ZodNativeEnum<
  typeof CustomerPaymentSessionObject
> = z.nativeEnum(CustomerPaymentSessionObject);

/** @internal */
export const Mode$inboundSchema: z.ZodNativeEnum<typeof Mode> = z.nativeEnum(
  Mode,
);

/** @internal */
export const CustomerPaymentSessionStatus$inboundSchema: z.ZodNativeEnum<
  typeof CustomerPaymentSessionStatus
> = z.nativeEnum(CustomerPaymentSessionStatus);

/** @internal */
export const CustomerPaymentSession$inboundSchema: z.ZodType<
  CustomerPaymentSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: CustomerPaymentSessionObject$inboundSchema,
  id: z.string(),
  mode: Mode$inboundSchema,
  status: CustomerPaymentSessionStatus$inboundSchema,
  url: z.string(),
  successRedirectUrl: z.nullable(z.string()).optional(),
  failureRedirectUrl: z.nullable(z.string()).optional(),
  metadata: z.record(z.any()).optional(),
  expiresAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  completedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function customerPaymentSessionFromJSON(
  jsonString: string,
): SafeParseResult<CustomerPaymentSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerPaymentSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerPaymentSession' from JSON`,
  );
}
