/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SubscriptionInterval,
  SubscriptionInterval$inboundSchema,
} from "./subscriptioninterval.js";

export type EditSubscriptionIntervalsResponseLineItems = {
  /**
   * Number of distinct prices that gained a line item as this timeline edit was re-derived into billing.
   */
  created: number;
  /**
   * Number of distinct prices whose future/uninvoiced line items were removed as this timeline edit was re-derived into billing.
   */
  removed: number;
  /**
   * True when the timeline edit was saved but the line-item re-derive failed. The edit is not rolled back, and the re-derive is retried automatically. Resubmitting the same request retries it sooner.
   */
  syncFailed?: boolean | undefined;
};

export type EditSubscriptionIntervalsResponse = {
  /**
   * The timeline's effective price intervals after applying the op set, ordered by start date.
   */
  intervals: Array<SubscriptionInterval>;
  /**
   * True when the op set resolved to no change and nothing was written.
   */
  unchanged: boolean;
  lineItems: EditSubscriptionIntervalsResponseLineItems;
};

/** @internal */
export const EditSubscriptionIntervalsResponseLineItems$inboundSchema:
  z.ZodType<EditSubscriptionIntervalsResponseLineItems, z.ZodTypeDef, unknown> =
    z.object({
      created: z.number().int(),
      removed: z.number().int(),
      syncFailed: z.boolean().optional(),
    });

export function editSubscriptionIntervalsResponseLineItemsFromJSON(
  jsonString: string,
): SafeParseResult<
  EditSubscriptionIntervalsResponseLineItems,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditSubscriptionIntervalsResponseLineItems$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditSubscriptionIntervalsResponseLineItems' from JSON`,
  );
}

/** @internal */
export const EditSubscriptionIntervalsResponse$inboundSchema: z.ZodType<
  EditSubscriptionIntervalsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  intervals: z.array(SubscriptionInterval$inboundSchema),
  unchanged: z.boolean(),
  lineItems: z.lazy(() =>
    EditSubscriptionIntervalsResponseLineItems$inboundSchema
  ),
});

export function editSubscriptionIntervalsResponseFromJSON(
  jsonString: string,
): SafeParseResult<EditSubscriptionIntervalsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditSubscriptionIntervalsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditSubscriptionIntervalsResponse' from JSON`,
  );
}
