/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  SubscriptionIntervalAddOp,
  SubscriptionIntervalAddOp$Outbound,
  SubscriptionIntervalAddOp$outboundSchema,
} from "./subscriptionintervaladdop.js";
import {
  SubscriptionIntervalEditOp,
  SubscriptionIntervalEditOp$Outbound,
  SubscriptionIntervalEditOp$outboundSchema,
} from "./subscriptionintervaleditop.js";
import {
  SubscriptionIntervalRemoveOp,
  SubscriptionIntervalRemoveOp$Outbound,
  SubscriptionIntervalRemoveOp$outboundSchema,
} from "./subscriptionintervalremoveop.js";

/**
 * An add/edit/remove op set to apply to the subscription's price timeline. At least one operation is required.
 */
export type EditSubscriptionIntervalsRequest = {
  /**
   * New override segments to add.
   */
  add?: Array<SubscriptionIntervalAddOp> | undefined;
  /**
   * Changes to existing intervals.
   */
  edit?: Array<SubscriptionIntervalEditOp> | undefined;
  /**
   * Intervals to remove outright.
   */
  remove?: Array<SubscriptionIntervalRemoveOp> | undefined;
};

/** @internal */
export type EditSubscriptionIntervalsRequest$Outbound = {
  add?: Array<SubscriptionIntervalAddOp$Outbound> | undefined;
  edit?: Array<SubscriptionIntervalEditOp$Outbound> | undefined;
  remove?: Array<SubscriptionIntervalRemoveOp$Outbound> | undefined;
};

/** @internal */
export const EditSubscriptionIntervalsRequest$outboundSchema: z.ZodType<
  EditSubscriptionIntervalsRequest$Outbound,
  z.ZodTypeDef,
  EditSubscriptionIntervalsRequest
> = z.object({
  add: z.array(SubscriptionIntervalAddOp$outboundSchema).optional(),
  edit: z.array(SubscriptionIntervalEditOp$outboundSchema).optional(),
  remove: z.array(SubscriptionIntervalRemoveOp$outboundSchema).optional(),
});

export function editSubscriptionIntervalsRequestToJSON(
  editSubscriptionIntervalsRequest: EditSubscriptionIntervalsRequest,
): string {
  return JSON.stringify(
    EditSubscriptionIntervalsRequest$outboundSchema.parse(
      editSubscriptionIntervalsRequest,
    ),
  );
}
