/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The type of feature: `boolean` (on/off), `static` (with config), or `metered` (usage-based).
 */
export const EntitlementAccessResultFeatureType = {
  Boolean: "boolean",
  Static: "static",
  Metered: "metered",
} as const;
/**
 * The type of feature: `boolean` (on/off), `static` (with config), or `metered` (usage-based).
 */
export type EntitlementAccessResultFeatureType = ClosedEnum<
  typeof EntitlementAccessResultFeatureType
>;

/**
 * Current status of the entitlement.
 */
export const EntitlementAccessResultStatus = {
  Active: "active",
  Canceled: "canceled",
  Expired: "expired",
} as const;
/**
 * Current status of the entitlement.
 */
export type EntitlementAccessResultStatus = ClosedEnum<
  typeof EntitlementAccessResultStatus
>;

/**
 * A customer's entitlement to a specific feature.
 */
export type EntitlementAccessResult = {
  /**
   * Whether the customer currently has active access to this feature.
   */
  hasAccess: boolean;
  /**
   * The unique key identifying the feature.
   */
  featureKey: string;
  /**
   * The type of feature: `boolean` (on/off), `static` (with config), or `metered` (usage-based).
   */
  featureType: EntitlementAccessResultFeatureType;
  /**
   * Configuration values for `static` features. Null for other types.
   */
  config?: { [k: string]: any } | null | undefined;
  /**
   * Unique identifier for this entitlement.
   */
  entitlementId: string;
  /**
   * Unique identifier for a product
   */
  productId: string;
  /**
   * When the entitlement becomes active.
   */
  activeFrom: Date;
  /**
   * When the entitlement expires. Null means no expiration.
   */
  activeTo?: Date | null | undefined;
  /**
   * Current status of the entitlement.
   */
  status: EntitlementAccessResultStatus;
};

/** @internal */
export const EntitlementAccessResultFeatureType$inboundSchema: z.ZodNativeEnum<
  typeof EntitlementAccessResultFeatureType
> = z.nativeEnum(EntitlementAccessResultFeatureType);

/** @internal */
export const EntitlementAccessResultStatus$inboundSchema: z.ZodNativeEnum<
  typeof EntitlementAccessResultStatus
> = z.nativeEnum(EntitlementAccessResultStatus);

/** @internal */
export const EntitlementAccessResult$inboundSchema: z.ZodType<
  EntitlementAccessResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  hasAccess: z.boolean(),
  featureKey: z.string(),
  featureType: EntitlementAccessResultFeatureType$inboundSchema,
  config: z.nullable(z.record(z.any())).optional(),
  entitlementId: z.string(),
  productId: z.string(),
  activeFrom: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  activeTo: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  status: EntitlementAccessResultStatus$inboundSchema,
});

export function entitlementAccessResultFromJSON(
  jsonString: string,
): SafeParseResult<EntitlementAccessResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntitlementAccessResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntitlementAccessResult' from JSON`,
  );
}
