/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of Paygentic entity this external reference points at
 */
export const EntityType = {
  Item: "item",
} as const;
/**
 * The type of Paygentic entity this external reference points at
 */
export type EntityType = ClosedEnum<typeof EntityType>;

/** @internal */
export const EntityType$inboundSchema: z.ZodNativeEnum<typeof EntityType> = z
  .nativeEnum(EntityType);
/** @internal */
export const EntityType$outboundSchema: z.ZodNativeEnum<typeof EntityType> =
  EntityType$inboundSchema;
