/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Current status of the entitlement.
 */
export const EntitlementStatus = {
  Active: "active",
  Canceled: "canceled",
  Expired: "expired",
} as const;
/**
 * Current status of the entitlement.
 */
export type EntitlementStatus = ClosedEnum<typeof EntitlementStatus>;

/** @internal */
export const EntitlementStatus$inboundSchema: z.ZodNativeEnum<
  typeof EntitlementStatus
> = z.nativeEnum(EntitlementStatus);
