/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const GrantObject = {
  Grant: "grant",
} as const;
export type GrantObject = ClosedEnum<typeof GrantObject>;

export type Grant = {
  object: GrantObject;
  /**
   * Unique identifier for the grant.
   */
  id: string;
  /**
   * The entitlement this grant belongs to.
   */
  entitlementId: string;
  /**
   * The number of credits granted.
   */
  amount: number;
  /**
   * When the grant becomes effective.
   */
  effectiveAt: Date;
  /**
   * When the grant expires. Null means no expiration.
   */
  expiresAt?: Date | null | undefined;
  /**
   * When the grant was voided. Null means the grant is active.
   */
  voidedAt?: Date | null | undefined;
  /**
   * When the grant was created.
   */
  createdAt: Date;
};

/** @internal */
export const GrantObject$inboundSchema: z.ZodNativeEnum<typeof GrantObject> = z
  .nativeEnum(GrantObject);

/** @internal */
export const Grant$inboundSchema: z.ZodType<Grant, z.ZodTypeDef, unknown> = z
  .object({
    object: GrantObject$inboundSchema.default("grant"),
    id: z.string(),
    entitlementId: z.string(),
    amount: z.number(),
    effectiveAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    expiresAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    voidedAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  });

export function grantFromJSON(
  jsonString: string,
): SafeParseResult<Grant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Grant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Grant' from JSON`,
  );
}
