/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GroupTrendEntry = {
  /**
   * Unique identifier for the group (e.g. plan ID, or 'other')
   */
  groupKey: string;
  /**
   * Human-readable label for the group (e.g. plan name)
   */
  groupLabel: string;
  /**
   * Total issued invoice amount in dollars for this group in this bucket
   */
  issuedInvoices: string;
};

/** @internal */
export const GroupTrendEntry$inboundSchema: z.ZodType<
  GroupTrendEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  groupKey: z.string(),
  groupLabel: z.string(),
  issuedInvoices: z.string(),
});

export function groupTrendEntryFromJSON(
  jsonString: string,
): SafeParseResult<GroupTrendEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupTrendEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupTrendEntry' from JSON`,
  );
}
