/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type IntervalChangeMetadata = string | number | boolean;

/** @internal */
export const IntervalChangeMetadata$inboundSchema: z.ZodType<
  IntervalChangeMetadata,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);
/** @internal */
export type IntervalChangeMetadata$Outbound = string | number | boolean;

/** @internal */
export const IntervalChangeMetadata$outboundSchema: z.ZodType<
  IntervalChangeMetadata$Outbound,
  z.ZodTypeDef,
  IntervalChangeMetadata
> = z.union([z.string(), z.number(), z.boolean()]);

export function intervalChangeMetadataToJSON(
  intervalChangeMetadata: IntervalChangeMetadata,
): string {
  return JSON.stringify(
    IntervalChangeMetadata$outboundSchema.parse(intervalChangeMetadata),
  );
}
export function intervalChangeMetadataFromJSON(
  jsonString: string,
): SafeParseResult<IntervalChangeMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IntervalChangeMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntervalChangeMetadata' from JSON`,
  );
}
