/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Type of event: 'usage' for billable metric events, 'fee' for fee events, 'discount' for grant discount line items (subtotal/total are negative, representing a credit)
 */
export const EventType = {
  Usage: "usage",
  Fee: "fee",
  Discount: "discount",
} as const;
/**
 * Type of event: 'usage' for billable metric events, 'fee' for fee events, 'discount' for grant discount line items (subtotal/total are negative, representing a credit)
 */
export type EventType = ClosedEnum<typeof EventType>;

/**
 * When this line falls due relative to the window it covers: `in_advance` at the window's start, `in_arrears` at its end. A metered line is stamped `in_arrears`, because usage is only known once the window closes — but metered rows written before that rule carry `null` and were never backfilled, so do not read a metered line's term as guaranteed. `null` also means the line is not billed on a term of its own: manual, grant-discount and adjustment lines carry no term, and an adjustment instead falls due with the charge it reduces. Treat `null` as an expected value on any line type, not an error.
 */
export const InvoiceLineItemPaymentTerm = {
  InAdvance: "in_advance",
  InArrears: "in_arrears",
} as const;
/**
 * When this line falls due relative to the window it covers: `in_advance` at the window's start, `in_arrears` at its end. A metered line is stamped `in_arrears`, because usage is only known once the window closes — but metered rows written before that rule carry `null` and were never backfilled, so do not read a metered line's term as guaranteed. `null` also means the line is not billed on a term of its own: manual, grant-discount and adjustment lines carry no term, and an adjustment instead falls due with the charge it reduces. Treat `null` as an expected value on any line type, not an error.
 */
export type InvoiceLineItemPaymentTerm = ClosedEnum<
  typeof InvoiceLineItemPaymentTerm
>;

/**
 * Type of line item: 'charge' for regular billing, 'refund' for refunded items (amounts are negated)
 */
export const InvoiceLineItemLineItemType = {
  Charge: "charge",
  Refund: "refund",
} as const;
/**
 * Type of line item: 'charge' for regular billing, 'refund' for refunded items (amounts are negated)
 */
export type InvoiceLineItemLineItemType = ClosedEnum<
  typeof InvoiceLineItemLineItemType
>;

export type InvoiceLineItem = {
  /**
   * Type of event: 'usage' for billable metric events, 'fee' for fee events, 'discount' for grant discount line items (subtotal/total are negative, representing a credit)
   */
  eventType: EventType;
  /**
   * The event ID (usage_event_id or fee_event_id)
   */
  eventId: string;
  /**
   * Source ID: billable_metric_id for usage events, fee_id for fee events
   */
  eventSourceId: string;
  /**
   * HOTFIX: Mirrors eventSourceId for backward compatibility
   */
  billableMetricId: string;
  /**
   * Item the line's charge was tagged with, recorded when the line was generated and not re-resolved on read. A discount line carries the same item as the charge it offsets. `null` means the charge carried no tag at that moment, the line predates item stamping, or the line has no originating charge (a grant-credit purchase) — it is an expected value, not an error. Use `priceId` to tell those cases apart.
   */
  itemId?: string | null | undefined;
  /**
   * The price this line was generated from, or `null` when the line has no originating charge. With `itemId` it says whether a missing tag is fixable: `priceId` set and `itemId` null means the charge was simply untagged, which tagging it and restamping resolves; both null means the line records a grant-credit purchase, which is deferred revenue and is never tagged. Any measure of outstanding mapping work must exclude the latter or it can never reach zero.
   */
  priceId?: string | null | undefined;
  /**
   * Start of the billed window this line covers, inclusive. Distinct from the invoice's own period, which is the union of its lines' windows (earliest start to latest end) and so covers time no single line bills on a mixed-timing invoice.
   */
  periodStart?: Date | undefined;
  /**
   * End of the billed window this line covers, exclusive — the instant at `periodEnd` belongs to the next window. Equal to `periodStart` on a one-off charge, which bills at an instant and has no period grid.
   */
  periodEnd?: Date | undefined;
  /**
   * When this line falls due relative to the window it covers: `in_advance` at the window's start, `in_arrears` at its end. A metered line is stamped `in_arrears`, because usage is only known once the window closes — but metered rows written before that rule carry `null` and were never backfilled, so do not read a metered line's term as guaranteed. `null` also means the line is not billed on a term of its own: manual, grant-discount and adjustment lines carry no term, and an adjustment instead falls due with the charge it reduces. Treat `null` as an expected value on any line type, not an error.
   */
  paymentTerm?: InvoiceLineItemPaymentTerm | null | undefined;
  /**
   * Display name for this line item on invoices
   */
  invoiceDisplayName: string;
  /**
   * Type of line item: 'charge' for regular billing, 'refund' for refunded items (amounts are negated)
   */
  lineItemType: InvoiceLineItemLineItemType;
  /**
   * The meter event ID (usage events only)
   */
  meterEventId: string;
  /**
   * Description of what this metric or fee measures
   */
  metricDescription: string;
  /**
   * Human-readable name of the billable metric or fee
   */
  metricName: string;
  /**
   * Measurement unit label. Sample values: 'calls' for API calls, 'GB' for storage, 'hours' for compute time, 'tokens' for LLM tokens, 'charge' for fees
   */
  metricUnit: string;
  /**
   * Quantity of usage. Negative for refunds.
   */
  quantity: number;
  /**
   * Tax rate as decimal (0.10 = 10%)
   */
  taxRate: number;
  /**
   * Total amount (totalPrice + totalTax) in decimal dollars. Negative for refunds.
   */
  totalAmount: string;
  /**
   * Total price (tax-exclusive) in decimal dollars. Negative for refunds.
   */
  totalPrice: string;
  /**
   * Total tax in decimal dollars. Negative for refunds.
   */
  totalTax: string;
  /**
   * Unit price in decimal dollars
   */
  unitPrice: string;
};

/** @internal */
export const EventType$inboundSchema: z.ZodNativeEnum<typeof EventType> = z
  .nativeEnum(EventType);

/** @internal */
export const InvoiceLineItemPaymentTerm$inboundSchema: z.ZodNativeEnum<
  typeof InvoiceLineItemPaymentTerm
> = z.nativeEnum(InvoiceLineItemPaymentTerm);

/** @internal */
export const InvoiceLineItemLineItemType$inboundSchema: z.ZodNativeEnum<
  typeof InvoiceLineItemLineItemType
> = z.nativeEnum(InvoiceLineItemLineItemType);

/** @internal */
export const InvoiceLineItem$inboundSchema: z.ZodType<
  InvoiceLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  eventType: EventType$inboundSchema,
  eventId: z.string(),
  eventSourceId: z.string(),
  billableMetricId: z.string(),
  itemId: z.nullable(z.string()).optional(),
  priceId: z.nullable(z.string()).optional(),
  periodStart: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  periodEnd: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  paymentTerm: z.nullable(InvoiceLineItemPaymentTerm$inboundSchema).optional(),
  invoiceDisplayName: z.string(),
  lineItemType: InvoiceLineItemLineItemType$inboundSchema,
  meterEventId: z.string(),
  metricDescription: z.string(),
  metricName: z.string(),
  metricUnit: z.string(),
  quantity: z.number(),
  taxRate: z.number(),
  totalAmount: z.string(),
  totalPrice: z.string(),
  totalTax: z.string(),
  unitPrice: z.string(),
});

export function invoiceLineItemFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceLineItem' from JSON`,
  );
}
