/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { InvoiceRefund, InvoiceRefund$inboundSchema } from "./invoicerefund.js";

/**
 * The object type
 */
export const InvoiceRefundListObject = {
  List: "list",
} as const;
/**
 * The object type
 */
export type InvoiceRefundListObject = ClosedEnum<
  typeof InvoiceRefundListObject
>;

export type InvoiceRefundList = {
  /**
   * The object type
   */
  object: InvoiceRefundListObject;
  /**
   * The refunds for this invoice
   */
  data: Array<InvoiceRefund>;
};

/** @internal */
export const InvoiceRefundListObject$inboundSchema: z.ZodNativeEnum<
  typeof InvoiceRefundListObject
> = z.nativeEnum(InvoiceRefundListObject);

/** @internal */
export const InvoiceRefundList$inboundSchema: z.ZodType<
  InvoiceRefundList,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: InvoiceRefundListObject$inboundSchema,
  data: z.array(InvoiceRefund$inboundSchema),
});

export function invoiceRefundListFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceRefundList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceRefundList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceRefundList' from JSON`,
  );
}
