/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The type of line item. 'discount' line items represent grant discounts with negative subtotal/total amounts.
 */
export const LineItemType = {
  Fee: "fee",
  Metered: "metered",
  Manual: "manual",
  Discount: "discount",
} as const;
/**
 * The type of line item. 'discount' line items represent grant discounts with negative subtotal/total amounts.
 */
export type LineItemType = ClosedEnum<typeof LineItemType>;

/**
 * Whether this item is pending or already on an invoice
 */
export const LineItemStatus = {
  Pending: "pending",
  Invoiced: "invoiced",
} as const;
/**
 * Whether this item is pending or already on an invoice
 */
export type LineItemStatus = ClosedEnum<typeof LineItemStatus>;

/**
 * Payment term for fee items. Null for metered/manual lines
 */
export const LineItemPaymentTerm = {
  InAdvance: "in_advance",
  InArrears: "in_arrears",
} as const;
/**
 * Payment term for fee items. Null for metered/manual lines
 */
export type LineItemPaymentTerm = ClosedEnum<typeof LineItemPaymentTerm>;

export type LineItem = {
  /**
   * The line item ID
   */
  id: string;
  /**
   * The subscription this line item belongs to
   */
  subscriptionId: string;
  /**
   * The price ID associated with this line item
   */
  priceId?: string | null | undefined;
  /**
   * The invoice ID if this item has been invoiced
   */
  invoiceId?: string | null | undefined;
  /**
   * The type of line item. 'discount' line items represent grant discounts with negative subtotal/total amounts.
   */
  type: LineItemType;
  /**
   * Whether this item is pending or already on an invoice
   */
  status: LineItemStatus;
  /**
   * Human-readable label shown on the invoice
   */
  displayName: string;
  /**
   * Optional longer description
   */
  description?: string | null | undefined;
  /**
   * ISO 4217 currency code (e.g., USD)
   */
  currency: string;
  /**
   * Start of the billing period (inclusive)
   */
  periodStart: Date;
  /**
   * End of the billing period (exclusive)
   */
  periodEnd: Date;
  /**
   * When this line item should be collected into an invoice
   */
  invoiceAt: Date;
  /**
   * When metered quantity was last computed
   */
  calculatedAt?: Date | null | undefined;
  /**
   * Units sold. Null for metered lines until invoice close
   */
  quantity?: string | null | undefined;
  /**
   * Price per unit in invoice currency
   */
  unitPrice: string;
  /**
   * Raw metered usage. Null for fee/manual lines
   */
  meteredQuantity?: string | null | undefined;
  /**
   * Payment term for fee items. Null for metered/manual lines
   */
  paymentTerm?: LineItemPaymentTerm | null | undefined;
  /**
   * quantity x unitPrice, before discounts and taxes. Defaults to '0.00' when not yet calculated
   */
  subtotal?: string | undefined;
  /**
   * Total tax amount for this line item in decimal format. Null until invoice calculation is complete
   */
  taxesTotal?: string | null | undefined;
  /**
   * Final total after discounts and taxes. Defaults to '0.00' when not yet calculated
   */
  total?: string | undefined;
  /**
   * When the line item was created
   */
  createdAt: Date;
  /**
   * When the line item was last updated
   */
  updatedAt: Date;
  /**
   * Real-time estimated metered usage quantity. Only present for type=metered items during an active billing period. Null for fee/manual items or when estimation is unavailable.
   */
  estimatedMeteredQuantity?: string | null | undefined;
  /**
   * Real-time estimated subtotal based on current metered usage. Only present for type=metered items during an active billing period. Null for fee/manual items or when estimation is unavailable.
   */
  estimatedSubtotal?: string | null | undefined;
};

/** @internal */
export const LineItemType$inboundSchema: z.ZodNativeEnum<typeof LineItemType> =
  z.nativeEnum(LineItemType);

/** @internal */
export const LineItemStatus$inboundSchema: z.ZodNativeEnum<
  typeof LineItemStatus
> = z.nativeEnum(LineItemStatus);

/** @internal */
export const LineItemPaymentTerm$inboundSchema: z.ZodNativeEnum<
  typeof LineItemPaymentTerm
> = z.nativeEnum(LineItemPaymentTerm);

/** @internal */
export const LineItem$inboundSchema: z.ZodType<
  LineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  subscriptionId: z.string(),
  priceId: z.nullable(z.string()).optional(),
  invoiceId: z.nullable(z.string()).optional(),
  type: LineItemType$inboundSchema,
  status: LineItemStatus$inboundSchema,
  displayName: z.string(),
  description: z.nullable(z.string()).optional(),
  currency: z.string(),
  periodStart: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  periodEnd: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  invoiceAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  calculatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  quantity: z.nullable(z.string()).optional(),
  unitPrice: z.string(),
  meteredQuantity: z.nullable(z.string()).optional(),
  paymentTerm: z.nullable(LineItemPaymentTerm$inboundSchema).optional(),
  subtotal: z.string().optional(),
  taxesTotal: z.nullable(z.string()).optional(),
  total: z.string().optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  estimatedMeteredQuantity: z.nullable(z.string()).optional(),
  estimatedSubtotal: z.nullable(z.string()).optional(),
});

export function lineItemFromJSON(
  jsonString: string,
): SafeParseResult<LineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineItem' from JSON`,
  );
}
