/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * External provider a merchant can connect at the tenant level
 */
export const MerchantIntegrationProvider = {
  Salesforce: "salesforce",
} as const;
/**
 * External provider a merchant can connect at the tenant level
 */
export type MerchantIntegrationProvider = ClosedEnum<
  typeof MerchantIntegrationProvider
>;

/** @internal */
export const MerchantIntegrationProvider$inboundSchema: z.ZodNativeEnum<
  typeof MerchantIntegrationProvider
> = z.nativeEnum(MerchantIntegrationProvider);
/** @internal */
export const MerchantIntegrationProvider$outboundSchema: z.ZodNativeEnum<
  typeof MerchantIntegrationProvider
> = MerchantIntegrationProvider$inboundSchema;
