/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Connection lifecycle state. Live Ampersand health is separate and not stored here.
 */
export const MerchantIntegrationStatus = {
  Active: "active",
  Disconnected: "disconnected",
  Error: "error",
} as const;
/**
 * Connection lifecycle state. Live Ampersand health is separate and not stored here.
 */
export type MerchantIntegrationStatus = ClosedEnum<
  typeof MerchantIntegrationStatus
>;

/** @internal */
export const MerchantIntegrationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MerchantIntegrationStatus
> = z.nativeEnum(MerchantIntegrationStatus);
/** @internal */
export const MerchantIntegrationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MerchantIntegrationStatus
> = MerchantIntegrationStatus$inboundSchema;
