/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EntitlementStatus,
  EntitlementStatus$inboundSchema,
} from "./entitlementstatus.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const MeteredEntitlementDetailObject = {
  Entitlement: "entitlement",
} as const;
export type MeteredEntitlementDetailObject = ClosedEnum<
  typeof MeteredEntitlementDetailObject
>;

/**
 * Common fields shared by all entitlement types.
 */
export type MeteredEntitlementDetail = {
  object: MeteredEntitlementDetailObject;
  /**
   * Unique identifier for the entitlement.
   */
  id: string;
  /**
   * Unique identifier for a customer
   */
  customerId: string;
  /**
   * The feature this entitlement grants access to.
   */
  featureId: string;
  /**
   * The unique key identifying the feature.
   */
  featureKey: string;
  featureType: "metered";
  /**
   * Unique identifier for a product
   */
  productId: string;
  /**
   * The subscription this entitlement is associated with, if any.
   */
  subscriptionId: string | null;
  /**
   * Current status of the entitlement.
   */
  status: EntitlementStatus;
  /**
   * When the entitlement becomes active.
   */
  activeFrom: Date;
  /**
   * When the entitlement expires. Null means no expiration.
   */
  activeTo: Date | null;
  /**
   * Whether the customer currently has active access to this entitlement.
   */
  hasAccess: boolean;
  /**
   * Additional metadata for the entitlement.
   */
  metadata: { [k: string]: string };
  /**
   * Always `null` for metered entitlements. Surfaced on every entitlement so clients can read `config` without first switching on `featureType`.
   */
  config: { [k: string]: any } | null;
  /**
   * When false (hard limit), access is blocked when balance is exhausted and overage is not charged on invoices. When true (soft limit), access continues past the grant and overage is charged at the per-unit rate.
   */
  isSoftLimit: boolean;
  /**
   * Remaining balance for the current period. When `pricingUnitId` is set, this is expressed in that pricing unit's credits (a balance shared across every feature drawing the same unit); otherwise it is in the feature's native metered units.
   */
  balance: number;
  /**
   * Total usage consumed in the current billing period, in the same unit as `balance` (credits when `pricingUnitId` is set, otherwise native metered units). When `pricingUnitId` is set, this is the shared-pool aggregate across every feature drawing the same unit, not usage specific to this feature.
   */
  usageInPeriod: number;
  /**
   * Amount of usage exceeding the balance, in the same unit as `balance` (credits when `pricingUnitId` is set, otherwise native metered units).
   */
  overage: number;
  /**
   * The pricing unit this feature is denominated in when it draws a credit pool. When set, `balance`/`usageInPeriod`/`overage` are in that unit's credits and reflect a balance shared across all features on the same unit. `null` for currency-denominated features (native metered units).
   */
  pricingUnitId: string | null;
  /**
   * Start of the current usage period. These bounds describe this entitlement's own usage window (not the shared pool's), even for a pool-backed feature (`pricingUnitId` set) whose `balance` and `usageInPeriod` are shared-pool aggregates. Before the entitlement activates (the pre-activation "dark window", when the query time is earlier than `activeFrom`) this instead describes the pre-activation `[subscription start, activation)` window and may be `null` when there is no associated subscription.
   */
  currentPeriodStart: Date | null;
  /**
   * End of the current usage period. These bounds describe this entitlement's own usage window (not the shared pool's), even for a pool-backed feature (`pricingUnitId` set) whose `balance` and `usageInPeriod` are shared-pool aggregates. Before the entitlement activates (the pre-activation "dark window", when the query time is earlier than `activeFrom`) this instead holds `activeFrom` — the end of the pre-activation `[subscription start, activation)` window.
   */
  currentPeriodEnd: Date | null;
};

/** @internal */
export const MeteredEntitlementDetailObject$inboundSchema: z.ZodNativeEnum<
  typeof MeteredEntitlementDetailObject
> = z.nativeEnum(MeteredEntitlementDetailObject);

/** @internal */
export const MeteredEntitlementDetail$inboundSchema: z.ZodType<
  MeteredEntitlementDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: MeteredEntitlementDetailObject$inboundSchema.default("entitlement"),
  id: z.string(),
  customerId: z.string(),
  featureId: z.string(),
  featureKey: z.string(),
  featureType: z.literal("metered"),
  productId: z.string(),
  subscriptionId: z.nullable(z.string()),
  status: EntitlementStatus$inboundSchema,
  activeFrom: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  activeTo: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  hasAccess: z.boolean(),
  metadata: z.record(z.string()),
  config: z.nullable(z.record(z.any())),
  isSoftLimit: z.boolean(),
  balance: z.number(),
  usageInPeriod: z.number(),
  overage: z.number(),
  pricingUnitId: z.nullable(z.string()),
  currentPeriodStart: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  currentPeriodEnd: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
});

export function meteredEntitlementDetailFromJSON(
  jsonString: string,
): SafeParseResult<MeteredEntitlementDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeteredEntitlementDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeteredEntitlementDetail' from JSON`,
  );
}
