/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  MintPlanLineInput,
  MintPlanLineInput$Outbound,
  MintPlanLineInput$outboundSchema,
} from "./mintplanlineinput.js";

/**
 * Either a price ID on its own, or a price ID with the key that names its line.
 */
export type MintPlanLineRef = MintPlanLineInput | string;

/** @internal */
export type MintPlanLineRef$Outbound = MintPlanLineInput$Outbound | string;

/** @internal */
export const MintPlanLineRef$outboundSchema: z.ZodType<
  MintPlanLineRef$Outbound,
  z.ZodTypeDef,
  MintPlanLineRef
> = z.union([MintPlanLineInput$outboundSchema, z.string()]);

export function mintPlanLineRefToJSON(
  mintPlanLineRef: MintPlanLineRef,
): string {
  return JSON.stringify(MintPlanLineRef$outboundSchema.parse(mintPlanLineRef));
}
