/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ReplacePrice = {
  /**
   * Unique identifier for a price
   */
  replacesPriceId: string;
  /**
   * Unique identifier for a price
   */
  withPriceId: string;
};

/**
 * A reference-by-id price diff applied to the prices of the plan's current version. Every id references an existing price created via POST /prices; inline price definitions are not accepted. An empty body copies the current prices into the new version unchanged. A version must carry at least one price, so a diff that would leave none is rejected.
 */
export type MintPlanVersionRequest = {
  /**
   * Prices to add to the version. Each must not already be on the plan's current version.
   */
  addPrices?: Array<string> | undefined;
  /**
   * Prices to remove. Each must be on the plan's current version.
   */
  removePrices?: Array<string> | undefined;
  /**
   * Prices to swap in place, preserving the slot's lineage so the price keeps its identity where the plan is configured for stable price ids. replacesPriceId must be on the plan's current version; withPriceId is the new price.
   */
  replacePrices?: Array<ReplacePrice> | undefined;
};

/** @internal */
export type ReplacePrice$Outbound = {
  replacesPriceId: string;
  withPriceId: string;
};

/** @internal */
export const ReplacePrice$outboundSchema: z.ZodType<
  ReplacePrice$Outbound,
  z.ZodTypeDef,
  ReplacePrice
> = z.object({
  replacesPriceId: z.string(),
  withPriceId: z.string(),
});

export function replacePriceToJSON(replacePrice: ReplacePrice): string {
  return JSON.stringify(ReplacePrice$outboundSchema.parse(replacePrice));
}

/** @internal */
export type MintPlanVersionRequest$Outbound = {
  addPrices?: Array<string> | undefined;
  removePrices?: Array<string> | undefined;
  replacePrices?: Array<ReplacePrice$Outbound> | undefined;
};

/** @internal */
export const MintPlanVersionRequest$outboundSchema: z.ZodType<
  MintPlanVersionRequest$Outbound,
  z.ZodTypeDef,
  MintPlanVersionRequest
> = z.object({
  addPrices: z.array(z.string()).optional(),
  removePrices: z.array(z.string()).optional(),
  replacePrices: z.array(z.lazy(() => ReplacePrice$outboundSchema)).optional(),
});

export function mintPlanVersionRequestToJSON(
  mintPlanVersionRequest: MintPlanVersionRequest,
): string {
  return JSON.stringify(
    MintPlanVersionRequest$outboundSchema.parse(mintPlanVersionRequest),
  );
}
