/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  MintPlanLineRef,
  MintPlanLineRef$Outbound,
  MintPlanLineRef$outboundSchema,
} from "./mintplanlineref.js";

/**
 * The price set the new version is to hold. Every price ID references an existing price created via POST /prices; inline price definitions are not accepted. The change against the plan's current version follows from the keys: a key on both sides with a different price ID replaces that line and keeps its identity, a key only in this request adds a line, and a key the current version holds and this request omits removes that line. An entry with no key adds a line under a generated key; it is never matched to an existing line by price ID. A version must carry at least one price, so an empty set is rejected.
 */
export type MintPlanVersionRequest = {
  /**
   * The full price set the new version holds. To move off the previous addPrices, removePrices and replacePrices fields: a replacePrices entry becomes the same key with the new price ID, a removePrices entry becomes an omitted key, and an addPrices entry becomes a new entry.
   */
  prices: Array<MintPlanLineRef>;
  /**
   * The ID of the plan version you read the current price set from. Supply it to be told when the plan has moved on: the request is rejected with 409 if the plan's current version is no longer this one, so a set built from a stale read cannot drop a line another caller has just added. Omit it to write the set unconditionally.
   */
  basedOnVersionId?: string | undefined;
};

/** @internal */
export type MintPlanVersionRequest$Outbound = {
  prices: Array<MintPlanLineRef$Outbound>;
  basedOnVersionId?: string | undefined;
};

/** @internal */
export const MintPlanVersionRequest$outboundSchema: z.ZodType<
  MintPlanVersionRequest$Outbound,
  z.ZodTypeDef,
  MintPlanVersionRequest
> = z.object({
  prices: z.array(MintPlanLineRef$outboundSchema),
  basedOnVersionId: z.string().optional(),
});

export function mintPlanVersionRequestToJSON(
  mintPlanVersionRequest: MintPlanVersionRequest,
): string {
  return JSON.stringify(
    MintPlanVersionRequest$outboundSchema.parse(mintPlanVersionRequest),
  );
}
