/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const OrderLineItemObject = {
  OrderLineItem: "order_line_item",
} as const;
export type OrderLineItemObject = ClosedEnum<typeof OrderLineItemObject>;

export type OrderLineItem = {
  id: string;
  object: OrderLineItemObject;
  orderId: string;
  itemId?: string | null | undefined;
  description?: string | null | undefined;
  /**
   * Decimal string
   */
  quantity: string;
  /**
   * Decimal string
   */
  listUnitPrice: string;
  /**
   * Decimal string
   */
  discountUnitAmount: string;
  /**
   * Decimal string
   */
  unitPrice: string;
  /**
   * Decimal string
   */
  totalPrice: string;
  termStartDate: Date | null;
  termEndDate: Date | null;
  metadata: { [k: string]: any };
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const OrderLineItemObject$inboundSchema: z.ZodNativeEnum<
  typeof OrderLineItemObject
> = z.nativeEnum(OrderLineItemObject);

/** @internal */
export const OrderLineItem$inboundSchema: z.ZodType<
  OrderLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: OrderLineItemObject$inboundSchema,
  orderId: z.string(),
  itemId: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  quantity: z.string(),
  listUnitPrice: z.string(),
  discountUnitAmount: z.string(),
  unitPrice: z.string(),
  totalPrice: z.string(),
  termStartDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  termEndDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  metadata: z.record(z.any()),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function orderLineItemFromJSON(
  jsonString: string,
): SafeParseResult<OrderLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderLineItem' from JSON`,
  );
}
