/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const PaymentObject = {
  Payment: "payment",
} as const;
export type PaymentObject = ClosedEnum<typeof PaymentObject>;

export type LineItem = {
  description?: string | undefined;
  amount?: string | undefined;
  quantity?: number | undefined;
};

/**
 * Current status of the payment.
 */
export const PaymentStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
/**
 * Current status of the payment.
 */
export type PaymentStatus = ClosedEnum<typeof PaymentStatus>;

export type Payment = {
  /**
   * Unique payment identifier (pay_* prefixed).
   */
  id: string;
  object: PaymentObject;
  /**
   * Payment amount in decimal format (e.g. '10.50').
   */
  amount: string;
  /**
   * ISO 4217 currency code (e.g. 'USD').
   */
  currency: string;
  /**
   * URL for the customer to complete the payment.
   */
  paymentUrl?: string | undefined;
  /**
   * Customer ID if provided.
   */
  customerId?: string | undefined;
  /**
   * Client-provided idempotency key.
   */
  idempotencyKey?: string | undefined;
  /**
   * Merchant-defined reference for this payment.
   */
  reference?: string | undefined;
  /**
   * Merchant-provided key-value metadata.
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * Breakdown of what the customer is being charged for.
   */
  lineItems?: Array<LineItem> | undefined;
  /**
   * Current status of the payment.
   */
  status: PaymentStatus;
  /**
   * When the payment expires.
   */
  expiresAt?: Date | undefined;
  /**
   * When the payment was created.
   */
  createdAt: Date;
};

/** @internal */
export const PaymentObject$inboundSchema: z.ZodNativeEnum<
  typeof PaymentObject
> = z.nativeEnum(PaymentObject);

/** @internal */
export const LineItem$inboundSchema: z.ZodType<
  LineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  amount: z.string().optional(),
  quantity: z.number().int().optional(),
});

export function lineItemFromJSON(
  jsonString: string,
): SafeParseResult<LineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineItem' from JSON`,
  );
}

/** @internal */
export const PaymentStatus$inboundSchema: z.ZodNativeEnum<
  typeof PaymentStatus
> = z.nativeEnum(PaymentStatus);

/** @internal */
export const Payment$inboundSchema: z.ZodType<Payment, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string(),
    object: PaymentObject$inboundSchema.default("payment"),
    amount: z.string(),
    currency: z.string(),
    paymentUrl: z.string().optional(),
    customerId: z.string().optional(),
    idempotencyKey: z.string().optional(),
    reference: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    lineItems: z.array(z.lazy(() => LineItem$inboundSchema)).optional(),
    status: PaymentStatus$inboundSchema,
    expiresAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  });

export function paymentFromJSON(
  jsonString: string,
): SafeParseResult<Payment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payment' from JSON`,
  );
}
