/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PlanVersionPriceSlot,
  PlanVersionPriceSlot$inboundSchema,
} from "./planversionpriceslot.js";

export const PlanVersionObject = {
  PlanVersion: "plan_version",
} as const;
export type PlanVersionObject = ClosedEnum<typeof PlanVersionObject>;

/**
 * Lifecycle status of the version.
 */
export const PlanVersionStatus = {
  Draft: "draft",
  Published: "published",
  Archived: "archived",
} as const;
/**
 * Lifecycle status of the version.
 */
export type PlanVersionStatus = ClosedEnum<typeof PlanVersionStatus>;

/**
 * A single plan version, including its price slots. Extends the list summary with the version's prices for draft review.
 */
export type PlanVersion = {
  /**
   * Unique identifier for a plan version
   */
  id: string;
  object: PlanVersionObject;
  /**
   * Monotonic version number within the plan, starting at 1.
   */
  versionNumber: number;
  /**
   * Lifecycle status of the version.
   */
  status: PlanVersionStatus;
  /**
   * When this version was published. Absent for draft versions.
   */
  publishedAt?: Date | undefined;
  /**
   * Whether this version is the plan's current default (live) version.
   */
  isDefault: boolean;
  /**
   * Number of committed-status subscriptions pinned to this version at creation time. Not a live-billing cohort.
   */
  subscriptionCount: number;
  /**
   * Unique identifier for a plan version
   */
  basedOnVersionId?: string | undefined;
  /**
   * When this version was last modified. Optimistic-concurrency token: read this value and echo it back as an `If-Match` header on a draft-price-mutation request to reject the write (412) if the draft changed since this read.
   */
  updatedAt: Date;
  /**
   * The price slots that make up this version.
   */
  prices: Array<PlanVersionPriceSlot>;
};

/** @internal */
export const PlanVersionObject$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionObject
> = z.nativeEnum(PlanVersionObject);

/** @internal */
export const PlanVersionStatus$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionStatus
> = z.nativeEnum(PlanVersionStatus);

/** @internal */
export const PlanVersion$inboundSchema: z.ZodType<
  PlanVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: PlanVersionObject$inboundSchema,
  versionNumber: z.number().int(),
  status: PlanVersionStatus$inboundSchema,
  publishedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  isDefault: z.boolean(),
  subscriptionCount: z.number().int(),
  basedOnVersionId: z.string().optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  prices: z.array(PlanVersionPriceSlot$inboundSchema),
});

export function planVersionFromJSON(
  jsonString: string,
): SafeParseResult<PlanVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanVersion' from JSON`,
  );
}
