/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * One line of a plan: the price it bills, and the key that names it.
 */
export type PlanLineInput = {
  /**
   * Unique identifier for a price
   */
  priceId: string;
  /**
   * The name you give one line of a plan, for example `platform_fee`. It starts with a lowercase letter or a digit, contains only lowercase letters, digits, hyphens and underscores, and is at most 64 characters. A key names one line for the life of the plan: every version that keeps the line carries the same key, and a key that you drop from one version and supply again on a later version says that the line resumed. Keys are compared exactly, so `Platform_Fee` is not accepted.
   */
  key?: string | undefined;
};

/** @internal */
export type PlanLineInput$Outbound = {
  priceId: string;
  key?: string | undefined;
};

/** @internal */
export const PlanLineInput$outboundSchema: z.ZodType<
  PlanLineInput$Outbound,
  z.ZodTypeDef,
  PlanLineInput
> = z.object({
  priceId: z.string(),
  key: z.string().optional(),
});

export function planLineInputToJSON(planLineInput: PlanLineInput): string {
  return JSON.stringify(PlanLineInput$outboundSchema.parse(planLineInput));
}
