/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PriceFeature, PriceFeature$inboundSchema } from "./pricefeature.js";
import { PriceTax, PriceTax$inboundSchema } from "./pricetax.js";

export const PlanVersionPriceSlotObject = {
  Price: "price",
} as const;
export type PlanVersionPriceSlotObject = ClosedEnum<
  typeof PlanVersionPriceSlotObject
>;

export const PlanVersionPriceSlotModel = {
  Standard: "standard",
  Dynamic: "dynamic",
  Volume: "volume",
  Percentage: "percentage",
} as const;
export type PlanVersionPriceSlotModel = ClosedEnum<
  typeof PlanVersionPriceSlotModel
>;

export const PlanVersionPriceSlotPaymentTerm = {
  InArrears: "in_arrears",
  InAdvance: "in_advance",
} as const;
export type PlanVersionPriceSlotPaymentTerm = ClosedEnum<
  typeof PlanVersionPriceSlotPaymentTerm
>;

/**
 * What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
 */
export const PlanVersionPriceSlotRateType = {
  Amount: "amount",
  Proportion: "proportion",
} as const;
/**
 * What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
 */
export type PlanVersionPriceSlotRateType = ClosedEnum<
  typeof PlanVersionPriceSlotRateType
>;

/**
 * One price slot on a plan version. Every `Price` field is present, plus `priceDeleted` layered on top.
 */
export type PlanVersionPriceSlot = {
  /**
   * Unique identifier for a price
   */
  id: string;
  object: PlanVersionPriceSlotObject;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  billableMetricId?: string | undefined;
  /**
   * The unique identifier for the fee referred to by this price
   */
  feeId?: string | undefined;
  /**
   * ISO 8601 duration for billing frequency (e.g., P1M for monthly)
   */
  billingCadence?: string | null | undefined;
  createdAt: Date;
  currency?: string | undefined;
  description?: string | undefined;
  invoiceDisplayName: string;
  model: PlanVersionPriceSlotModel;
  paymentTerm: PlanVersionPriceSlotPaymentTerm;
  properties: { [k: string]: any };
  unitAmount?: string | undefined;
  updatedAt: Date;
  /**
   * Features associated with this price
   */
  features?: Array<PriceFeature> | undefined;
  /**
   * When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
   */
  grantDiscountEnabled: boolean;
  /**
   * A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close.
   */
  isObligation: boolean;
  /**
   * What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
   */
  rateType: PlanVersionPriceSlotRateType;
  /**
   * Presentation only. Prices sharing this value, within one billing period, print as a single row on the rendered invoice PDF and are described by this string. Every member still bills its own line item on the ledger, this API and the compliance document. The combined row's rate is derived from the members' own rates. Requires the 'standard' pricing model. Sample values: 'Cross Border Fees', 'FX Fees'
   */
  invoiceDisplayGroup?: string | null | undefined;
  /**
   * Unique identifier for a pricing unit
   */
  pricingUnitId?: string | undefined;
  /**
   * A price's tax declaration. Optional on write — a price that declares nothing is `IN_SCOPE`, and is billed and taxed exactly as it was before this object existed. Always present on read. Replaced as a whole on update: send the object to change it, omit it to leave it alone.
   */
  tax: PriceTax;
  /**
   * Quantity used when generating invoice line items for this price. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1.
   */
  quantity: number;
  /**
   * True when the underlying price this slot references has been soft-deleted.
   */
  priceDeleted: boolean;
};

/** @internal */
export const PlanVersionPriceSlotObject$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionPriceSlotObject
> = z.nativeEnum(PlanVersionPriceSlotObject);

/** @internal */
export const PlanVersionPriceSlotModel$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionPriceSlotModel
> = z.nativeEnum(PlanVersionPriceSlotModel);

/** @internal */
export const PlanVersionPriceSlotPaymentTerm$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionPriceSlotPaymentTerm
> = z.nativeEnum(PlanVersionPriceSlotPaymentTerm);

/** @internal */
export const PlanVersionPriceSlotRateType$inboundSchema: z.ZodNativeEnum<
  typeof PlanVersionPriceSlotRateType
> = z.nativeEnum(PlanVersionPriceSlotRateType);

/** @internal */
export const PlanVersionPriceSlot$inboundSchema: z.ZodType<
  PlanVersionPriceSlot,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: PlanVersionPriceSlotObject$inboundSchema.default("price"),
  merchantId: z.string(),
  billableMetricId: z.string().optional(),
  feeId: z.string().optional(),
  billingCadence: z.nullable(z.string()).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  currency: z.string().optional(),
  description: z.string().optional(),
  invoiceDisplayName: z.string(),
  model: PlanVersionPriceSlotModel$inboundSchema,
  paymentTerm: PlanVersionPriceSlotPaymentTerm$inboundSchema,
  properties: z.record(z.any()),
  unitAmount: z.string().optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  features: z.array(PriceFeature$inboundSchema).optional(),
  grantDiscountEnabled: z.boolean().default(false),
  isObligation: z.boolean().default(false),
  rateType: PlanVersionPriceSlotRateType$inboundSchema.default("amount"),
  invoiceDisplayGroup: z.nullable(z.string()).optional(),
  pricingUnitId: z.string().optional(),
  tax: PriceTax$inboundSchema,
  quantity: z.number().int().default(1),
  priceDeleted: z.boolean(),
});

export function planVersionPriceSlotFromJSON(
  jsonString: string,
): SafeParseResult<PlanVersionPriceSlot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanVersionPriceSlot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanVersionPriceSlot' from JSON`,
  );
}
