/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Percentage pricing model
 */
export type PercentagePriceProperties = {
  /**
   * Ceiling amount limiting total charge regardless of percentage calculation. Sample values: '500.00' caps fees at $500 maximum, '2000.00' limits charges to $2000 per period
   */
  maxCharge: string;
  /**
   * Floor amount charged regardless of percentage calculation. Sample values: '5.00' ensures minimum $5 fee, '25.00' guarantees at least $25 per billing event
   */
  minCharge: string;
  /**
   * Rate expressed as decimal between 0 and 10, supporting up to 4 decimal precision. Sample values: '0.03' represents 3%, '0.075' represents 7.5%, '1.10' represents 110%
   */
  percentage: string;
};

export type VolumeTier = {
  /**
   * Inclusive upper bound of the band, as a decimal string. Null on the last band only, which carries the remainder. Sample values: '100' bounds the band at 100 units, null leaves the top open.
   */
  upTo: string | null;
  /**
   * Per-unit cost inside this band, as a decimal string, capped at 6 decimal places. Sample values: '5' represents $5 per unit, '0.004' represents $0.004 per unit.
   */
  unitPrice: string;
};

/**
 * Volume pricing model
 */
export type VolumePriceProperties = {
  /**
   * Ordered ladder of bands. The band is selected by the period's total metered usage, and its rate applies to every billed unit. A band matches when the quantity is less than or equal to its `upTo`, and the first matching band wins; the previous band's `upTo` is the exclusive lower bound, and the first band's floor is 0.
   */
  tiers: Array<VolumeTier>;
};

/**
 * Dynamic pricing model
 */
export type DynamicPriceProperties = {
  /**
   * Upper limit of the price range for dynamic pricing. Sample values: '0.10' means $0.10 per token for large volumes at peak times
   */
  maxPrice: string;
  /**
   * Lower limit of the price range for dynamic pricing. Sample values: '0.01' means $0.01 per token for low volumes during off-peak hours
   */
  minPrice: string;
};

/**
 * Standard pricing model
 */
export type StandardPriceProperties = {
  /**
   * Per-unit cost in decimal format for fixed-rate pricing. Sample values: '0.00002' represents $0.00002 per token, '0.15' represents $0.15 per gigabyte stored, '0.05' represents $0.05 per API call. Per unit. Total per period = quantity × unitPrice; see the `quantity` field. A negative value defines a usage-scaled rebate: the line's subtotal is negative and reduces the invoice. A rebate never drives an invoice total below zero, so set rebate rates below the charges they offset. A negative unitPrice is only valid on a metered price (a billableMetricId is required — there is no usage to scale on a fee price) and cannot be combined with grantDiscountEnabled, a hard-limit feature, or a pricingUnitId. When a rebate and a charge price share a billable metric but attach to different features, they compute against different quantity bases: a price attached to a feature bills the overage against its allowance, while a featureless price bills the raw metered usage. That is a permitted configuration, not an error. Attach both to the same feature to bill them against one basis.
   */
  unitPrice: string;
};

export type PriceProperties =
  | PercentagePriceProperties
  | DynamicPriceProperties
  | StandardPriceProperties
  | VolumePriceProperties;

/** @internal */
export const PercentagePriceProperties$inboundSchema: z.ZodType<
  PercentagePriceProperties,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxCharge: z.string(),
  minCharge: z.string(),
  percentage: z.string(),
});
/** @internal */
export type PercentagePriceProperties$Outbound = {
  maxCharge: string;
  minCharge: string;
  percentage: string;
};

/** @internal */
export const PercentagePriceProperties$outboundSchema: z.ZodType<
  PercentagePriceProperties$Outbound,
  z.ZodTypeDef,
  PercentagePriceProperties
> = z.object({
  maxCharge: z.string(),
  minCharge: z.string(),
  percentage: z.string(),
});

export function percentagePricePropertiesToJSON(
  percentagePriceProperties: PercentagePriceProperties,
): string {
  return JSON.stringify(
    PercentagePriceProperties$outboundSchema.parse(percentagePriceProperties),
  );
}
export function percentagePricePropertiesFromJSON(
  jsonString: string,
): SafeParseResult<PercentagePriceProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PercentagePriceProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PercentagePriceProperties' from JSON`,
  );
}

/** @internal */
export const VolumeTier$inboundSchema: z.ZodType<
  VolumeTier,
  z.ZodTypeDef,
  unknown
> = z.object({
  upTo: z.nullable(z.string()),
  unitPrice: z.string(),
});
/** @internal */
export type VolumeTier$Outbound = {
  upTo: string | null;
  unitPrice: string;
};

/** @internal */
export const VolumeTier$outboundSchema: z.ZodType<
  VolumeTier$Outbound,
  z.ZodTypeDef,
  VolumeTier
> = z.object({
  upTo: z.nullable(z.string()),
  unitPrice: z.string(),
});

export function volumeTierToJSON(volumeTier: VolumeTier): string {
  return JSON.stringify(VolumeTier$outboundSchema.parse(volumeTier));
}
export function volumeTierFromJSON(
  jsonString: string,
): SafeParseResult<VolumeTier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VolumeTier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VolumeTier' from JSON`,
  );
}

/** @internal */
export const VolumePriceProperties$inboundSchema: z.ZodType<
  VolumePriceProperties,
  z.ZodTypeDef,
  unknown
> = z.object({
  tiers: z.array(z.lazy(() => VolumeTier$inboundSchema)),
});
/** @internal */
export type VolumePriceProperties$Outbound = {
  tiers: Array<VolumeTier$Outbound>;
};

/** @internal */
export const VolumePriceProperties$outboundSchema: z.ZodType<
  VolumePriceProperties$Outbound,
  z.ZodTypeDef,
  VolumePriceProperties
> = z.object({
  tiers: z.array(z.lazy(() => VolumeTier$outboundSchema)),
});

export function volumePricePropertiesToJSON(
  volumePriceProperties: VolumePriceProperties,
): string {
  return JSON.stringify(
    VolumePriceProperties$outboundSchema.parse(volumePriceProperties),
  );
}
export function volumePricePropertiesFromJSON(
  jsonString: string,
): SafeParseResult<VolumePriceProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VolumePriceProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VolumePriceProperties' from JSON`,
  );
}

/** @internal */
export const DynamicPriceProperties$inboundSchema: z.ZodType<
  DynamicPriceProperties,
  z.ZodTypeDef,
  unknown
> = z.object({
  maxPrice: z.string(),
  minPrice: z.string(),
});
/** @internal */
export type DynamicPriceProperties$Outbound = {
  maxPrice: string;
  minPrice: string;
};

/** @internal */
export const DynamicPriceProperties$outboundSchema: z.ZodType<
  DynamicPriceProperties$Outbound,
  z.ZodTypeDef,
  DynamicPriceProperties
> = z.object({
  maxPrice: z.string(),
  minPrice: z.string(),
});

export function dynamicPricePropertiesToJSON(
  dynamicPriceProperties: DynamicPriceProperties,
): string {
  return JSON.stringify(
    DynamicPriceProperties$outboundSchema.parse(dynamicPriceProperties),
  );
}
export function dynamicPricePropertiesFromJSON(
  jsonString: string,
): SafeParseResult<DynamicPriceProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamicPriceProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamicPriceProperties' from JSON`,
  );
}

/** @internal */
export const StandardPriceProperties$inboundSchema: z.ZodType<
  StandardPriceProperties,
  z.ZodTypeDef,
  unknown
> = z.object({
  unitPrice: z.string(),
});
/** @internal */
export type StandardPriceProperties$Outbound = {
  unitPrice: string;
};

/** @internal */
export const StandardPriceProperties$outboundSchema: z.ZodType<
  StandardPriceProperties$Outbound,
  z.ZodTypeDef,
  StandardPriceProperties
> = z.object({
  unitPrice: z.string(),
});

export function standardPricePropertiesToJSON(
  standardPriceProperties: StandardPriceProperties,
): string {
  return JSON.stringify(
    StandardPriceProperties$outboundSchema.parse(standardPriceProperties),
  );
}
export function standardPricePropertiesFromJSON(
  jsonString: string,
): SafeParseResult<StandardPriceProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StandardPriceProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StandardPriceProperties' from JSON`,
  );
}

/** @internal */
export const PriceProperties$inboundSchema: z.ZodType<
  PriceProperties,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PercentagePriceProperties$inboundSchema),
  z.lazy(() => DynamicPriceProperties$inboundSchema),
  z.lazy(() => StandardPriceProperties$inboundSchema),
  z.lazy(() => VolumePriceProperties$inboundSchema),
]);
/** @internal */
export type PriceProperties$Outbound =
  | PercentagePriceProperties$Outbound
  | DynamicPriceProperties$Outbound
  | StandardPriceProperties$Outbound
  | VolumePriceProperties$Outbound;

/** @internal */
export const PriceProperties$outboundSchema: z.ZodType<
  PriceProperties$Outbound,
  z.ZodTypeDef,
  PriceProperties
> = z.union([
  z.lazy(() => PercentagePriceProperties$outboundSchema),
  z.lazy(() => DynamicPriceProperties$outboundSchema),
  z.lazy(() => StandardPriceProperties$outboundSchema),
  z.lazy(() => VolumePriceProperties$outboundSchema),
]);

export function pricePropertiesToJSON(
  priceProperties: PriceProperties,
): string {
  return JSON.stringify(PriceProperties$outboundSchema.parse(priceProperties));
}
export function pricePropertiesFromJSON(
  jsonString: string,
): SafeParseResult<PriceProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceProperties' from JSON`,
  );
}
