/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const PriceFeatureType = {
  Metered: "metered",
  Static: "static",
  Boolean: "boolean",
} as const;
export type PriceFeatureType = ClosedEnum<typeof PriceFeatureType>;

export type PriceFeatureFeature = {
  key?: string | undefined;
  name?: string | undefined;
  type?: PriceFeatureType | undefined;
};

export type PriceFeature = {
  id: string;
  featureId: string;
  entitlementTemplate: { [k: string]: any };
  feature?: PriceFeatureFeature | undefined;
};

/** @internal */
export const PriceFeatureType$inboundSchema: z.ZodNativeEnum<
  typeof PriceFeatureType
> = z.nativeEnum(PriceFeatureType);

/** @internal */
export const PriceFeatureFeature$inboundSchema: z.ZodType<
  PriceFeatureFeature,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string().optional(),
  name: z.string().optional(),
  type: PriceFeatureType$inboundSchema.optional(),
});

export function priceFeatureFeatureFromJSON(
  jsonString: string,
): SafeParseResult<PriceFeatureFeature, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceFeatureFeature$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceFeatureFeature' from JSON`,
  );
}

/** @internal */
export const PriceFeature$inboundSchema: z.ZodType<
  PriceFeature,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  featureId: z.string(),
  entitlementTemplate: z.record(z.any()),
  feature: z.lazy(() => PriceFeatureFeature$inboundSchema).optional(),
});

export function priceFeatureFromJSON(
  jsonString: string,
): SafeParseResult<PriceFeature, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceFeature$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceFeature' from JSON`,
  );
}
