/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PriceFeature, PriceFeature$inboundSchema } from "./pricefeature.js";

export const PriceObject = {
  Price: "price",
} as const;
export type PriceObject = ClosedEnum<typeof PriceObject>;

export const PriceModel = {
  Standard: "standard",
  Dynamic: "dynamic",
  Volume: "volume",
  Percentage: "percentage",
} as const;
export type PriceModel = ClosedEnum<typeof PriceModel>;

export const PricePaymentTerm = {
  Instant: "instant",
  InArrears: "in_arrears",
  InAdvance: "in_advance",
} as const;
export type PricePaymentTerm = ClosedEnum<typeof PricePaymentTerm>;

export type Price = {
  /**
   * Unique identifier for a price
   */
  id: string;
  object: PriceObject;
  billableMetricId?: string | undefined;
  /**
   * The unique identifier for the fee referred to by this price
   */
  feeId?: string | undefined;
  /**
   * ISO 8601 duration for billing frequency (e.g., P1M for monthly)
   */
  billingCadence?: string | null | undefined;
  createdAt: Date;
  currency?: string | undefined;
  description?: string | undefined;
  invoiceDisplayName: string;
  model: PriceModel;
  paymentTerm: PricePaymentTerm;
  properties: { [k: string]: any };
  unitAmount?: string | undefined;
  updatedAt: Date;
  /**
   * Features associated with this price
   */
  features?: Array<PriceFeature> | undefined;
};

/** @internal */
export const PriceObject$inboundSchema: z.ZodNativeEnum<typeof PriceObject> = z
  .nativeEnum(PriceObject);

/** @internal */
export const PriceModel$inboundSchema: z.ZodNativeEnum<typeof PriceModel> = z
  .nativeEnum(PriceModel);

/** @internal */
export const PricePaymentTerm$inboundSchema: z.ZodNativeEnum<
  typeof PricePaymentTerm
> = z.nativeEnum(PricePaymentTerm);

/** @internal */
export const Price$inboundSchema: z.ZodType<Price, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    object: PriceObject$inboundSchema.default("price"),
    billableMetricId: z.string().optional(),
    feeId: z.string().optional(),
    billingCadence: z.nullable(z.string()).optional(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    currency: z.string().optional(),
    description: z.string().optional(),
    invoiceDisplayName: z.string(),
    model: PriceModel$inboundSchema,
    paymentTerm: PricePaymentTerm$inboundSchema,
    properties: z.record(z.any()),
    unitAmount: z.string().optional(),
    updatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    features: z.array(PriceFeature$inboundSchema).optional(),
  });

export function priceFromJSON(
  jsonString: string,
): SafeParseResult<Price, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Price$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Price' from JSON`,
  );
}
