/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Whether this price's money is consideration for a supply — the one tax fact only you can state, because it is settled when you agree the deal rather than derived from what was sold. `IN_SCOPE` (the default) is consideration: it enters the taxable amount, positive as a charge or negative as a reduction in the price of the supply it applies to. `OUTSIDE_SCOPE` money is not consideration for anything, so it does not change the taxable amount, carries no tax, does not appear on the tax document, and nets into the amount payable after tax. This means "not consideration for a supply" — it does NOT mean "a supply outside this jurisdiction": exports and place-of-supply answers are worked out from the addresses on the sale by the tax provider, and are never declared on a price. How a supply is then classified — standard, zero-rated, exempt — is the tax provider's determination and is not set here either. Omit the whole `tax` object to leave a price in scope; there is deliberately no schema default on this property, so that a misspelt key is refused rather than silently defaulted.
 */
export const SupplyScope = {
  InScope: "IN_SCOPE",
  OutsideScope: "OUTSIDE_SCOPE",
} as const;
/**
 * Whether this price's money is consideration for a supply — the one tax fact only you can state, because it is settled when you agree the deal rather than derived from what was sold. `IN_SCOPE` (the default) is consideration: it enters the taxable amount, positive as a charge or negative as a reduction in the price of the supply it applies to. `OUTSIDE_SCOPE` money is not consideration for anything, so it does not change the taxable amount, carries no tax, does not appear on the tax document, and nets into the amount payable after tax. This means "not consideration for a supply" — it does NOT mean "a supply outside this jurisdiction": exports and place-of-supply answers are worked out from the addresses on the sale by the tax provider, and are never declared on a price. How a supply is then classified — standard, zero-rated, exempt — is the tax provider's determination and is not set here either. Omit the whole `tax` object to leave a price in scope; there is deliberately no schema default on this property, so that a misspelt key is refused rather than silently defaulted.
 */
export type SupplyScope = ClosedEnum<typeof SupplyScope>;

/**
 * What an `OUTSIDE_SCOPE` amount is called in the invoice totals, so the wording follows the declaration rather than being retyped per price. Required when `supplyScope` is `OUTSIDE_SCOPE`, and rejected otherwise. `CASHBACK` is the only value today, and a price declaring it must use the `standard` model and must not carry a positive `unitPrice` — a cashback is money paid back, not charged.
 */
export const OutsideScopeLabel = {
  Cashback: "CASHBACK",
} as const;
/**
 * What an `OUTSIDE_SCOPE` amount is called in the invoice totals, so the wording follows the declaration rather than being retyped per price. Required when `supplyScope` is `OUTSIDE_SCOPE`, and rejected otherwise. `CASHBACK` is the only value today, and a price declaring it must use the `standard` model and must not carry a positive `unitPrice` — a cashback is money paid back, not charged.
 */
export type OutsideScopeLabel = ClosedEnum<typeof OutsideScopeLabel>;

/**
 * A price's tax declaration. Optional on write — a price that declares nothing is `IN_SCOPE`, and is billed and taxed exactly as it was before this object existed. Always present on read. Replaced as a whole on update: send the object to change it, omit it to leave it alone.
 */
export type PriceTax = {
  /**
   * Whether this price's money is consideration for a supply — the one tax fact only you can state, because it is settled when you agree the deal rather than derived from what was sold. `IN_SCOPE` (the default) is consideration: it enters the taxable amount, positive as a charge or negative as a reduction in the price of the supply it applies to. `OUTSIDE_SCOPE` money is not consideration for anything, so it does not change the taxable amount, carries no tax, does not appear on the tax document, and nets into the amount payable after tax. This means "not consideration for a supply" — it does NOT mean "a supply outside this jurisdiction": exports and place-of-supply answers are worked out from the addresses on the sale by the tax provider, and are never declared on a price. How a supply is then classified — standard, zero-rated, exempt — is the tax provider's determination and is not set here either. Omit the whole `tax` object to leave a price in scope; there is deliberately no schema default on this property, so that a misspelt key is refused rather than silently defaulted.
   */
  supplyScope: SupplyScope;
  /**
   * What an `OUTSIDE_SCOPE` amount is called in the invoice totals, so the wording follows the declaration rather than being retyped per price. Required when `supplyScope` is `OUTSIDE_SCOPE`, and rejected otherwise. `CASHBACK` is the only value today, and a price declaring it must use the `standard` model and must not carry a positive `unitPrice` — a cashback is money paid back, not charged.
   */
  outsideScopeLabel?: OutsideScopeLabel | null | undefined;
};

/** @internal */
export const SupplyScope$inboundSchema: z.ZodNativeEnum<typeof SupplyScope> = z
  .nativeEnum(SupplyScope);
/** @internal */
export const SupplyScope$outboundSchema: z.ZodNativeEnum<typeof SupplyScope> =
  SupplyScope$inboundSchema;

/** @internal */
export const OutsideScopeLabel$inboundSchema: z.ZodNativeEnum<
  typeof OutsideScopeLabel
> = z.nativeEnum(OutsideScopeLabel);
/** @internal */
export const OutsideScopeLabel$outboundSchema: z.ZodNativeEnum<
  typeof OutsideScopeLabel
> = OutsideScopeLabel$inboundSchema;

/** @internal */
export const PriceTax$inboundSchema: z.ZodType<
  PriceTax,
  z.ZodTypeDef,
  unknown
> = z.object({
  supplyScope: SupplyScope$inboundSchema,
  outsideScopeLabel: z.nullable(OutsideScopeLabel$inboundSchema).optional(),
});
/** @internal */
export type PriceTax$Outbound = {
  supplyScope: string;
  outsideScopeLabel?: string | null | undefined;
};

/** @internal */
export const PriceTax$outboundSchema: z.ZodType<
  PriceTax$Outbound,
  z.ZodTypeDef,
  PriceTax
> = z.object({
  supplyScope: SupplyScope$outboundSchema,
  outsideScopeLabel: z.nullable(OutsideScopeLabel$outboundSchema).optional(),
});

export function priceTaxToJSON(priceTax: PriceTax): string {
  return JSON.stringify(PriceTax$outboundSchema.parse(priceTax));
}
export function priceTaxFromJSON(
  jsonString: string,
): SafeParseResult<PriceTax, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceTax$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceTax' from JSON`,
  );
}
