/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProfitabilityRow,
  ProfitabilityRow$inboundSchema,
} from "./profitabilityrow.js";

/**
 * Where the caller's revenue actually lies in time. Scoped by the same filters as the request (merchant, and where given customer, subscription and currency), so it is not an account-wide statement. Present only when the selected range returned nothing. An object carries the bounds of the real revenue; null means no revenue under these filters at any time; an absent field means the extent was not resolved, because the result was not empty or because the lookup failed. An absent field must never be read as an absence. The bounds may span more than this endpoint's maximum queryable range, so clamp before re-querying.
 */
export type ProfitabilitySummaryResponseRevenueRange = {
  /**
   * Earliest invoice issue instant.
   */
  from: Date;
  /**
   * Latest invoice issue instant.
   */
  to: Date;
};

/**
 * Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence.
 */
export type ProfitabilitySummaryResponseCostRange = {
  /**
   * Earliest cost event instant.
   */
  from: Date;
  /**
   * Latest cost event instant.
   */
  to: Date;
};

export type ProfitabilitySummaryResponse = {
  /**
   * Object type identifier
   */
  object: "profitability_summary";
  /**
   * ISO 4217 currency code applied to revenue and cost values
   */
  currency: string;
  /**
   * Top-N customer rows by profit descending, optionally followed by a single 'Other' row when more than topN customers contributed.
   */
  rows: Array<ProfitabilityRow>;
  /**
   * Non-fatal warnings collected during cost discovery (e.g. an individual cost query failed). Empty array on a clean run.
   */
  warnings?: Array<string> | undefined;
  /**
   * Where the caller's revenue actually lies in time. Scoped by the same filters as the request (merchant, and where given customer, subscription and currency), so it is not an account-wide statement. Present only when the selected range returned nothing. An object carries the bounds of the real revenue; null means no revenue under these filters at any time; an absent field means the extent was not resolved, because the result was not empty or because the lookup failed. An absent field must never be read as an absence. The bounds may span more than this endpoint's maximum queryable range, so clamp before re-querying.
   */
  revenueRange?: ProfitabilitySummaryResponseRevenueRange | null | undefined;
  /**
   * Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence.
   */
  costRange?: ProfitabilitySummaryResponseCostRange | null | undefined;
};

/** @internal */
export const ProfitabilitySummaryResponseRevenueRange$inboundSchema: z.ZodType<
  ProfitabilitySummaryResponseRevenueRange,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  to: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function profitabilitySummaryResponseRevenueRangeFromJSON(
  jsonString: string,
): SafeParseResult<
  ProfitabilitySummaryResponseRevenueRange,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ProfitabilitySummaryResponseRevenueRange$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ProfitabilitySummaryResponseRevenueRange' from JSON`,
  );
}

/** @internal */
export const ProfitabilitySummaryResponseCostRange$inboundSchema: z.ZodType<
  ProfitabilitySummaryResponseCostRange,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  to: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function profitabilitySummaryResponseCostRangeFromJSON(
  jsonString: string,
): SafeParseResult<ProfitabilitySummaryResponseCostRange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ProfitabilitySummaryResponseCostRange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfitabilitySummaryResponseCostRange' from JSON`,
  );
}

/** @internal */
export const ProfitabilitySummaryResponse$inboundSchema: z.ZodType<
  ProfitabilitySummaryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.literal("profitability_summary"),
  currency: z.string(),
  rows: z.array(ProfitabilityRow$inboundSchema),
  warnings: z.array(z.string()).optional(),
  revenueRange: z.nullable(
    z.lazy(() => ProfitabilitySummaryResponseRevenueRange$inboundSchema),
  ).optional(),
  costRange: z.nullable(
    z.lazy(() => ProfitabilitySummaryResponseCostRange$inboundSchema),
  ).optional(),
});

export function profitabilitySummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProfitabilitySummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfitabilitySummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfitabilitySummaryResponse' from JSON`,
  );
}
