/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProfitabilityTrend,
  ProfitabilityTrend$inboundSchema,
} from "./profitabilitytrend.js";

export type ProfitabilityRow = {
  /**
   * Customer ID, or the literal 'other' for the overflow row.
   */
  customerId: string;
  /**
   * Display name for the row. 'Other' for the overflow row.
   */
  customerName: string;
  /**
   * Net revenue (paid + outstanding) in unit currency, with two decimals.
   */
  netRevenue: string;
  /**
   * Aggregated cost in unit currency, with two decimals.
   */
  totalCost: string;
  /**
   * Profit (revenue − cost) in unit currency, with two decimals. May be negative.
   */
  profit: string;
  /**
   * Margin percent (profit / revenue × 100), with two decimals. Null when revenue is zero.
   */
  marginPct: string | null;
  /**
   * Per-customer revenue trend over the period. Null for the 'Other' row and when there's insufficient data.
   */
  trend: ProfitabilityTrend | null;
};

/** @internal */
export const ProfitabilityRow$inboundSchema: z.ZodType<
  ProfitabilityRow,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string(),
  customerName: z.string(),
  netRevenue: z.string(),
  totalCost: z.string(),
  profit: z.string(),
  marginPct: z.nullable(z.string()),
  trend: z.nullable(ProfitabilityTrend$inboundSchema),
});

export function profitabilityRowFromJSON(
  jsonString: string,
): SafeParseResult<ProfitabilityRow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfitabilityRow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfitabilityRow' from JSON`,
  );
}
