/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const PurchaseGrantResponseObject = {
  GrantPurchase: "grant_purchase",
} as const;
export type PurchaseGrantResponseObject = ClosedEnum<
  typeof PurchaseGrantResponseObject
>;

export type PaymentSession = {
  /**
   * The Stripe checkout URL for the customer to complete payment.
   */
  url: string;
  /**
   * When the payment session expires.
   */
  expiresAt?: Date | null | undefined;
  /**
   * The payment amount in the currency's minor unit (e.g., cents).
   */
  amount?: number | undefined;
};

export type PurchaseGrantResponse = {
  object: PurchaseGrantResponseObject;
  /**
   * The invoice ID for this grant purchase.
   */
  invoiceId: string;
  /**
   * The entitlement that will receive the grant.
   */
  entitlementId: string;
  /**
   * The number of credits that will be granted on payment.
   */
  grantAmount: number;
  /**
   * The price in decimal format (e.g., '5.00').
   */
  price: string;
  /**
   * The three-letter ISO 4217 currency code (e.g., 'usd').
   */
  currency: string;
  /**
   * Payment session(s) for the customer to complete the purchase.
   */
  paymentSessions: Array<PaymentSession>;
};

/** @internal */
export const PurchaseGrantResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof PurchaseGrantResponseObject
> = z.nativeEnum(PurchaseGrantResponseObject);

/** @internal */
export const PaymentSession$inboundSchema: z.ZodType<
  PaymentSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  expiresAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  amount: z.number().optional(),
});

export function paymentSessionFromJSON(
  jsonString: string,
): SafeParseResult<PaymentSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentSession' from JSON`,
  );
}

/** @internal */
export const PurchaseGrantResponse$inboundSchema: z.ZodType<
  PurchaseGrantResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: PurchaseGrantResponseObject$inboundSchema.default("grant_purchase"),
  invoiceId: z.string(),
  entitlementId: z.string(),
  grantAmount: z.number().int(),
  price: z.string(),
  currency: z.string(),
  paymentSessions: z.array(z.lazy(() => PaymentSession$inboundSchema)),
});

export function purchaseGrantResponseFromJSON(
  jsonString: string,
): SafeParseResult<PurchaseGrantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PurchaseGrantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PurchaseGrantResponse' from JSON`,
  );
}
