/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PurchaseGrantRequest = {
  /**
   * The number of credits to grant upon payment completion.
   */
  amount: number;
  /**
   * The price in decimal format (e.g., '5.00' for $5.00 USD). Must be at least $0.50.
   */
  price: string;
  /**
   * Caller-provided deduplication key. Retrying with the same key returns the existing invoice.
   */
  idempotencyKey: string;
  /**
   * When the grant becomes effective. Defaults to now.
   */
  effectiveAt?: Date | undefined;
  /**
   * When the grant expires. If omitted, the grant does not expire.
   */
  expiresAt?: Date | null | undefined;
  /**
   * URL to redirect the customer to after successful payment.
   */
  successUrl?: string | undefined;
  /**
   * URL to redirect the customer to if payment is cancelled.
   */
  cancelUrl?: string | undefined;
  /**
   * When the payment session expires. If omitted, uses the default expiry.
   */
  paymentExpiresAt?: Date | undefined;
};

/** @internal */
export type PurchaseGrantRequest$Outbound = {
  amount: number;
  price: string;
  idempotencyKey: string;
  effectiveAt?: string | undefined;
  expiresAt?: string | null | undefined;
  successUrl?: string | undefined;
  cancelUrl?: string | undefined;
  paymentExpiresAt?: string | undefined;
};

/** @internal */
export const PurchaseGrantRequest$outboundSchema: z.ZodType<
  PurchaseGrantRequest$Outbound,
  z.ZodTypeDef,
  PurchaseGrantRequest
> = z.object({
  amount: z.number(),
  price: z.string(),
  idempotencyKey: z.string(),
  effectiveAt: z.date().transform(v => v.toISOString()).optional(),
  expiresAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  successUrl: z.string().optional(),
  cancelUrl: z.string().optional(),
  paymentExpiresAt: z.date().transform(v => v.toISOString()).optional(),
});

export function purchaseGrantRequestToJSON(
  purchaseGrantRequest: PurchaseGrantRequest,
): string {
  return JSON.stringify(
    PurchaseGrantRequest$outboundSchema.parse(purchaseGrantRequest),
  );
}
