/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ExternalReference,
  ExternalReference$inboundSchema,
} from "./externalreference.js";

/**
 * An item a line was tagged with, together with its external accounting/tax codes. Deliberately narrower than the /v0/items Item resource: it carries what is needed to translate a line into a GL/SKU code, not the full record.
 */
export type ResolvedItem = {
  /**
   * Unique identifier for an item
   */
  id: string;
  /**
   * Human-readable item name
   */
  name: string;
  /**
   * The product this item belongs to, for grouping lines by product
   */
  catalogId: string | null;
  /**
   * When this item was retired from the catalog. Archived items still resolve here — invoices that already reference them have to keep resolving — but cannot be tagged onto new pricing. Null while active.
   */
  archivedAt: Date | null;
  /**
   * The item's external codes, narrowed to the requested provider when one is given. An empty list means the item is not yet mapped for that provider — an actionable state, not an error. More than one may be returned for a single provider, and more than one of those may carry `isPrimary: true`: the uniqueness constraint runs the other way round (an external id is the primary reference of at most one item per merchant), so it does not reduce an item's references to one per provider. Entries are ordered newest first, tie-broken by id, so the order is stable across reads — but a consumer that needs exactly one code must choose deliberately rather than assume there is only one.
   */
  externalReferences: Array<ExternalReference>;
};

/** @internal */
export const ResolvedItem$inboundSchema: z.ZodType<
  ResolvedItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  catalogId: z.nullable(z.string()),
  archivedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  externalReferences: z.array(ExternalReference$inboundSchema),
});

export function resolvedItemFromJSON(
  jsonString: string,
): SafeParseResult<ResolvedItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResolvedItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResolvedItem' from JSON`,
  );
}
