/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CurrencyBreakdownEntry,
  CurrencyBreakdownEntry$inboundSchema,
} from "./currencybreakdownentry.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  GroupInvoiceSummary,
  GroupInvoiceSummary$inboundSchema,
} from "./groupinvoicesummary.js";
import {
  InvoiceSummary,
  InvoiceSummary$inboundSchema,
} from "./invoicesummary.js";
import {
  PaymentSummary,
  PaymentSummary$inboundSchema,
} from "./paymentsummary.js";
import {
  RevenueTrendBucket,
  RevenueTrendBucket$inboundSchema,
} from "./revenuetrendbucket.js";

export type RevenueSummaryResponse = {
  /**
   * Object type identifier
   */
  object: "revenue_summary";
  /**
   * Net collected revenue in dollars (paid invoices + completed payments). Omitted when groupBy=currency is active.
   */
  netRevenue?: string | undefined;
  invoices?: InvoiceSummary | undefined;
  payments?: PaymentSummary | undefined;
  /**
   * Time-bucketed revenue trend data. Omitted when groupBy=currency is active.
   */
  trend?: Array<RevenueTrendBucket> | undefined;
  /**
   * Invoice breakdown by group dimension (only present when groupBy=plan or groupBy=customer is specified)
   */
  groupBreakdown?: Array<GroupInvoiceSummary> | undefined;
  /**
   * Per-currency revenue aggregates (only present when groupBy=currency is specified). Primary currency appears first, then alphabetical by ISO code. When present, top-level netRevenue, invoices, payments, and trend fields are omitted.
   */
  currencyBreakdown?: Array<CurrencyBreakdownEntry> | undefined;
};

/** @internal */
export const RevenueSummaryResponse$inboundSchema: z.ZodType<
  RevenueSummaryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.literal("revenue_summary"),
  netRevenue: z.string().optional(),
  invoices: InvoiceSummary$inboundSchema.optional(),
  payments: PaymentSummary$inboundSchema.optional(),
  trend: z.array(RevenueTrendBucket$inboundSchema).optional(),
  groupBreakdown: z.array(GroupInvoiceSummary$inboundSchema).optional(),
  currencyBreakdown: z.array(CurrencyBreakdownEntry$inboundSchema).optional(),
});

export function revenueSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevenueSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevenueSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevenueSummaryResponse' from JSON`,
  );
}
