/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RevenueStats = {
  /**
   * Revenue from usage charges in dollars
   */
  usageRevenue?: string | undefined;
  /**
   * Revenue from fee charges in dollars
   */
  feeRevenue?: string | undefined;
  /**
   * Total refund amount in dollars
   */
  refundAmount?: string | undefined;
  /**
   * Net revenue in dollars (usage + fees - refunds)
   */
  netRevenue?: string | undefined;
  /**
   * Number of usage charge events
   */
  usageCount?: number | undefined;
  /**
   * Number of fee charge events
   */
  feeCount?: number | undefined;
  /**
   * Number of usage refund events
   */
  usageRefundCount?: number | undefined;
  /**
   * Number of fee refund events
   */
  feeRefundCount?: number | undefined;
};

/** @internal */
export const RevenueStats$inboundSchema: z.ZodType<
  RevenueStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  usageRevenue: z.string().optional(),
  feeRevenue: z.string().optional(),
  refundAmount: z.string().optional(),
  netRevenue: z.string().optional(),
  usageCount: z.number().int().optional(),
  feeCount: z.number().int().optional(),
  usageRefundCount: z.number().int().optional(),
  feeRefundCount: z.number().int().optional(),
});

export function revenueStatsFromJSON(
  jsonString: string,
): SafeParseResult<RevenueStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevenueStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevenueStats' from JSON`,
  );
}
