/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PriceFeature, PriceFeature$inboundSchema } from "./pricefeature.js";
import { PriceModel, PriceModel$inboundSchema } from "./pricemodel.js";
import {
  PriceProperties,
  PriceProperties$inboundSchema,
} from "./priceproperties.js";
import { PriceTax, PriceTax$inboundSchema } from "./pricetax.js";
import { RateType, RateType$inboundSchema } from "./ratetype.js";

export const SchemasPriceObject = {
  Price: "price",
} as const;
export type SchemasPriceObject = ClosedEnum<typeof SchemasPriceObject>;

export const SchemasPricePaymentTerm = {
  InArrears: "in_arrears",
  InAdvance: "in_advance",
} as const;
export type SchemasPricePaymentTerm = ClosedEnum<
  typeof SchemasPricePaymentTerm
>;

export type SchemasPrice = {
  /**
   * Unique identifier for a price
   */
  id: string;
  object: SchemasPriceObject;
  /**
   * Unique identifier for a billable metric
   */
  billableMetricId?: string | undefined;
  /**
   * The unique identifier for the fee referred to by this price. Present when price is linked to a fee.
   */
  feeId?: string | undefined;
  /**
   * Unique identifier for a pricing unit
   */
  pricingUnitId?: string | undefined;
  /**
   * Unique identifier for an organization
   */
  merchantId: string;
  /**
   * ISO 8601 duration. 'P0D' for one-time, 'P1M' for monthly, 'P1Y' for yearly. Required for fees, optional for billable metrics. Defaults to plan's billingCadence if not specified.
   */
  billingCadence?: string | null | undefined;
  createdAt: Date;
  invoiceDisplayName: string;
  /**
   * Presentation only. Prices sharing this value, within one billing period, print as a single row on the rendered invoice PDF and are described by this string. Every member still bills its own line item on the ledger, this API and the compliance document. The combined row's rate is derived from the members' own rates. Requires the 'standard' pricing model. Sample values: 'Cross Border Fees', 'FX Fees'
   */
  invoiceDisplayGroup?: string | null | undefined;
  /**
   * Pricing model of a price as returned by the API. Includes the legacy models ('dynamic', 'percentage') retained for existing prices; 'standard' and 'volume' can be created (see PriceModelInput).
   */
  model?: PriceModel | undefined;
  paymentTerm: SchemasPricePaymentTerm;
  properties: PriceProperties;
  updatedAt: Date;
  /**
   * Features associated with this price
   */
  features?: Array<PriceFeature> | undefined;
  /**
   * When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
   */
  grantDiscountEnabled: boolean;
  /**
   * A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close.
   */
  isObligation: boolean;
  /**
   * What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
   */
  rateType?: RateType | undefined;
  /**
   * A price's tax declaration. Optional on write — a price that declares nothing is `IN_SCOPE`, and is billed and taxed exactly as it was before this object existed. Always present on read. Replaced as a whole on update: send the object to change it, omit it to leave it alone.
   */
  tax: PriceTax;
  /**
   * Quantity for invoice line items. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1.
   */
  quantity: number;
};

/** @internal */
export const SchemasPriceObject$inboundSchema: z.ZodNativeEnum<
  typeof SchemasPriceObject
> = z.nativeEnum(SchemasPriceObject);

/** @internal */
export const SchemasPricePaymentTerm$inboundSchema: z.ZodNativeEnum<
  typeof SchemasPricePaymentTerm
> = z.nativeEnum(SchemasPricePaymentTerm);

/** @internal */
export const SchemasPrice$inboundSchema: z.ZodType<
  SchemasPrice,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: SchemasPriceObject$inboundSchema.default("price"),
  billableMetricId: z.string().optional(),
  feeId: z.string().optional(),
  pricingUnitId: z.string().optional(),
  merchantId: z.string(),
  billingCadence: z.nullable(z.string()).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  invoiceDisplayName: z.string(),
  invoiceDisplayGroup: z.nullable(z.string()).optional(),
  model: PriceModel$inboundSchema.optional(),
  paymentTerm: SchemasPricePaymentTerm$inboundSchema,
  properties: PriceProperties$inboundSchema,
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  features: z.array(PriceFeature$inboundSchema).optional(),
  grantDiscountEnabled: z.boolean().default(false),
  isObligation: z.boolean().default(false),
  rateType: RateType$inboundSchema.optional(),
  tax: PriceTax$inboundSchema,
  quantity: z.number().int(),
});

export function schemasPriceFromJSON(
  jsonString: string,
): SafeParseResult<SchemasPrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasPrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasPrice' from JSON`,
  );
}
