/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const SchemasPaymentSessionObject = {
  PaymentSession: "payment_session",
} as const;
export type SchemasPaymentSessionObject = ClosedEnum<
  typeof SchemasPaymentSessionObject
>;

/**
 * Lifecycle status of the session.
 */
export const SchemasPaymentSessionStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Failed: "failed",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
/**
 * Lifecycle status of the session.
 */
export type SchemasPaymentSessionStatus = ClosedEnum<
  typeof SchemasPaymentSessionStatus
>;

export type SchemasPaymentSession = {
  object: SchemasPaymentSessionObject;
  /**
   * Payment session ID (ps_*).
   */
  id: string;
  /**
   * Type of entity the session pays for (invoice, subscription, payment, topup).
   */
  entityType: string;
  /**
   * ID of the entity the session pays for.
   */
  entityId: string;
  /**
   * Amount in decimal dollars.
   */
  amount: string;
  /**
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Lifecycle status of the session.
   */
  status: SchemasPaymentSessionStatus;
  /**
   * Stripe Connect account ID (acct_*) when the session is routed to a connected account.
   */
  merchantPaymentAccountId?: string | null | undefined;
  /**
   * Timestamp the session reached terminal completion. Null until the session completes.
   */
  completedAt?: Date | null | undefined;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const SchemasPaymentSessionObject$inboundSchema: z.ZodNativeEnum<
  typeof SchemasPaymentSessionObject
> = z.nativeEnum(SchemasPaymentSessionObject);

/** @internal */
export const SchemasPaymentSessionStatus$inboundSchema: z.ZodNativeEnum<
  typeof SchemasPaymentSessionStatus
> = z.nativeEnum(SchemasPaymentSessionStatus);

/** @internal */
export const SchemasPaymentSession$inboundSchema: z.ZodType<
  SchemasPaymentSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: SchemasPaymentSessionObject$inboundSchema,
  id: z.string(),
  entityType: z.string(),
  entityId: z.string(),
  amount: z.string(),
  currency: z.string(),
  status: SchemasPaymentSessionStatus$inboundSchema,
  merchantPaymentAccountId: z.nullable(z.string()).optional(),
  completedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function schemasPaymentSessionFromJSON(
  jsonString: string,
): SafeParseResult<SchemasPaymentSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasPaymentSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasPaymentSession' from JSON`,
  );
}
