/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const SchemasBillingScheduleObject = {
  BillingSchedule: "billing_schedule",
} as const;
export type SchemasBillingScheduleObject = ClosedEnum<
  typeof SchemasBillingScheduleObject
>;

export const SchemasBillingScheduleStatus = {
  Draft: "draft",
  Active: "active",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type SchemasBillingScheduleStatus = ClosedEnum<
  typeof SchemasBillingScheduleStatus
>;

export const SchemasBillingScheduleAlignmentPolicy = {
  Anchor: "anchor",
  Calendar: "calendar",
  Coterm: "coterm",
} as const;
export type SchemasBillingScheduleAlignmentPolicy = ClosedEnum<
  typeof SchemasBillingScheduleAlignmentPolicy
>;

export const SchemasBillingScheduleProrationPolicy = {
  None: "none",
  Daily: "daily",
} as const;
export type SchemasBillingScheduleProrationPolicy = ClosedEnum<
  typeof SchemasBillingScheduleProrationPolicy
>;

export const SchemasBillingSchedulePeriodPreset = {
  Single: "single",
  P1M: "P1M",
  P3M: "P3M",
  P6M: "P6M",
  P1Y: "P1Y",
  Custom: "custom",
} as const;
export type SchemasBillingSchedulePeriodPreset = ClosedEnum<
  typeof SchemasBillingSchedulePeriodPreset
>;

export type SchemasBillingSchedule = {
  id: string;
  object: SchemasBillingScheduleObject;
  orderId?: string | null | undefined;
  subscriptionId?: string | null | undefined;
  merchantId: string;
  status: SchemasBillingScheduleStatus;
  startDate: Date;
  /**
   * The schedule's end date. Always present.
   */
  endDate: Date | null;
  billingAnchor: Date;
  alignmentPolicy: SchemasBillingScheduleAlignmentPolicy;
  prorationPolicy: SchemasBillingScheduleProrationPolicy;
  paymentTermDays?: number | null | undefined;
  periodPreset: SchemasBillingSchedulePeriodPreset;
  customPeriodWindows: Array<any>;
  metadata: { [k: string]: any };
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null | undefined;
};

/** @internal */
export const SchemasBillingScheduleObject$inboundSchema: z.ZodNativeEnum<
  typeof SchemasBillingScheduleObject
> = z.nativeEnum(SchemasBillingScheduleObject);

/** @internal */
export const SchemasBillingScheduleStatus$inboundSchema: z.ZodNativeEnum<
  typeof SchemasBillingScheduleStatus
> = z.nativeEnum(SchemasBillingScheduleStatus);

/** @internal */
export const SchemasBillingScheduleAlignmentPolicy$inboundSchema:
  z.ZodNativeEnum<typeof SchemasBillingScheduleAlignmentPolicy> = z.nativeEnum(
    SchemasBillingScheduleAlignmentPolicy,
  );

/** @internal */
export const SchemasBillingScheduleProrationPolicy$inboundSchema:
  z.ZodNativeEnum<typeof SchemasBillingScheduleProrationPolicy> = z.nativeEnum(
    SchemasBillingScheduleProrationPolicy,
  );

/** @internal */
export const SchemasBillingSchedulePeriodPreset$inboundSchema: z.ZodNativeEnum<
  typeof SchemasBillingSchedulePeriodPreset
> = z.nativeEnum(SchemasBillingSchedulePeriodPreset);

/** @internal */
export const SchemasBillingSchedule$inboundSchema: z.ZodType<
  SchemasBillingSchedule,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: SchemasBillingScheduleObject$inboundSchema,
  orderId: z.nullable(z.string()).optional(),
  subscriptionId: z.nullable(z.string()).optional(),
  merchantId: z.string(),
  status: SchemasBillingScheduleStatus$inboundSchema,
  startDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  endDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  billingAnchor: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  alignmentPolicy: SchemasBillingScheduleAlignmentPolicy$inboundSchema,
  prorationPolicy: SchemasBillingScheduleProrationPolicy$inboundSchema,
  paymentTermDays: z.nullable(z.number().int()).optional(),
  periodPreset: SchemasBillingSchedulePeriodPreset$inboundSchema,
  customPeriodWindows: z.array(z.any()),
  metadata: z.record(z.any()),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function schemasBillingScheduleFromJSON(
  jsonString: string,
): SafeParseResult<SchemasBillingSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasBillingSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasBillingSchedule' from JSON`,
  );
}
