/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { RuleCondition, RuleCondition$inboundSchema } from "./rulecondition.js";

/**
 * An auto-acceptance rule that automatically approves source events matching specified conditions. Rules help automate the approval process for trusted customers or specific transaction patterns.
 */
export type SourceRule = {
  /**
   * Unique identifier for the rule
   */
  id: string;
  /**
   * List of conditions that must ALL be met (AND logic)
   */
  conditions: Array<RuleCondition>;
  /**
   * When the rule was created
   */
  createdAt: Date;
  /**
   * User ID who created the rule
   */
  createdBy?: string | null | undefined;
  /**
   * Detailed description of what this source rule does
   */
  description: string;
  /**
   * Whether this rule is currently active
   */
  enabled: boolean;
  /**
   * Total number of times this rule has been evaluated
   */
  evaluationCount: number;
  /**
   * Last time this rule was evaluated against an invoice
   */
  lastEvaluatedAt?: Date | null | undefined;
  /**
   * Number of times this rule has matched and auto-accepted an invoice
   */
  matchCount: number;
  /**
   * Human-readable name for the source rule
   */
  name: string;
  /**
   * Priority order for rule evaluation (lower numbers are evaluated first)
   */
  order: number;
  /**
   * ID of the source this rule belongs to
   */
  sourceId: string;
  /**
   * When the rule was last updated
   */
  updatedAt: Date;
};

/** @internal */
export const SourceRule$inboundSchema: z.ZodType<
  SourceRule,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  conditions: z.array(RuleCondition$inboundSchema),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  createdBy: z.nullable(z.string()).optional(),
  description: z.string(),
  enabled: z.boolean(),
  evaluationCount: z.number().int(),
  lastEvaluatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  matchCount: z.number().int(),
  name: z.string(),
  order: z.number().int(),
  sourceId: z.string(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function sourceRuleFromJSON(
  jsonString: string,
): SafeParseResult<SourceRule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SourceRule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SourceRule' from JSON`,
  );
}
