/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const SourceEventStatus = {
  Pending: "pending",
  Processed: "processed",
  Failed: "failed",
  Rejected: "rejected",
} as const;
export type SourceEventStatus = ClosedEnum<typeof SourceEventStatus>;

export type SourceEvent = {
  /**
   * Unique identifier for a source event
   */
  id: string;
  createdAt: Date;
  /**
   * The customer associated with this source event
   */
  customerId?: string | undefined;
  errorMessage?: string | undefined;
  externalEventId: string;
  processedAt?: Date | undefined;
  processedBy?: string | undefined;
  rawData: { [k: string]: any };
  /**
   * Unique identifier for a source
   */
  sourceId: string;
  status: SourceEventStatus;
  /**
   * The subscription associated with this source event
   */
  subscriptionId?: string | undefined;
  updatedAt: Date;
  usageEventIds?: Array<string> | undefined;
};

/** @internal */
export const SourceEventStatus$inboundSchema: z.ZodNativeEnum<
  typeof SourceEventStatus
> = z.nativeEnum(SourceEventStatus);

/** @internal */
export const SourceEvent$inboundSchema: z.ZodType<
  SourceEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  customerId: z.string().optional(),
  errorMessage: z.string().optional(),
  externalEventId: z.string(),
  processedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  processedBy: z.string().optional(),
  rawData: z.record(z.any()),
  sourceId: z.string(),
  status: SourceEventStatus$inboundSchema,
  subscriptionId: z.string().optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  usageEventIds: z.array(z.string()).optional(),
});

export function sourceEventFromJSON(
  jsonString: string,
): SafeParseResult<SourceEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SourceEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SourceEvent' from JSON`,
  );
}
