/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EntitlementStatus,
  EntitlementStatus$inboundSchema,
} from "./entitlementstatus.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Common fields shared by all entitlement list items. List items use `entitlementId` (not `id`) to preserve the original public field name on `/v1/entitlements`. The get-by-id endpoint returns the same object with a top-level `id` and `object: "entitlement"` instead.
 */
export type StaticEntitlementListItem = {
  /**
   * Unique identifier for the entitlement.
   */
  entitlementId: string;
  /**
   * Unique identifier for a customer
   */
  customerId: string;
  /**
   * The feature this entitlement grants access to.
   */
  featureId: string;
  /**
   * The unique key identifying the feature.
   */
  featureKey: string;
  featureType: "static";
  /**
   * Unique identifier for a product
   */
  productId: string;
  /**
   * The subscription this entitlement is associated with, if any.
   */
  subscriptionId: string | null;
  /**
   * Current status of the entitlement.
   */
  status: EntitlementStatus;
  /**
   * When the entitlement becomes active.
   */
  activeFrom: Date;
  /**
   * When the entitlement expires. Null means no expiration.
   */
  activeTo: Date | null;
  /**
   * Whether the customer currently has active access to this entitlement.
   */
  hasAccess: boolean;
  /**
   * Additional metadata for the entitlement.
   */
  metadata: { [k: string]: string };
  /**
   * Configuration values for this entitlement.
   */
  config: { [k: string]: any };
};

/** @internal */
export const StaticEntitlementListItem$inboundSchema: z.ZodType<
  StaticEntitlementListItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  entitlementId: z.string(),
  customerId: z.string(),
  featureId: z.string(),
  featureKey: z.string(),
  featureType: z.literal("static"),
  productId: z.string(),
  subscriptionId: z.nullable(z.string()),
  status: EntitlementStatus$inboundSchema,
  activeFrom: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  activeTo: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  hasAccess: z.boolean(),
  metadata: z.record(z.string()),
  config: z.record(z.any()),
});

export function staticEntitlementListItemFromJSON(
  jsonString: string,
): SafeParseResult<StaticEntitlementListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StaticEntitlementListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StaticEntitlementListItem' from JSON`,
  );
}
