/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const SubscriptionObject = {
  Subscription: "subscription",
} as const;
export type SubscriptionObject = ClosedEnum<typeof SubscriptionObject>;

/**
 * Invoice 0 awaiting merchant approval before payment can proceed. The invoice is in DRAFT status with totals calculated. Approval is currently platform-only — do not call PATCH /v2/invoices/{id} with {"trigger": "APPROVE"} from merchant credentials (it will return 403). A merchant-accessible approval endpoint is planned for PAYG-754.
 */
export type PaymentAwaitingApproval = {
  /**
   * The Invoice 0 id awaiting approval
   */
  invoiceId: string;
  /**
   * Total payment amount in decimal dollar format
   */
  amount: string;
  /**
   * Payment status
   */
  status: "awaiting_approval";
};

/**
 * Zero-amount Invoice 0 that completed synchronously to PAID
 */
export type PaymentPaid = {
  /**
   * The Invoice 0 id
   */
  invoiceId: string;
  /**
   * Payment amount ('0' for zero-amount subscriptions)
   */
  amount: string;
  /**
   * Payment status
   */
  status: "paid";
};

/**
 * Breakdown of payment amount
 */
export type Breakdown = {
  /**
   * One-time flat fee charges in decimal dollar format. Sample values: '50.00' equals $50.00 setup fee, '100.00' equals $100.00 activation fee
   */
  upfrontCharges: string;
  /**
   * Wallet charge amount in decimal dollar format.
   */
  walletCharge: string;
};

export type PaymentPending = {
  /**
   * Total payment amount in decimal dollar format. Sample values: '250.00' equals $250.00, '99.99' equals $99.99
   */
  amount: string;
  /**
   * Breakdown of payment amount
   */
  breakdown: Breakdown;
  /**
   * Checkout page URL for customer payment completion.
   */
  checkoutUrl: string;
  /**
   * ID of the invoice linked to this payment.
   */
  invoiceId?: string | undefined;
  /**
   * Payment session identifier for upfront payment processing.
   */
  paymentSessionId: string;
  /**
   * Payment status
   */
  status: "pending";
};

/**
 * Payment session details when upfront payment is required, or confirmation of a zero-amount paid invoice
 */
export type PaymentUnion =
  | PaymentPending
  | PaymentPaid
  | PaymentAwaitingApproval;

export const SubscriptionStatusEnum = {
  PendingPayment: "pending_payment",
  Active: "active",
  Terminated: "terminated",
} as const;
export type SubscriptionStatusEnum = ClosedEnum<typeof SubscriptionStatusEnum>;

export type Merchant = {
  id: string;
  name: string;
  email: string;
};

export type Consumer = {
  id: string;
  name: string;
  email: string;
};

/**
 * Customer details with merchant and consumer information. Only included when include=customer is specified in the list query.
 */
export type SubscriptionCustomer = {
  /**
   * Customer ID
   */
  id?: string | undefined;
  /**
   * Merchant organization ID
   */
  merchantId?: string | undefined;
  merchant?: Merchant | undefined;
  consumer?: Consumer | undefined;
};

export type Subscription = {
  id: string;
  object: SubscriptionObject;
  /**
   * Whether automatic charging is enabled for this subscription. When true, invoices will be automatically paid using stored payment methods.
   */
  autoCharge: boolean;
  createdAt: Date;
  customerId: string;
  endingAt?: Date | undefined;
  /**
   * Projected tax percentage rate. Sample values: 8.875 indicates 8.875% tax rate, 10.0 indicates 10% tax rate, 0 indicates no tax applied
   */
  estimatedTaxRate?: number | undefined;
  /**
   * When true, tax rate is forced to 0%.
   */
  taxExempt: boolean;
  name: string;
  /**
   * Payment session details when upfront payment is required, or confirmation of a zero-amount paid invoice
   */
  payment?: PaymentPending | PaymentPaid | PaymentAwaitingApproval | undefined;
  planId: string;
  /**
   * @deprecated Use minimumAccountBalance instead. Minimum required wallet balance in atomic units. Sample values: '200000000000' equals $200.00 minimum, '1000000000000' equals $1000.00 minimum
   */
  prefundAmount?: string | undefined;
  /**
   * Minimum wallet balance requirement in nanodollars. Can be '0' to disable. The system calculates the difference between this minimum and the customer's current balance, charging only what's needed to reach the minimum. Note: If the calculated charge amount is below payment processor minimums (typically $1.00), the actual charged amount may be automatically adjusted upward to meet the minimum requirement. Sample values: '200000000000' equals $200.00 minimum, '1000000000000' equals $1000.00 minimum
   */
  minimumAccountBalance?: string | undefined;
  startedAt: Date;
  status: SubscriptionStatusEnum;
  terminatedAt?: Date | undefined;
  /**
   * ID of who terminated the subscription (customer ID or merchant ID)
   */
  terminatedBy?: string | undefined;
  /**
   * Reason for termination
   */
  terminationReason?: string | undefined;
  /**
   * Test clock ID if this subscription is attached to a test clock. Only present in non-production environments.
   */
  testClockId?: string | undefined;
  updatedAt: Date;
  /**
   * Optional (virtual) wallet ID for the subscription
   */
  walletId?: string | undefined;
  /**
   * Whether renewal reminder emails are enabled for this subscription. Null means use plan default.
   */
  renewalReminderEnabled?: boolean | null | undefined;
  /**
   * Number of days before renewal to send the reminder. Null means use plan default.
   */
  renewalReminderDays?: number | null | undefined;
  /**
   * Customer details with merchant and consumer information. Only included when include=customer is specified in the list query.
   */
  customer?: SubscriptionCustomer | undefined;
};

/** @internal */
export const SubscriptionObject$inboundSchema: z.ZodNativeEnum<
  typeof SubscriptionObject
> = z.nativeEnum(SubscriptionObject);

/** @internal */
export const PaymentAwaitingApproval$inboundSchema: z.ZodType<
  PaymentAwaitingApproval,
  z.ZodTypeDef,
  unknown
> = z.object({
  invoiceId: z.string(),
  amount: z.string(),
  status: z.literal("awaiting_approval"),
});

export function paymentAwaitingApprovalFromJSON(
  jsonString: string,
): SafeParseResult<PaymentAwaitingApproval, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentAwaitingApproval$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentAwaitingApproval' from JSON`,
  );
}

/** @internal */
export const PaymentPaid$inboundSchema: z.ZodType<
  PaymentPaid,
  z.ZodTypeDef,
  unknown
> = z.object({
  invoiceId: z.string(),
  amount: z.string(),
  status: z.literal("paid"),
});

export function paymentPaidFromJSON(
  jsonString: string,
): SafeParseResult<PaymentPaid, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentPaid$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentPaid' from JSON`,
  );
}

/** @internal */
export const Breakdown$inboundSchema: z.ZodType<
  Breakdown,
  z.ZodTypeDef,
  unknown
> = z.object({
  upfrontCharges: z.string(),
  walletCharge: z.string(),
});

export function breakdownFromJSON(
  jsonString: string,
): SafeParseResult<Breakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Breakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Breakdown' from JSON`,
  );
}

/** @internal */
export const PaymentPending$inboundSchema: z.ZodType<
  PaymentPending,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string(),
  breakdown: z.lazy(() => Breakdown$inboundSchema),
  checkoutUrl: z.string(),
  invoiceId: z.string().optional(),
  paymentSessionId: z.string(),
  status: z.literal("pending"),
});

export function paymentPendingFromJSON(
  jsonString: string,
): SafeParseResult<PaymentPending, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentPending$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentPending' from JSON`,
  );
}

/** @internal */
export const PaymentUnion$inboundSchema: z.ZodType<
  PaymentUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PaymentPending$inboundSchema),
  z.lazy(() => PaymentPaid$inboundSchema),
  z.lazy(() => PaymentAwaitingApproval$inboundSchema),
]);

export function paymentUnionFromJSON(
  jsonString: string,
): SafeParseResult<PaymentUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentUnion' from JSON`,
  );
}

/** @internal */
export const SubscriptionStatusEnum$inboundSchema: z.ZodNativeEnum<
  typeof SubscriptionStatusEnum
> = z.nativeEnum(SubscriptionStatusEnum);

/** @internal */
export const Merchant$inboundSchema: z.ZodType<
  Merchant,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
});

export function merchantFromJSON(
  jsonString: string,
): SafeParseResult<Merchant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Merchant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Merchant' from JSON`,
  );
}

/** @internal */
export const Consumer$inboundSchema: z.ZodType<
  Consumer,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
});

export function consumerFromJSON(
  jsonString: string,
): SafeParseResult<Consumer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Consumer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Consumer' from JSON`,
  );
}

/** @internal */
export const SubscriptionCustomer$inboundSchema: z.ZodType<
  SubscriptionCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  merchantId: z.string().optional(),
  merchant: z.lazy(() => Merchant$inboundSchema).optional(),
  consumer: z.lazy(() => Consumer$inboundSchema).optional(),
});

export function subscriptionCustomerFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionCustomer' from JSON`,
  );
}

/** @internal */
export const Subscription$inboundSchema: z.ZodType<
  Subscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: SubscriptionObject$inboundSchema,
  autoCharge: z.boolean().default(false),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  customerId: z.string(),
  endingAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  estimatedTaxRate: z.number().optional(),
  taxExempt: z.boolean().default(false),
  name: z.string(),
  payment: z.union([
    z.lazy(() => PaymentPending$inboundSchema),
    z.lazy(() => PaymentPaid$inboundSchema),
    z.lazy(() => PaymentAwaitingApproval$inboundSchema),
  ]).optional(),
  planId: z.string(),
  prefundAmount: z.string().optional(),
  minimumAccountBalance: z.string().optional(),
  startedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  status: SubscriptionStatusEnum$inboundSchema,
  terminatedAt: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  terminatedBy: z.string().optional(),
  terminationReason: z.string().optional(),
  testClockId: z.string().optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  walletId: z.string().optional(),
  renewalReminderEnabled: z.nullable(z.boolean()).optional(),
  renewalReminderDays: z.nullable(z.number().int()).optional(),
  customer: z.lazy(() => SubscriptionCustomer$inboundSchema).optional(),
});

export function subscriptionFromJSON(
  jsonString: string,
): SafeParseResult<Subscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subscription' from JSON`,
  );
}
