/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * approved/rejected: reviewer decision (maker-checker enforced). cancelled: recall a pending approval or reopen an approved one.
 */
export const UpdateApprovalRequestDecision = {
  Approved: "approved",
  Rejected: "rejected",
  Cancelled: "cancelled",
} as const;
/**
 * approved/rejected: reviewer decision (maker-checker enforced). cancelled: recall a pending approval or reopen an approved one.
 */
export type UpdateApprovalRequestDecision = ClosedEnum<
  typeof UpdateApprovalRequestDecision
>;

export type UpdateApprovalRequest = {
  /**
   * approved/rejected: reviewer decision (maker-checker enforced). cancelled: recall a pending approval or reopen an approved one.
   */
  decision: UpdateApprovalRequestDecision;
  note?: string | null | undefined;
  /**
   * Optional. The real user id performing the action. Used when the request is made via a platform-level key on behalf of a human user. Ignored when the caller is a non-platform API key.
   */
  actorId?: string | undefined;
};

/** @internal */
export const UpdateApprovalRequestDecision$outboundSchema: z.ZodNativeEnum<
  typeof UpdateApprovalRequestDecision
> = z.nativeEnum(UpdateApprovalRequestDecision);

/** @internal */
export type UpdateApprovalRequest$Outbound = {
  decision: string;
  note?: string | null | undefined;
  actorId?: string | undefined;
};

/** @internal */
export const UpdateApprovalRequest$outboundSchema: z.ZodType<
  UpdateApprovalRequest$Outbound,
  z.ZodTypeDef,
  UpdateApprovalRequest
> = z.object({
  decision: UpdateApprovalRequestDecision$outboundSchema,
  note: z.nullable(z.string()).optional(),
  actorId: z.string().optional(),
});

export function updateApprovalRequestToJSON(
  updateApprovalRequest: UpdateApprovalRequest,
): string {
  return JSON.stringify(
    UpdateApprovalRequest$outboundSchema.parse(updateApprovalRequest),
  );
}
