/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  RuleCondition,
  RuleCondition$Outbound,
  RuleCondition$outboundSchema,
} from "./rulecondition.js";

export type UpdateRuleRequest = {
  /**
   * List of conditions that must ALL be met (AND logic)
   */
  conditions?: Array<RuleCondition> | undefined;
  /**
   * Detailed description of what this source rule does
   */
  description?: string | undefined;
  /**
   * Whether this rule should be active
   */
  enabled?: boolean | undefined;
  /**
   * Human-readable name for the source rule
   */
  name?: string | undefined;
  /**
   * Priority order for rule evaluation (lower numbers are evaluated first)
   */
  order?: number | undefined;
};

/** @internal */
export type UpdateRuleRequest$Outbound = {
  conditions?: Array<RuleCondition$Outbound> | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  name?: string | undefined;
  order?: number | undefined;
};

/** @internal */
export const UpdateRuleRequest$outboundSchema: z.ZodType<
  UpdateRuleRequest$Outbound,
  z.ZodTypeDef,
  UpdateRuleRequest
> = z.object({
  conditions: z.array(RuleCondition$outboundSchema).optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  name: z.string().optional(),
  order: z.number().int().optional(),
});

export function updateRuleRequestToJSON(
  updateRuleRequest: UpdateRuleRequest,
): string {
  return JSON.stringify(
    UpdateRuleRequest$outboundSchema.parse(updateRuleRequest),
  );
}
