/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const UsageResponseObject = {
  Meter: "meter",
} as const;
export type UsageResponseObject = ClosedEnum<typeof UsageResponseObject>;

export type WindowedValue = {
  windowStart: Date;
  windowEnd: Date;
  value: number;
};

export type GroupedValue = {
  groupBy: { [k: string]: string };
  value: number;
};

export type UsageResponse = {
  object: UsageResponseObject;
  /**
   * Unique identifier for a billable metric
   */
  billableMetricId: string;
  /**
   * Total aggregated value across the query window
   */
  totalValue: number;
  /**
   * Time-bucketed values. Only present when windowSize is specified.
   */
  windowedValues?: Array<WindowedValue> | undefined;
  /**
   * Dimension-grouped values. Only present when groupBy is specified.
   */
  groupedValues?: Array<GroupedValue> | undefined;
};

/** @internal */
export const UsageResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof UsageResponseObject
> = z.nativeEnum(UsageResponseObject);

/** @internal */
export const WindowedValue$inboundSchema: z.ZodType<
  WindowedValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  windowStart: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  windowEnd: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  value: z.number(),
});

export function windowedValueFromJSON(
  jsonString: string,
): SafeParseResult<WindowedValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WindowedValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WindowedValue' from JSON`,
  );
}

/** @internal */
export const GroupedValue$inboundSchema: z.ZodType<
  GroupedValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  groupBy: z.record(z.string()),
  value: z.number(),
});

export function groupedValueFromJSON(
  jsonString: string,
): SafeParseResult<GroupedValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupedValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupedValue' from JSON`,
  );
}

/** @internal */
export const UsageResponse$inboundSchema: z.ZodType<
  UsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: UsageResponseObject$inboundSchema.default("meter"),
  billableMetricId: z.string(),
  totalValue: z.number(),
  windowedValues: z.array(z.lazy(() => WindowedValue$inboundSchema)).optional(),
  groupedValues: z.array(z.lazy(() => GroupedValue$inboundSchema)).optional(),
});

export function usageResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageResponse' from JSON`,
  );
}
