/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { Address, Address$inboundSchema } from "./address.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const UserObject = {
  User: "user",
} as const;
export type UserObject = ClosedEnum<typeof UserObject>;

export const State = {
  Invited: "invited",
  Active: "active",
  Suspended: "suspended",
} as const;
export type State = ClosedEnum<typeof State>;

export type UserOrganization = {
  /**
   * Unique identifier for an organization
   */
  id?: string | undefined;
  state?: State | undefined;
};

export const UserType = {
  Company: "COMPANY",
  Individual: "INDIVIDUAL",
} as const;
export type UserType = ClosedEnum<typeof UserType>;

export type User = {
  /**
   * Unique identifier for a user
   */
  id: string;
  object: UserObject;
  address?: Address | undefined;
  createdAt: Date;
  dateOfBirth?: RFCDate | undefined;
  email: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  organizations: Array<UserOrganization>;
  oryId: string;
  phone?: string | undefined;
  type?: UserType | undefined;
  updatedAt: Date;
};

/** @internal */
export const UserObject$inboundSchema: z.ZodNativeEnum<typeof UserObject> = z
  .nativeEnum(UserObject);

/** @internal */
export const State$inboundSchema: z.ZodNativeEnum<typeof State> = z.nativeEnum(
  State,
);

/** @internal */
export const UserOrganization$inboundSchema: z.ZodType<
  UserOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  state: State$inboundSchema.optional(),
});

export function userOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<UserOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserOrganization' from JSON`,
  );
}

/** @internal */
export const UserType$inboundSchema: z.ZodNativeEnum<typeof UserType> = z
  .nativeEnum(UserType);

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    object: UserObject$inboundSchema.default("user"),
    address: Address$inboundSchema.optional(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    dateOfBirth: z.string().transform(v => new RFCDate(v)).optional(),
    email: z.string(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    organizations: z.array(z.lazy(() => UserOrganization$inboundSchema)),
    oryId: z.string(),
    phone: z.string().optional(),
    type: UserType$inboundSchema.optional(),
    updatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  });

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
